### ISSUE TITLE
Meet with Jim about ATMAP specifications

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1008]

**Comment by mouneyrac** [comment]
Jim wants to be able to transform all current modules (from the live alpha version) into Follow Ups. But he wants only one Add button that creates a new empty version for all of them. This is not supported yet by RDRF.

I suggested having all modules replaced by one big follow up form. Jim is okay with this solution, especially as he would not have to click on each form to navigate between data.

As for the locking feature, Jim is ok for the simple solution of locking all the followups for everybody and unlocking all the followups for everybody.
