### ISSUE TITLE
CIC CRC: Hidden fields error

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1021]
After #1018 in effect. 

Data in hidden fields was added via an admin account, and saved successfully. Admin account was then logged out, and clinician account logged in. Data for country of birth was edited, and an attempt made to save the page. The page was not saved due to a validation error relating to a hidden field, with the note;
>Patient date of migration: Enter a valid date.

The error highlight creates a space between the CDE above and below where the hidden field should be present for an admin user, and marks it with "*Enter a valid date.", as shown in the image below;
![hidfielderror_small](https://user-images.githubusercontent.com/50615516/66446538-87b35800-ea7d-11e9-95b3-bcdd74ca0ccb.png)

EDIT:
As admin, removed date of migration on patient record, saved successfully, and logged out. Logged in as clinician, edited patient's country of birth and attempted to save. This saved successfully, implying that the date of migration hidden field is the only problematic field.

**Comment by id2359** [comment]
The hidden fields shouldn't really be seen even by an admin:

The implementation of the feature was confused : 

There is a difference between:

a) specifying what demographics fields a given registry requires ( at all)
b) limiting what different groups see

I think with the current implementation it's not possible to  do a)  - we do b) but the admn always can see i
