### ISSUE TITLE
Pre-prod QA: test plan

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#1038]
### Tasks

- [x] change password
- [x] proms: input field
- [x] 2fa
- [x] display name when importing registry
- [x] regression testing

### Description

We need to run a "final" QA before switching our CIC Midland environment from UAT to Prod this coming Wednesday.

Go to CIC staging to do the tests: https://rdrf.ccgapps.com.au/cicclinical

First we need to tests:
* changing password (no link should appear to change password except for the admin when going on a user page)
* proms: the proms should have an input text field - check it works - try to break it
* 2fa authentication - test on a differenty user
* display name (they should be present when importing a new registry)

Finally do some regression testing, i.e. try to catch the maximum of unkown bugs (if you find a bug check on Github issues if it exists first) as possible.
Try with admin and then a Clinical Staff user without superuser permission.
Main feature to test is the entire section starting when clicking from Patient lists link (all forms, add, edit, proms, etc...)

**Comment by id2359** [comment]
The tests should be performed on Midland Prod namespace of Rancher

**Comment by id2359** [comment]
Jerome - the input text field proms should be testable on staging now ( cron was switched back on)

**Comment by mouneyrac** [comment]
I'll redo a full staging QA once we get the new staging deployment today.

**Comment by mouneyrac** [comment]
retesting all

**Comment by mouneyrac** [comment]
all good
