### ISSUE TITLE
Patient list columns are hardcoded

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#1040]
Angela would like to hide ‘genetic data’ column. 

We need to implement some kind of hide column feature or list of enable columns.
Could be an admin settings or env settings, but I think it should be an admin settings.

**Comment by id2359** [comment]
I already have for clinical staff - she can see it because she's an admin.


There's a permission on auth groups ( see admin interface , look at Groups )  for controlling columns

I've hidden columns in Rancher for Clinical Staff using it (including Genetic )
