### ISSUE TITLE
CIC CRC PROMS surveys: Employment question error

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1045]
In RDRF staging environment; in both Baseline PROMS and FollowUp PROMS. When answering CDE `Employ_status` ("What is your current employment status?") as "Employed", and CDE `Employ_type` ("If employed, what type of employment do you undertake?") as any or none.

Upon answering `Employ_type` and continuing, the page becomes blank, with no elements to interact with. `Employ_type` may also be left unanswered, and continuing causes the page to become blank. This causes the survey to become inoperable.

**Comment by id2359** [comment]
I bumped version to 6.0.14 pushed next_release branch just now containing this fix -
