### ISSUE TITLE
Update project name in rancher

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#1046]
Mihai email:

In regards to the naming of the Production environment – after some internal discussion the following was decided:
* We will keep the existing CIC Project Name
* The name of the Production CIC for Midland will be cic-crc-mi (created inside the CIC project)

 I noticed that there is a clone function within Rancher’s  workloads, but not for workspaces as such.

So when we are ready to go to Prod if you could create the new namespace as mentioned above that will be great.

**Comment by id2359** [comment]
This is really an ops ticket

**Comment by id2359** [comment]
done
