### ISSUE TITLE
Design a single APMAT form

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#1074]
Jim wants to be able to transform all current modules (from the live alpha version) into Follow Ups. But he wants only one Add button that creates a new empty version for all of them. This is not supported yet by RDRF.

I suggested having all modules replaced by one big follow up form. Jim is okay with this solution, especially as he would not have to click on each form to navigate between data.

It is like a good exercise for George :)

**Comment by mouneyrac** [comment]
Assigning to Jith.

**Comment by mouneyrac** [comment]
For the information, related issues are:
https://github.com/muccg/rdrf/issues/1026
https://github.com/muccg/rdrf/issues/1014
https://github.com/muccg/rdrf/issues/1008

**Comment by id2359** [comment]
I have moved all sections into one followup form
