### ISSUE TITLE
Family linkage - can not save twice

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#1076]
Multiple edits cannot be performed with saving in-between, if remaining on the same family linkage page; i.e. Change linkage, save, then change linkage again and attempt to save.
The family linkage URL refers to the current index patient ID. Changing the index patient then changes which patient is referred to in the URL. If successfully saving the new index/family order and refreshing the page, the refreshed page will appear blank, because the old index patient is no longer an index (and therefore is not the family linkage "anchor"). Changing the ID in the URL to the ID of the new index patient will open the correct family linkage page.

**Comment by gmaloneccg** [comment]
Passed 2019-11-19 2:30pm. Short delay (~5s) when saving changes. Green banner appears briefly if successful, and redirects to the page of the new index patient/linkage anchor.
