### ISSUE TITLE
QA - 6 Nov 2019

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#1078]
- [x] FH reports
- [x] Hide / Readonly demographic fields
- [x] consent files
- [x] PROMS emails should greet user with Firstname - Lastname (no opposite)
- [x] PROMS

### Details

**FH reports**
Test that reports works (no timeout, data seems correct)

**Hide / Readonly demographic fields**
Test that the feature to hide a demographic field works. Same for readonly. Especially test a Date input field.

**consent files**
Upload a same consent file name twice for the same user. Nothing should break.
 

**PROMS emails should greet user with Firstname - Lastname (no opposite)**
Create a PROMS (with email, not QR code)
 

**PROMS**
Just do some sanity checking with PROMS

**Comment by gmaloneccg** [comment]
Demographics fields allow "Unknown" option on the drop-down list for both readonly and hidden options, which defaults to behaviour for "No".

**Comment by mouneyrac** [comment]
- [ ] family linkage: check you see a confirmation message after saving
- [ ] proms: check that the proms are correctly displayed on mobile
- [ ] explorer (/explorer/) Enter any weird SQL, it should tell you what is the format of the first charcaters of the SQL. Enter a sql (with correct first charcater) with the wording DELETE, then UPDATE, then DROP. You should not be able to save any of that. Note you don't need to ever enter a correct one - but to be safe - just try to save the existing sql to heck it works.
- [ ] angelman : registration page: create a user then go back to the registration and use same email. An error message should be displayed.

**Comment by gmaloneccg** [comment]
Opened ticket #1081 in re: family linkage.

PROMS appear to display correctly on mobile devices, but the page for the slider "your health today" is slightly cluttered (tested on viewport for iPhone 6/7/8 and Galaxy S5) at the bottom of the page. Copyright text and progress bar/arrows slightly overlap. Progress bar/arrows are below the copyright text. Screenshot attached below;

![Viewport_S5_PROMS_overlap](https://user-images.githubusercontent.com/50615516/68281813-69a83a00-00b3-11ea-84bd-0fa78051033d.png)

**Comment by mouneyrac** [comment]
Thanks George, please write a single ticket for each issue (.i.e this last comment, thanks)
