### ISSUE TITLE
CIC PROMS: Survey reset for textbox input question

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1079]
In the Baseline PROMS survey, completed via link in browser after being sent by QR code.

After answering "employed" when asked about employment status, the next question asks what specific job is performed and provides a text box. Pressing Enter/Return when in the text box causes the survey to reset to question 1, with all previous answers cleared. The baseline survey can be otherwise completed normally.

**Comment by id2359** [comment]
Happens on cic lung too for a different textbox
