### ISSUE TITLE
FH: Report service usability issues

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1080]
For the FH report service;

1. Most reports take a long time to load, when viewing or downloading, but downloading is somewhat faster.
2. The viewing service is slow, and has caused a crash at least twice when attempting to view "FH Report 2". Other large reports were manually cancelled before loading to avoid further crashes.
3. The scroll-bar at the bottom of the pane (side-scroll) is obscured (hence unusable) at standard or 100% size. Can be viewed and used when at 90% view size, running on Firefox, on a 1920x1080 28" monitor. On the test laptop's built-in 13" screen (1366x768), the view must be 60% or less.
4. Report "testbadreport" returns a ProgrammingError traceback; this is assumed to be intentional, given the name of the report.

**Comment by id2359** [comment]
Closing stale issue
