### ISSUE TITLE
FH Family Linkage: Visual feedback issues

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1081]
For the family linkage feature;

1. Successfully saving a change of index patient does not display any message.
EDIT: Saving change of index patient does display a message, stating `Linkages updated successfully`, but appears after a short delay (~5 seconds). This may make point 7 redundant. This does not update the page to the URL with the new index patient ID.
2. Saving when making no change shows; `Linkages updated successfully`
3. Saving change of index then attempting to save any other change while still on same page displays; `FAIL: PatientRelative matching query does not exist`
4. Family linkage URL appears to be anchored at the index patient. Changing the index patient changes the patient ID in the family linkage URL. This may be relevant to points 2 and 3.
5. For index patient ID number 666. Performing two changes of index patient, with saving, in quick succession on the same page displays an error, stating;
`FAIL: duplicate key value violates unique constraint "patients_patientrelative_relative_patient_id_key" DETAIL: Key (relative_patient_id)=(666) already exists.`
6. The message banners fade fairly rapidly, which may be a usability issue.
7. When changing index patient and saving, there is a short delay before the changes take effect. This is not an error, but should be considered when testing.

**Comment by id2359** [comment]
Closing stale issue
