### ISSUE TITLE
test werkzeug update prior to merge

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1088]

**Comment by mouneyrac** [comment]
I tested the bot PR.

What werkzeug does now it to ask for a PIN. This PIN is generated when starting the dev server, you can find the PIN in the starting log (develop.sh up):

```
uwsgi_1        | Thu Nov  7 06:01:47 2019 - [emperor] vassal socket-9100.ini is ready to accept requests
uwsgi_1        | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55940b1b10a0 pid: 44 (default app)
runserver_1    |  * Debugger is active!
runserver_1    |  * Debugger PIN: 193-445-134
runserver_1    | 172.20.0.1 - - [07/Nov/2019 14:02:37] "GET /admin/ HTTP/1.1" 302 -
```

For information we use **django-extensions** app (https://django-extensions.readthedocs.io/en/latest/runserver_plus.html#debugger-pin) to load Werkzeug in Django.  Werkzeug is installed by dev-requirement.

We could pre-set the pin with the WERKZEUG_DEBUG_PIN env variable but I don't really know why you would want to do that. I think the PIN feature seems good to me as it is, as the PIN is remembered anyway. 

I  consider it as a security improvement.

My +1 to merge the bot PR.
