### ISSUE TITLE
Integer max value on integer cde shouldn't be assumed

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1094]
Integer cdes are not required to be "bounded" ( have min and max defined) - the proms client side code should handle this case correctly.

My commits enforce an implicit limit which is probably the wrong way to do this - hence reopening - Lee.

**Comment by mouneyrac** [comment]
Moving away from CIC lung milestone.

Ideal solution:
1) add a new "Proms component" DB field to CDE
2) when Proms React app detects a "slider" Proms component, then display the current slider (for Health question for example).
3) all other integer datatype should display a text input

**Comment by id2359** [comment]
JIth your changes probably invalidate this - so close it when you're done
