### ISSUE TITLE
CIC CRC: Multiple-select RadioSelect fields

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1101]
Two CDEs RADIOTXTYPECRC ("Type of radiotherapy") and CRCCompTreatment ("Type of treatment for leak or complications (select all that apply)") are RadioSelect widgets with the multiple select checkbox checked. The questions do not allow multiple selection, because they are RadioSelect widgets. The multiple select option is normally enabled for multiple selection lists only, which have the widget name field blank.

When attempting to save the page with any option selected, a validation error occurs at the question, stating "Enter a list of values". It is impossible to select more than one option. It is also impossible to deselect data if it is already selected. This makes it impossible to save the page, and all data entered must be discarded and re-entered in order to save the page. This occurs on the Baseline Treatment page, which contains a relatively large number of questions, therefore all data is lost.

**Comment by id2359** [comment]
We can edit the definition to fix these.
