### ISSUE TITLE
CIC LC PROMS: Email text

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1114]
When the CIC LC followup PROMS link is transmitted by email, the email subject states;
>ICHOM Lung Cancer FollowUpLung Survey Request

i.e. there are no spaces in the survey name. This name is identical to the name in the survey request table on staging. The email text for the baseline survey has not yet been tested, but may follow the same convention, as the name in the survey request table also lacks a space.

**Comment by jithendralal** [comment]
The display name of surveys should have spaces between words.
Currently, the display names are set without spaces and they are same as names of surveys.
BaselinePROMS
FollowUpPROMS
