### ISSUE TITLE
CIC LC PROMS: "Your health today" slider

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1116]
In the CIC LC FollowUp PROMS survey. Not yet tested for BaselinePROMS.

The question with the "Your Health Today" slider has the following description text. Some punctuation is missing.
>(We would like to know how good or bad your health is TODAY. This scale is numbered from 0 to 100. 100 means the best health you can imagine 0 means the worst health you can imagine Please tap on the scale to indicate how your health is TODAY)

Further, the copyright text appears to be pushed off the bottom of the screen on simulated (Firefox responsive design mode) mobile devices, which requires the PROMS question page to be scrolled to view the copyright text.

**Comment by mouneyrac** [comment]
created https://github.com/muccg/rdrf/issues/1118 as this issue contains two different issues fixed at different places by different people.

**Comment by mouneyrac** [comment]
the copyright fix has been done. Closing this one as I reported the other issue in another ticket.
