### ISSUE TITLE
Definition - CIC LC PROMS: Follow-up PROMS name and survey start

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1120]
On the patient's PROMS page.

When adding a new survey, the drop-down list for selecting the PROMS type lists "PROMS" and "Baseline PROMS - Lung Cancer". This implies that the Follow-up PROMS survey is the former entry, but this is not clearly labelled.

Further, the text at the start of the Follow-up PROMS survey states "PROMS", rather than (for example) "Follow-up PROMS - Lung Cancer".

**Comment by jithendralal** [comment]
The display name to be changed from 'PROMS' to 'FollowUpProms'
https://rdrf.ccgapps.com.au/ciclung/admin/rdrf/survey/3/change/

**Comment by jithendralal** [comment]
The survey name changed from PROMS to FollowUpProms
Bumped up the registry version from 0.0.10 to 0.0.11

**TO DO** 
Copy the definition to LC Staging PROMS System.
