### ISSUE TITLE
Upgrade build script/plan upgrades

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1131]
Use pur to check any updates to dependencies in our requirements files

eg

dev-requirements.txt
test-requirements.txt

setup.py ( you'll need to  copy the files to avoid in place updating )

Also

**Comment by id2359** [comment]
Use pur to check dependencies

**Comment by jithendralal** [comment]
- create a upgrade_dependencies branch off next_release

- use pur command to check the existing requirements for possible updates
- eg: pur -r test-requirements.txt -o test-r.txt
and compare the existing requirements, with the updates

- create issues for each updateable package eg: #1134
- work on a branch of its own eg: upgrade_1134 off upgrade_dependencies
- do the unittests
- do the behaviour tests
- do manual testing by importing regirty metadata yaml and creating a few objects, logging in and out as users etc
- if all good merge in to upgrade_dependencies 
- do not delete the individual branches until all upgrades are worked on (done or discarded)
