### ISSUE TITLE
Django upgrade to 2.2.11 ( security recommendation from github)

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1133]
Follow best practice as outlined in Django docs to upgrade

**Comment by jithendralal** [comment]
[INFO:2020-02-10 14:27:22,330:apps.py:14:ready] running RDRFConfig.ready ... 
SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E007) The custom handler404 view 'rdrf.urls.handler404' does not take the correct number of arguments (request, exception).

**Comment by jithendralal** [comment]
2ba6729f1a5eb5f4815e695728c5eaacd9b69e99 - 404 handler modified to match the new django version
build on Travis failed:
AssertionError: Database queries to 'clinical' are not allowed in this test. Add 'clinical' to rdrf.testing.unit.tests.ClinicalDataTestCase.databases to ensure proper test isolation and silence this failure.

**Comment by jithendralal** [comment]
https://github.com/muccg/rdrf/commit/50126ab3a33ea76f83f880d3ef599e9ada1b4fd8 - url in stellar.yaml config files modified to test the effect
