### ISSUE TITLE
Security fix pillow

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1167]
1 pillow vulnerability found in rdrf/setup.py on 23 Oct
Remediation
Upgrade pillow to version 6.2.0 or later. For example:

install_requires=[
    'pillow>=6.2.0'
],
or…
extra_requires=[
    'pillow>=6.2.0'
],

**Comment by jithendralal** [comment]
#1156 - Pillow was upgraded to 6.2.1 
851d808
