### ISSUE TITLE
Plasmic Score for APMAT

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1168]

**Comment by id2359** [comment]
See attached "flowchart": Plasmic Score module should implemented as a new section at the end of the form such that:

inputs ( put in one new section called Plasmic Score Module )
platelet count < threshhold ( see diagram)    : yes/no
haemolysis variable : yes/no
No active cancer : yes/no
No history of solid-organ or stem cell transplant: yes/no
MCV <90 fL   (calculated field based on MCV cde input)  : yes/no
INR < 1.5    yes/no
Creatine <2.0 mg/dL  yes/no

output:
Plasmic Score
yes = 1 point 
calculate sum(points) 

0-4   low risk
5      intermediate risk
6-7 high risk

**Comment by id2359** [comment]
This is the key feature they want so do first

**Comment by jithendralal** [comment]
```
---------------------------------------------------------------------------------------------
New CDE                         Type        Name/Label
---------------------------------------------------------------------------------------------
APMATPlateletCountLessThan30    Boolean     Platelet Count < 30x10^6/L
APMATHaemolysisVariable         Boolean     Haemolysis Variable
APMATNoActiveCancer             Boolean     No Active Cancer
APMATNoTransplant               Boolean     No history of solid-organ or stem cell transplant
APMATMCVLessThan90              Boolean     MCV < 90 fL
APMATINRLessThan1Dot5           Boolean     INR < 1dot5
APMATCreatinineLessThan2        Boolean     Creatinine < 2
---------------------------------------------------------------------------------------------
```

**Comment by jithendralal** [comment]
The new section does the Plasmic Score calculation.
The CDEs use the naming/label format specified by Jim.

Ref:
http://www.clinlabnavigator.com/ttp-plasmic-scoring-system.html
https://www.mdcalc.com/plasmic-score-ttp

**Comment by id2359** [comment]
apmat yaml added 
md5sum apmat.yaml 
f80111765e78efaebbb67c0693cd04c5  apmat.yaml

**Comment by jithendralal** [comment]
[ERROR:2020-04-06 12:20:11,012:utils.py:38:func_wrapper] 'APMATNoActiveCancer' | Traceback (most recent call last):
File "/env/lib/python3.7/site-packages/rdrf/helpers/utils.py", line 33, in func_wrapper
return func(*args, **kwargs)
File "/env/lib/python3.7/site-packages/rdrf/management/commands/update_calculated_fields.py", line 110, in handle
new_calculated_cde_value = calculate_cde(patient_model, form_cde_values, calculated_cde_model)
File "/env/lib/python3.7/site-packages/rdrf/management/commands/update_calculated_fields.py", line 161, in calculate_cde
return func(patient_values, form_values)
File "/env/lib/python3.7/site-packages/rdrf/forms/fields/calculated_functions.py", line 823, in APMATPlasmicRisk
score += 1 if yes_selected(context["APMATNoActiveCancer"]) else 0
KeyError: 'APMATNoActiveCancer'

**Comment by jithendralal** [comment]
![image](https://user-images.githubusercontent.com/1198456/78536827-0583d080-7821-11ea-965d-07633e8b4626.png)

**Comment by id2359** [comment]
Let's close this off when the calc is fully working

**Comment by id2359** [comment]
Testing lead to another bug https://github.com/muccg/rdrf/issues/1288

**Comment by jithendralal** [comment]
#1288 was done by editing the definition.
