### ISSUE TITLE
CIC EQ5D changes

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1200]
[Effective_Australia (English) EQ-5D-5L Digital Self complete Tablet v1.2 (ID 64680).xlsx](https://github.com/muccg/rdrf/files/4120573/Effective_Australia.English.EQ-5D-5L.Digital.Self.complete.Tablet.v1.2.ID.64680.xlsx)
[EQ_5D changes.docx](https://github.com/muccg/rdrf/files/4120574/EQ_5D.changes.docx)

**Comment by id2359** [comment]
https://openbase.io/js/rc-slider

**Comment by jithendralal** [comment]
The Health Rate slider changes committed : 6001db0087769ae056d5128f09b0a8572c8f711f

**Comment by id2359** [comment]
Request from Angela: Make the Health Score Label 2 lines per label to fit without horizontal scrolling.

**Comment by gmaloneccg** [comment]
Tested 2020-02-17 ~11am. Text is good for Android (as per Lee's test) and Firefox adaptive design (imitating iPhone X/XS on iOS 12). Overlap still occurs for obsolescent software Microsoft Edge for Windows 10 Phone, but it is unlikely this software will be used.

**Comment by jithendralal** [comment]
Changes requested by EQ5D:

The instructions (Please tap…) are to be showed in regular font, not in italics.

The VAS instructions to be showed with bullets or at least left aligned instead of concatenated. 

Some space to be retained by removing the header ‘YOUR HEALTH TODAY’.
