### ISSUE TITLE
Calculated fields runtime error on breast cancer staging site ( ccg site)

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1211]
AttributeError at /ICHOMBC/forms/223/73/69
module 'rdrf.forms.fields.calculated_functions' has no attribute 'BMI_inputs'

**Comment by jithendralal** [comment]
The Section BASELINECLINICAL is using a CDE coded BMI and not CDEBMI

**Comment by id2359** [comment]
The Breast cancer registry on ccg is an old version - the correct version is https://rdrf.ccgapps.com.au/cicbreast   - I'll mark this ticket as invalid
