### ISSUE TITLE
EQ5D Changes Round 2

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1221]
- [x] Please show the instructions (Please tap…) in regular font, not in italics.

- [x] Levels 4 and 5 of Pain/Discomfort are mixed-up:. It should be as follows:

I have severe pain or discomfort
I have extreme pain or discomfort
( This has been done by Angela on the staging clinical system for Lung )

- [x] Finally, please show the VAS instructions with bullets or at least left aligned instead of concatenated. Possibly you can retain some space by removing the header ‘YOUR HEALTH TODAY’.

 

Finally, please show the VAS instructions with bullets or at least left aligned instead of concatenated. Possibly you can retain some space by removing the header ‘YOUR HEALTH TODAY’.

 
![image01](https://user-images.githubusercontent.com/1163895/74701760-cf739880-5242-11ea-97b8-a13e6cdf9a34.jpg)

**Comment by id2359** [comment]
Updated yamls on proms staging.
md5 hashes:

 127723be3d1fe05f6f91b3544d9ba827  ciclungclinical.yaml

c8ee0a81b69bf55171fad2d63b0cb6d7  ciclungproms.yaml

**Comment by gmaloneccg** [comment]
Tested 2020-02-21 ~11:30am. All three points (in ticket description) appear successful. Tested manually and automated, baseline and followup.
