### ISSUE TITLE
patient address state evades validation and doesn't allow selection after save

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1226]
from Jing:

I’ve been able to replicate the same issue as Theresa. ie. Save the Demographics module with “State” left empty, then the dropdown for “State” never populates despite reselecting different countries.

 

The only way I can work around it is to delete the Patient Address section (mark for deletion, then save), and then “+Add” the Patient Address section and enter into it again.

 

Can this be fixed?

 

Many thanks,

Jing

Ticket includes

- [x] code
- [x] test

**Comment by gmaloneccg** [comment]
In addition: After saving successfully without state entered, if immediately attempting another save (change no data, just click save again after refresh) then a validation error will occur for the state field.

**Comment by id2359** [comment]
NB. The code change has been merged and released after manual testing ( version 6.1.5 )
An automated test is being added by JN and will appear in a later version.
