### ISSUE TITLE
FH/OPHG: Incomplete data prefill on patient demographics page

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1228]
In FH, when changing the structure of family linkage, in particular swapping index patients, the Sex, Location, and Living status fields for relatives are missing data on the index patient's demographics page.

Reprex:
1. Create new patient and successfully save (do not add relative at this stage)
2. Add relative to the new patient via demographics, and create relative patient
3. Navigate to the family linkage page:
3.1. Move relative to the index slot and save
3.2. Move old index back to index slot and save
4. Check relatives listed on index patient's demographics page -- Sex, Location and Living status of the relative should be empty

**Comment by APMCCG** [comment]
Issue is still presenting in RDRF 6.3.19.
Steps to recreate are the same as original ticket.
