### ISSUE TITLE
CIC CRC: Double answers for BCCA questions

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1237]
In the patient's Bi-national Colorectal Cancer Audit page, in the Pathology section. The CDEs `BCCAtumour_site` and `BCCAprimary_tumour` feature the answer "Sigmoid colon" twice.

![dbl-sgmd](https://user-images.githubusercontent.com/50615516/75528662-387ebb80-5a4e-11ea-99ba-70f9f3382e62.png)

**Comment by id2359** [comment]
This is also present at Midland ( from site):
[('Pending', 'Pending'), ('11', 'Rectum - lower third (<8 cm)'), ('10', 'Rectum - mid third (8 -12 cm)'), ('9', 'Rectum - upper third (>12cm)'), ('8', 'Sigmoid colon'), ('7', 'Sigmoid colon'), ('6', 'Descending colon'), ('5', 'Splenic flexure'), ('4', 'Transverse colon'), ('3', 'Ascending colon'), ('2', 'Caecum'), ('1', 'Appendix'), ('Unknown', 'Unknown')]

**Comment by id2359** [comment]
We'll need to do a data migration to fix

**Comment by id2359** [comment]
from angela:
Hi Lee,

Good pick up George.

It should be the following:

Code number 8 = Rectosigmoid colon

 

Also noticed another error/missing variable which is:
Code number 12 = Hepatic flexure
I’ve altered on the system and also changed all the position numbers as Hepatic flexure should come between ascending and transverse colon when viewed on databas

**Comment by jithendralal** [comment]
[
  {
    "code": "1",
    "text": "Appendix"
  },
  {
    "code": "2",
    "text": "Caecum"
  },
  {
    "code": "3",
    "text": "Ascending colon"
  },
  {
    "code": "12",
    "text": "Hepatic flexure"
  },
  {
    "code": "4",
    "text": "Transverse colon"
  },
  {
    "code": "5",
    "text": "Splenic flexure"
  },
  {
    "code": "6",
    "text": "Descending colon"
  },
  {
    "code": "7",
    "text": "Sigmoid colon"
  },
  {
    "code": "8",
    "text": "Rectosigmoid colon"
  },
  {
    "code": "9",
    "text": "Rectum - upper third (>12cm)"
  },
  {
    "code": "10",
    "text": "Rectum - mid third (8 -12 cm)"
  },
  {
    "code": "11",
    "text": "Rectum - lower third (<8 cm)"
  },
  {
    "code": "Pending",
    "text": "Pending"
  },
  {
    "code": "Unknown",
    "text": "Unknown"
  }
]
