### ISSUE TITLE
CIC CRC: Sync for PROMS surveys

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1238]
For the CIC CRC PROMS surveys, the text for the EQ-5D questions may need to be synchronised. The instruction text for the "Your health today" slider is doubled, and the instructions for the other questions do not feature underlined text but capitals.

Slider text:
![ciccrc-survey-slider](https://user-images.githubusercontent.com/50615516/75530192-a925d800-5a4e-11ea-8e3e-afa85b983759.png)

Other EQ-5D questions text:
![ciccrc-survey-eq5dheader](https://user-images.githubusercontent.com/50615516/75530325-b4790380-5a4e-11ea-84ad-2824b436dd0b.png)

**Comment by gmaloneccg** [comment]
Tested 2020-03-04 ~10:45am. Slider text is no longer doubled, and appears to be normal. Other EQ-5D questions remain the same.

**Comment by id2359** [comment]
Fixed definition on staging:
md5sum cicclinical.yaml 
73073ef32f9de27770918de6a3378ed0  cicclinical.yaml
lee@xublr:~/src/rdrd/registries$ md5sum cicproms.yaml 
2aa4cf99659f7952b5e5d4ff0ba5b5b2  cicproms.yaml
lee@xublr:~/src/rdrd/registries$

**Comment by gmaloneccg** [comment]
Tested 2020-03-09 ~4:40pm. Slider text no longer doubled for followup survey. Text for other EQ-5D questions not a bug (I misinterpreted the changes requested).
