### ISSUE TITLE
SMTP Email Backend

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1240]
HSS (govt) requires SMTP server endpoint not mailgun:

- [x] check local smtp server can plugged in as a backend  (EMAIL_BACKEND)
- [x] if other settings in settings.py need to be added, ensure these can be pulled from the system environment.
- [x] test with a local smtp server 
- [x] test with a local docker based smtp server
- [x] test with a hosted smtp server

**Comment by jithendralal** [comment]
'''
EMAIL_BACKEND = env.get('EMAIL_BACKEND', 'anymail.backends.mailgun.EmailBackend')

if EMAIL_BACKEND == 'smtp':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env.get('EMAIL_HOST', 'localhost')
    EMAIL_PORT = env.get('EMAIL_PORT', '25')
    EMAIL_HOST_USER = env.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_HOST_PASSWORD = env.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_SSL = env.get('EMAIL_USE_SSL', False)
    if EMAIL_USE_SSL:
        EMAIL_SSL_KEYFILE = env.get('EMAIL_SSL_KEYFILE', None)
        EMAIL_SSL_CERTFILE = env.get('EMAIL_SSL_CERTFILE', None)
    EMAIL_USE_TLS = env.get('EMAIL_USE_TLS', False)
else:
    ANYMAIL = {
        'MAILGUN_API_KEY': env.get('DJANGO_MAILGUN_API_KEY', ''),
    }
'''

**Comment by jithendralal** [comment]
These changes were committed here: 4e4295afffd247cc9bee69691235fd5cceb21ce6

**Comment by id2359** [comment]
If both code paths are tested ( env var set for smtp, env var not set and defaulting to mailgun) then we can close off

**Comment by jithendralal** [comment]
With env var not set for smtp, it was defaulting to mailgun.
