### ISSUE TITLE
Bulletted instructions for the HEALTH_RATE slider survey question

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1246]
Modification requested by the EQ5D team:

Please remove the bullet in front of instruction:
0 means the worst health you can imagine.

Possible fix: 
Since the bullets are added to the list of instructions based on line breaks,
the instruction can be made a single line (by removing the line break) like this
in the definition:

100 means the best health you can imagine, 0 means the worst health you can imagine.

**Comment by id2359** [comment]
This can't be just a definition change - need to change that mini-parser "transformation" code
