### ISSUE TITLE
Angelman: 500 error on registration

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1247]
When registering a patient on Angelman (staging), using an invalid email causes a Mailgun error. The parent user object is created in the registry regardless, and can be activated by an admin.

**Comment by id2359** [comment]
```
[ERROR:2020-03-06 10:09:57,443:registration_rdrf.py:95:form_valid] Unhandled error in registration for user None: Sending a message to regtest0603_1@email.addr from no-reply@mg.ccgapps.com.au
Mailgun API response 400 (BAD REQUEST):

```

**Comment by id2359** [comment]
If you register with an invalid email mailgun complains with this status code.
