### ISSUE TITLE
EQ5D alignment issue

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1251]
The 0 is not under the bullet

<img width="942" alt="Your health today" src="https://user-images.githubusercontent.com/1163895/76279820-ffa2da00-62ca-11ea-817b-a0ed769edc21.PNG">

**Comment by id2359** [comment]
Firefox doesn't have the problem.
Chrome does.

We need to primarily get it working on Chrome.

**Comment by id2359** [comment]
On my uuntu desktop:
Chrome has issue
Firefox no
On my android ( samsung g7) phone: no issue using ghostery browser doesn;t have the problem
but chrome on android does.

**Comment by gmaloneccg** [comment]
Tested 2020-03-13 1:25pm. Alignment appears to be good on Chrome v80, Ubuntu 19.10. Switching between devtools responsive design (specifically emulating iPhone X, iPad, plus rotations) and back to full-screen realigns text properly.
