### ISSUE TITLE
Confirm LDAPS works in RDRF

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1258]
use Osixia open ldap image to create an Active Directory tree containing two subtrees of users

details to come

- [x] docker pull osixia/openldap  
- [x] read 
- [x] create users in 2 subtrees ( somehow) ( add same role cic to both )
- [x] export this to a file ( ldif?)
- [x] add dummy certs Jith created to test secure ldap

I will then load this into staging and test with latest rdrf

**Comment by jithendralal** [comment]
Tested using the image: osixia/docker-openldap

Done the TLS config as per instructions: https://github.com/osixia/docker-openldap#tls

- **Generated self signed cert in certs folder**

openssl genrsa 2048 > host.key
chmod 400 host.key
openssl req -new -x509 -nodes -sha256 -days 365 -key host.key -out host.cert
chmod 400 host.cert

- Uncommented ldap settings in docker-compose.yaml 

docker_compose_common.yaml
      - EMAIL_BACKEND=smtp
      - EMAIL_PORT=1025
      - LDAP_ENABLED=1
      - AUTH_LDAP_REQUIRE_GROUP=cn=App-MI-CIC-ICHOMCRC,ou=groups,dc=example,dc=com
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=1

docker_compose.yaml
    volumes:
      - ./certs:/container/service/slapd/assets/certs
    environment:
      - LDAP_TLS_CRT_FILENAME=host.crt
      - LDAP_TLS_KEY_FILENAME=host.key

----------------------------------------------------------------------------

**Comment by id2359** [comment]
Different settings are needed for django-auth-ldap

I've modified codebase  but we need to setup the osixia container so we can test on statging with my new version of RDRF

**Comment by APMCCG** [comment]
Docker-compose file template for setting up local OpenLDAP and PHPLDAPadmin containers (can change container names, env variables, host volume, and ports to fit local machine): [docker_compose_template.txt](https://github.com/muccg/rdrf/files/6263099/docker_compose_template.txt)

**Comment by APMCCG** [comment]
https://github.com/osixia/docker-openldap/blob/master/README.md - contains information on importing LDIF files ("Create new LDAP server" -> "Seed LDAP database with LDIF") and on using TLS certificates ("TLS" -> "Use your own certificate").

**Comment by APMCCG** [comment]
Updated example docker-compose: [docker_compose_template.txt](https://github.com/muccg/rdrf/files/6295075/docker_compose_template.txt)
The information in the template can be used to populate fields in Portainer. Make sure in the "Networks" tab in the container details to add the containers to the "rdrf_default" network.
