### ISSUE TITLE
CIC Lung Proms login error

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1270]
AttributeError at /admin/
'dict' object has no attribute 'append'
Request Method:	GET
Request URL:	https://rdrf.ccgapps.com.au/ciclungproms/admin/
Django Version:	2.1.15
Exception Type:	AttributeError
Exception Value:	
'dict' object has no attribute 'append'
Exception Location:	/env/lib/python3.7/site-packages/registry/groups/models.py in menu_links, line 235
Python Executable:	/env/bin/uwsgi
Python Version:	3.7.7
Python Path:	
['.',
 '/app',
 '/usr/local/lib/python37.zip',
 '/usr/local/lib/python3.7',
 '/usr/local/lib/python3.7/lib-dynload',
 '/env/lib/python3.7/site-packages']
Server time:	Thu, 26 Mar 2020 08:53:47 +0800
Error during template rendering
In template /env/lib/python3.7/site-packages/rdrf/templates/rdrf_cdes/base.html, error at line 145

'dict' object has no attribute 'append'
135	                        {% endblock %}
136	
137	                        {% block formlinks %}
138	                        {% endblock %}
139	
140	                        <li class="dropdown dropdown-menu-button">
141	                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
142	                                <span class="glyphicon glyphicon-tasks"></span> {% trans "Menu" %}<span class="caret"></span>
143	                            </a>
144	                            <ul class="dropdown-menu" role="menu">
145	                                {% for quick_link in request.user.menu_links %}
146	                                <li><a href="{{quick_link.url}}">{% trans quick_link.text %}</a></li>
147	                                {% endfor %}
148	
149	                                {% block extra_menu %}
150	                                {% endblock %}
151	                            </ul>
152	                        </li>
153	
154	                        {% if request.user.is_superuser %}
155	                        <li class="dropdown dropdown-menu-button">
Traceback Switch to copy-and-paste view
/env/lib/python3.7/site-packages/django/template/base.py in _resolve_lookup
                    current = current[bit] ...
▶ Local vars
/env/lib/python3.7/site-packages/django/utils/functional.py in inner
        return func(self._wrapped, *args) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/utils/functional.py in inner
        return func(self._wrapped, *args) ...
▶ Local vars
During handling of the above exception ('CustomUser' object is not subscriptable), another exception occurred:
/env/lib/python3.7/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/core/handlers/base.py in _get_response
                response = response.render() ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/response.py in render
            self.content = self.rendered_content ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/response.py in rendered_content
        content = template.render(context, self._request) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/backends/django.py in render
            return self.template.render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in render
                    return self._render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in render_annotated
            return self.render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/loader_tags.py in render
            return compiled_parent._render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in render_annotated
            return self.render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/defaulttags.py in render
                return nodelist.render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in render_annotated
            return self.render(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/defaulttags.py in render
            values = self.sequence.resolve(context, ignore_failures=True) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in resolve
                obj = self.var.resolve(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in resolve
            value = self._resolve_lookup(context) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/template/base.py in _resolve_lookup
                        current = getattr(current, bit) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/utils/functional.py in inner
        return func(self._wrapped, *args) ...
▶ Local vars
/env/lib/python3.7/site-packages/django/utils/functional.py in inner
        return func(self._wrapped, *args) ...
▶ Local vars
/env/lib/python3.7/site-packages/registry/groups/models.py in menu_links
                    links.append(custom_action.menu_link) ...
▼ Local vars
Variable	Value
QuickLinks	
<class 'rdrf.forms.navigation.quick_links.QuickLinks'>
custom_action	
<CustomAction: CustomAction object (2)>
links	
{}
qlinks	
<rdrf.forms.navigation.quick_links.QuickLinks object at 0x7f4d3501d6d0>
registry_model	
<Registry: ICHOM Lung Cancer (ICHOMLC)>
self	
<CustomUser: admin>
Request information
USER
admin

GET
No GET data

POST
```
cause:

https://github.com/muccg/rdrf/commit/e3808008fa88da62e3788ee2b8e370d32f26411f

**Comment by gmaloneccg** [comment]
Passed testing for login and navigation, except for #1299.
