### ISSUE TITLE
FH/OPHG: Family linkage lookup

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1277]
In FH/OPHG, when logged in as admin. On the family linkage page.

Attempting to search for a patient using "Load this index and family" does not seem to perform any action, or at least does not show any indication of an action being performed. Attempting to use "Add looked up patient to family" will add the current patient to the patient's own family, but will not do so if the patient already has relatives attached, and will instead give a warning notification. The contents of the search bar do not appear to have any effect on the behaviour of the buttons.

I may have misinterpreted the usage of the index lookup. I made the assumptions that the "Load this index and family" button will load the family linkage of the index patient typed into the search bar, and that the "Add looked up patient to family" button will add the patient in the search bar to the current index patient's family.

**Comment by id2359** [comment]
Which inputs  did you try?

**Comment by id2359** [comment]
which patient were you looking at?

**Comment by id2359** [comment]
For any ticket what we need is replicable info in the ticket so the devs can isolate the problem

**Comment by gmaloneccg** [comment]
On family linkage for patients 523 (Mary Black) and 642 (Greg Bloggs), and typing the name of the converse (e.g. typing "Mary BLACK" or "BLACK Mary" on Greg Bloggs' linkage page) when using index lookup buttons. Initially tested with patients 705 and 706 (Goldie Aurum and Silvia Agnium).

**Comment by id2359** [comment]
on staging site works for me
