### ISSUE TITLE
CIC CRC: Completion Report medical number and Consent Date

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1282]
Testing #1204.

- The field for patient medical record number refers to the medical number on Demographics, whereas it should refer to the number on Patient Information. The field on Demographics cannot be accessed by clinical staff (hidden).
- The column for consent date is labelled "Consent", identical to the title of the preceding column.

**Comment by gmaloneccg** [comment]
If being used in _R_, missing data should be represented by `NA`.

Reading the .csv could include the empty string in the `na.strings` argument, or could be converted post-read. The `na.strings` method can also accommodate flag values such as 999 or -1, where viable. If some fields can feasibly take such values, post-read conversion may be the better option, as `na.strings` covers all input data.

`na.strings` method;
```r
csv<-read.csv(
    path,
    na.strings=c("","999","-1")
)
```

Post-read method to convert all "999" entries in column `var1` to `NA`;
```r
csv$var1[csv$var1=="999"]<-NA
```
This method can also be used for the whole dataframe post-read;
```r
csv[csv=="999"]<-NA
```

**Comment by id2359** [comment]
Fixed in definition on staging site
