### ISSUE TITLE
APMAT: Followup form errors

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1287]
Testing the APMAT followup form.

Some fields, seemingly those named "Frequency", are of the datatype "Alpha Numeric". It appears to accept only alphanumeric characters, as entering any spaces results in the validation error "Enter a valid value". There is no instruction text for these fields.

Furthermore, a validation error can cause an error within the same section whereby a multiselect list is labelled with "Enter a list of values". Possibly related to #1101. Screenshot attached;

![apmat_listerror](https://user-images.githubusercontent.com/50615516/78535897-7cb86500-781f-11ea-8849-d79cbd0f0a86.png)

**Comment by jithendralal** [comment]
The datatype of CDE 'APMATAspirinFrequency' with label 'Frequency' is currently set as AlphaNumeric.
This can be set as a String, so it will accept strings like '2 times; 500mg'

**Comment by id2359** [comment]
Blocked until we get some kind of formal go ahead
