### ISSUE TITLE
APMAT: Plasmic Score 10^9 not 10^6

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1288]
Testing #1168.

- Platelet count perhaps should be &times;10<sup>9</sup>, rather than &times;10<sup>6</sup> (as per the [reference provided by Jith](https://www.mdcalc.com/plasmic-score-ttp)).
- MCV may be intended as a calculated field itself (as per [Lee's comment](https://github.com/muccg/rdrf/issues/1168#issuecomment-567812770))

**Comment by id2359** [comment]
1b0776af096a9e482973b8a9919dbda1  registries/apmat.yaml

**Comment by jithendralal** [comment]
The unit of platelet count was corrected in the current definition of APMAT.

**Comment by jithendralal** [comment]
It was decided to go with what Jim suggested for MCV.
So not to convert it to a calculated field.

**Comment by id2359** [comment]
Jim suggested not adding further calcs so we'll go with his suggestion
