### ISSUE TITLE
CDE labels can't have period 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1289]
This affects APMAT but it means you can't label things like:

X > 3.5

**Comment by jithendralal** [comment]
The comment given by Lee on 10/2/2016
for the clean method, which checks presence of "." in CDE name and raises a validation error:

# this was causing issues with form progress completion cdes record
# todo update the way form progress completion cdes are recorded to
# only use code not cde.name!

**Comment by jithendralal** [comment]
To test this:
1. add a new CDE with "." in name
2. add a new section to use that CDE
3. use that section in a form and selected that CDE as a completion CDE
5. logged in as curator, edit the form for a patient multiple times to see the progress change correctly
6. in step 6 the new cde can edited to have value and not to have to see how that affects the completion %

**Comment by gmaloneccg** [comment]
Tested 2020-04-09 5:00pm. Cannot save a new CDE with dots in the name. An error appears stating;

> `CDE TESTCDEDOT name error 'test.cde.name.with.dots' has dots - this causes problems please remove`

**Comment by gmaloneccg** [comment]
Tested for CIC Lung and OPHG/FH. Passes for CIC CRC, CIC LC, OPHG/FH and APMAT. Fails for Angelman and MTM.
