### ISSUE TITLE
Security update - Pillow

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1293]
dependabot couldn't create an automatic pull request:
Dependabot cannot create a pull request as one or more other dependencies require a version that is incompatible with this update.

2 Pillow vulnerabilities found in rdrf/setup.py 6 days ago
Remediation
Upgrade Pillow to version 6.2.2 or later. For example:

install_requires=[
    'Pillow>=6.2.2'
],
or…
extra_requires=[
    'Pillow>=6.2.2'
],

**Comment by id2359** [comment]
Given there was an issue doing it automatically , this might not be possible under the current constraints.

**Comment by jithendralal** [comment]
Upgraded Pillow to version 6.2.2

**Comment by id2359** [comment]
Test for this is regression testing George

**Comment by jithendralal** [comment]
TODO: the only reference to Pillow being in setup.py, try removing the requirement entry there and doing a clean build

**Comment by gmaloneccg** [comment]
CIC CRC regression test shows no apparent faults at UI level, therefore the testing appears to have passed.
