### ISSUE TITLE
APMAT: Locked form on loading shows an error popup

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1294]
While testing the issue #1170, on ccgapps, it was noted that 
when loading a locked form a popup comes up that says:
ReferenceError: moment is not defined

logged in either as a curator or a clinical user, opening a locked form of a patient
eg: https://rdrf.ccgapps.com.au/ccg/apmat/forms/312/112/143

By inspecting the code, it was seen that moment library is being used in different locations in existing js.

**Comment by gmaloneccg** [comment]
Appears as follows for patient "NEWTEST Norman", logged in as georgecurator, testing #1170.

![apmat_momentreferror](https://user-images.githubusercontent.com/50615516/78858358-b6ee5600-7a1b-11ea-81a1-c39eb0e5ef31.png)

**Comment by id2359** [comment]
Blocked until we get some kind of formal go ahead
