### ISSUE TITLE
CustomAction scope not being preserved / imported

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1295]
The scope attribute on CustomAction controls when/where the custom action link in the menu is shown.
The importer and exporter code needs to be kept up to date with any model changes else loaded registries lose that config.

This happened so the custom action was not properly displayed when cic registries loaded

**Comment by id2359** [comment]
To test this, login in as an admin in CIC Lung ( say)
Navigate to the admin page/custom actions
write down the scope of the action
got to registries in admin page
export a yaml file
open in editor and search for the word "scope" - you should see the code for the scope U for universal P for patient ( I think) 

Importing I've already tested

**Comment by gmaloneccg** [comment]
Exporting the .yaml as at 15th April 4:30pm shows;
```yaml
..
..
7030  name: Completion Report
7031  scope: P
..
..
```
Therefore this appears to have passed.
