### ISSUE TITLE
Add a celery container 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1297]
Run the same codebase with a different entry point as an extra docker container

(As is done for Automatic)

**Comment by id2359** [comment]
NB. This ticket does not include any real tasks ( like running the reports / custom actions) we'll need to figure that out later. A dummy task invoked from a test page would be good, but see how you go.

**Comment by jithendralal** [comment]
tasks.py
`
from __future__ import absolute_import, unicode_literals
from celery import shared_task


@shared_task()
def add(x, y):
    return x + y
`

**Comment by jithendralal** [comment]
prodbuild done locally for testing.
