### ISSUE TITLE
APMAT: Form lock error

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1300]
Logged in to APMAT as curator. Patient "NEWTEST Norman". Found while testing #1170.

The form lock button does not appear after unlocking a form and successfully saving the form. The form lock button returns once leaving the page and returning, or cancelling operations on the page. The lock button is not present when the "patient saved successfully" green banner is present.

Steps to reproduce:
1. Go to patient page and navigate to a locked followup form.
2. Unlock the form.
3. Successfully save the form &mdash; data do not need to be modified, but can be if desired.
4. With the "patient saved successfully" green banner present, scroll to the bottom of the page to find the "lock form" button. The button should be present, but is not.
5. Select "Cancel", or navigate away then back. Refresh does not display the same behaviour.
6. The green banner should now not be present. Scroll to the bottom of the page. The form lock button is now present.

**Comment by id2359** [comment]
Blocked until we get some kind of formal go ahead
