### ISSUE TITLE
CIC CRC: Minor typo for Type of radiotherapy CDE

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1302]
On the Baseline Treatment page, the CDE "Type of radiotherapy" (code RADIOTXTYPECRC) has the answer "Intraoperative radiation therapy (ORT)". The abbreviation perhaps should be IORT, rather than ORT.

**Comment by gmaloneccg** [comment]
Also for CDE code R_RADIOTXTYPECRC.

**Comment by id2359** [comment]
Is this lung ?

**Comment by id2359** [comment]
Need to ask Angela
