### ISSUE TITLE
Password Reset Email not getting sent 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1308]
Reported by MTM by code is in base RDRF.

**Comment by id2359** [comment]
The MTM account lockout email template has a link to  http://localhost:8000/login_assistance ( effectively)

**Comment by jithendralal** [comment]
The case of user getting blocked was tested on staging: After 3 failed login attempts on ciclung on staging, the message "you will be sent an email with instructions on what to do" was displayed, but no mail was received.

**Comment by jithendralal** [comment]
current logic allows self unlock for non privileged users only:
```
def is_user_privileged(user):
    return not (user.is_patient or user.is_parent or user.is_carrier)


def can_user_self_unlock(user):
    return (
        getattr(settings, 'ACCOUNT_SELF_UNLOCK_ENABLED', False) and not
        is_user_privileged(user) and not user.prevent_self_unlock)
```

**Comment by jithendralal** [comment]
Currently implemented workflow:
[password_workflow.pdf](https://github.com/muccg/rdrf/files/4660520/password_workflow.pdf)
