### ISSUE TITLE
Input form generation for Custom Actions

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1314]
- [x] spec representation
- [x] importer
- [x] exporter
- [x] generate form class 
- [x] intermediate view
- [x] query restriction

**Comment by id2359** [comment]
The initial requirement of filtering by "consent date" was clarified after phone conversation with Angela Ives 8 May 2020:
The main requirement is to know who to send the proms to after the initial visit: the date of first surgical consult is the date field to filter on.

**Comment by id2359** [comment]
consent date is a red herring - better to filter on date of first surgical consult - and allow the report to be   extensible to other "filter values"

**Comment by jithendralal** [comment]
**Issue:** Invalid format of date input causes error
**Suggestion:** Based on field_type in filter_spec, the date inputs can be assigned date picker

**Comment by id2359** [comment]
input validation needs to be added - I should have added that before updating

**Comment by id2359** [comment]
to test check the input filtering works:

we specify that like this in the config:

The start/end date apply to BaselineClinicalForm/BASELINECLINICALCRC/First_Consult_Date

(inclusive)
