### ISSUE TITLE
Create abnormality condition  aloe test

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1316]
- [x] Enter abnormal value and assert abnormal icon shown
- [x] Enter normal value and assert it's not shown

**Comment by gmaloneccg** [comment]
Working steps and feature file;
- Steps;
  - Check if CDE is or is not marked as abnormal
  - Click a radioselect value
  - Check a radioselect value is selected
- Feature to check abnormality condition;
  - 2 CDEs on Baseline PROMS page; EORTCQLQC30_Q02, EORTCQLQC30_Q29
- Tested and working locally, continuing to test/modify

**Comment by gmaloneccg** [comment]
Modified step for CDE mark;
- Step now identifies if CDE is abnormal, important, or required
- Code format modified a bit
- Feature file renamed, scenario added
