### ISSUE TITLE
CIC Lung PROMS: Alignment on Windows 10 phone

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1319]
When completing the Followup PROMS on Windows 10 phone, built-in Edge browser.

The text for the "YOUR HEALTH TODAY" slider overlaps somewhat. The text for the highest and lowest scores overlaps with other text.

Screenshots;

![20200515_promsslider_1_reduced](https://user-images.githubusercontent.com/50615516/82016672-12da7900-9671-11ea-88df-b563784dfc51.png)
![20200515_promsslider_2_reduced](https://user-images.githubusercontent.com/50615516/82016674-14a43c80-9671-11ea-93d6-1689d63796b5.png)

**Comment by id2359** [comment]
We'll triage this later. It's low priority, until we get all the main workflows tested on supported platforms: Android, IOS using Chrome
