### ISSUE TITLE
CIC Lung: Minor typos on Initial Review

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1320]
On the patient's Initial Review page, in section "Lung cancer risk factors - Smoking".

The instruction text for CDEs `SMOKINGSTARTYEAR` ("Age when started smoking") and `SMOKINGSTOPYEAR` ("Age when stopped smoking") has a minor typo.

The text reads;

> Enter 999  of unknown

This perhaps should read;

> Enter 999 if unknown

Screenshot;

![20200515_smokingcde_texttypo](https://user-images.githubusercontent.com/50615516/82018189-45d23c00-9674-11ea-9143-553b77ba69dd.png)

**Comment by id2359** [comment]
Fixed in definitions.
Exported and added to rdrd.
