### ISSUE TITLE
CIC CRC PROMS: Precondition for survey question EORTCQLQLC30_Q23

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1324]
In the CIC Clinical PROMS baseline survey. Received via QRcode, Windows 10 phone, default Edge browser.

The question "Did you feel irritable?" was not asked. In the previous test (version just before definition update), the question was asked but the instruction text was missing.

**Comment by gmaloneccg** [comment]
There is a precondition in the baseline survey such that the previous question ("Did you worry?") must be answered at the highest or worst level for this question to be asked.

This precondition is not present for the follow-up survey.

**Comment by id2359** [comment]
Angela advises precondition shouldn't be there

**Comment by id2359** [comment]
I have removed the procondition of registry version 1.21
( in rdrd next_release branch https://github.com/muccg/rdrd/commit/ae2cd5d20a9c6702684f2142cd49aa388f82ca6c )
