### ISSUE TITLE
fix workflow for curators ( reset password ) when receiving login assistance email mtm

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1327]

**Comment by jithendralal** [comment]
Related issue: https://github.com/muccg/rdrf/issues/1308

**Comment by jithendralal** [comment]
To test on MTM:

**Patient:**
Register as a patient. 
Get locked out by 3 wrong password login attempts.
Use the link in the locked notification email.
Submit email.
Use the link in the verification email.
Submit Patient details.
Reset password and login.

**Curator:**
Get locked out by 3 wrong password login attempts.
Use the link in the locked notification email.
Submit email.
Use the link in the reset password email.
Reset password and login.

**Clinical:**
Get locked out by 3 wrong password login attempts.
Use the link in the locked notification email.
Submit email.
Receive instructions to contact admin.
