### ISSUE TITLE
Infrastructure for Async  Custom Actions ( Polling View etc.)

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1330]
Current "completion report" for CIC CRC takes too long.

We have added the celery task queue but not integrated into custom actions yet.

This requires:
 
- [x] The custom action to be marked as runnable async
- [x]  The result to be updated as a json object in the result backend 
- [x] Temporary files to be created holding the report ( written to /data/static/tasks )
- [x]  A polling view to check the task status and allow download of the finished report/action
- [x] clean up action of the "temporary files"

**Comment by gmaloneccg** [comment]
Appears to work correctly from the clinical staff user's view, so marking as a pass.

- Requesting the report for a given date range shows a page stating "Waiting for Completion Report", showing the job ID, then provides a download link when the report is complete.
- Refreshing the page runs a new job with a new ID, but with seemingly identical date range parameters.
- Running the report via the "patient zero" menu option (see #1335) does not throw an error.
