### ISSUE TITLE
Integer cdes in survey seem to require min and max value

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1336]
The original CIC Breast cancer survey has a question for height where the cde originally had no max value - Trying to open the survey resulted in a traceback when creating the client_rep of the survey.

( For the spec in the case the cde was of datatype integer)
was trying to do int(None)

**Comment by id2359** [comment]
So rather than enforce max and min on integer cdes ( so as not to break the surveys), the react frontend should handle the case where max or min are not set.

**Comment by jithendralal** [comment]
It was decided to add a validation instead of setting default values.
