### ISSUE TITLE
CIC Breast: Baseline PROMS page validation error

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1338]
Logged in as clinical staff (?) user.

Attempting to "manually" enter data for the patient's Baseline PROMS survey returns the validation error "Enter a list of values" for the CDE "What was the highest level of schooling you completed" (which incidentally may be lacking a question mark). This stops all data on the page from being saved.

Possibly related to #1101, #1287.

![cicbc_educationlevel](https://user-images.githubusercontent.com/50615516/83708371-acab9b00-a60b-11ea-9a5a-74e221ff6cf4.png)

**Comment by id2359** [comment]
The highest level of education cde was marked as allow multiple which won't work as a radioselect.

In this case I have made it non-multiple as it doesn't make sense
