### ISSUE TITLE
CIC Breast: PROMS errors

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1339]
Attempting to access the PROMS surveys for CIC BC.

- #1337 has already been identified.
- The title of the survey is "None", and no logo is present. Possibly related to the previous bug.
- No email has been received when attempting the 6-month Followup survey via email.

**Comment by id2359** [comment]
I think best to create separate tickets _ I'll split this one.

**Comment by id2359** [comment]
closing after creating sep tickets
