### ISSUE TITLE
Confirm numeric survey questions widgets with Angela

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1367]
- [x] Jith to determine if dev is required for those cdes which are to use the slider control.
- [x] Jith to confirm integer or float cdes that are not using the slider behave properly
- [x] Jith to summarise results and send to Lee
- [x] Lee to confirm survey questions/widgets  with Angela

**Comment by jithendralal** [comment]
1. An integer CDE can be made to rendered as a slider/input box -- this can be controlled by the presence/absence of widget_config ({}) in survey question
2. A float CDE has an issue on staging in surveys -- the TS expects 'tag' key in the 'spec' dictionary of that -- this breaks the survey
3. The survey questions do not have validations -- though the validations work on admin forms
4. The date inputs can be entered in any format -- there is no validation or no format suggestion/help text even
5. An input box on survey does not respect the datatype of the CDE
6. The survey title is not valiadated and hence can be left blank -- this appears as None on proms survey
7. The survey design, on saving should be cleaned by removing any newlines from the instruction field -- the existing '_clean_instructions' is being called in 'client_rep' for CDE instructions not for survey question's intructions

[survey_report.txt](https://github.com/muccg/rdrf/files/4763329/survey_report.txt)
