### ISSUE TITLE
Add validation logic for Integer survey questions

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1371]
The integer type survey questions do not have validations -- the validations work on admin forms only

**Comment by jithendralal** [comment]
https://stackoverflow.com/questions/51770246/how-to-validate-numeric-inputs-in-reactjs

**Comment by id2359** [comment]
only datatype

**Comment by jithendralal** [comment]
**For testing:**

- SurveyQuestion's CDE to have integer datatype
- the Survey Question on the survey should accept only numbers

**Comment by jithendralal** [comment]
Currently you cannot start typing with a symbol '-', so validate only when Next is clicked

**Comment by gmaloneccg** [comment]
Testing failed as the `HEIGHTCLIN` CDE in the Baseline PROMS survey can accept decimal and exponential (&times;10<sup>n</sup>) notation. The info entered is pulled, but shows a validation error when opening the Baseline PROMS data page.

"Very wrong" data, such as using multiple decimals in a row (e.g. "125....2..e....e...e....eeeee.44.") is erased when clicking Next in the survey. Accepted data will persist when clicking Next -- the data entered in the field will be present in the next field when clicking Next. Not interacting with the field leaves it blank, but entering more data or backspacing any "persisted" data in the new field will update as entered data.

**Comment by jithendralal** [comment]
After the changes in #1372 are merged, this validation to be added for integer question
```
    public handleIntegerChange = (event) => {
        if ((/^-?\d*$/.test(event.target.value)) && !(/^-$/.test(event.target.value))) {
            event.target.classList.remove('is-invalid');
            const code = this.props.questions[this.props.stage].cde;
            this.props.enterData(code, event.target.value, true);
        } else {
            event.target.classList.add('is-invalid');
            this.props.enterData("", "", false);
        }
    }
```

**Comment by jithendralal** [comment]
**With the addition of the integer validation, this strange behaviour was noted in the HEIGHTCLIN question:**

Once the user's input is invalid, the buttons remain disabled, even after clearing the input box.
(A blank input box remains invalid.)

To make the buttons enable again, the user has to type some digit.
OR
Even to skip the question, the user has to type some digit and delete it.

**Comment by jithendralal** [comment]
**With the addition of the integer validation, this strange behaviour was noted in the HEIGHTCLIN question:**

Step 1. Enter 'a' (shows invalid)
Step 2. Clear 'a' (shows valid)
Step 3. Try to enter 'a' (this is not allowed)

Step 1. Enter '-' (shows invalid)
Step 2. Enter '2' (shows valid)
Step 3. Now try to clear '2' (not allowed) (shows invalid)
Step 4. Clear '-' (shows valid)
Step 5. Clear '2' (shows valid)
Step 6. Try to enter '-' (not allowed) (shows invalid)

Once the user's input is invalid, the buttons remain disabled, even after clearing the input box.
(A blank input box remains invalid.)

To make the buttons enable again, the user has to type some digit.
OR
Even to skip the question, the user has to type some digit and delete it.

**Comment by gmaloneccg** [comment]
In Google Chrome, on an Android One phone;
- the questions can be skipped without entering any data.
- the field will accept an integer that exceeds the maximum value.
- `WEIGHTCLIN` does not accept decimals, as it will show a warning for any non-numeric character, though will show the characters in the field.
- non-numeric characters do not appear at all in `HEIGHTCLIN`, unless they are the first characters entered.
- a warning is shown if a non-numeric character is attempted in `HEIGHTCLIN`, which must be cleared by adding or removing a character.
- all non-numeric characters must be removed from `WEIGHTCLIN` before the validation is cleared and the user can progress.

**Comment by gmaloneccg** [comment]
Failed as the integer behaviour (field `HEIGHTCLIN`) is odd;

- If the first character entered into the field is an invalid character, any characters can then be entered into the field.
  - The field only becomes valid when all characters are removed.
    - The first character is invalid, hence all characters must be removed for the field to then become valid.
  - Attempting to enter any invalid character after the field returns to validity will result in the field becoming invalid.
    - If the field becomes valid once empty, attempting any invalid character makes the field invalid but does not show any characters entered.
    - To then make the field valid, a valid character must be entered.
    - This means that, if an invalid character is accidentally entered but the field should remain empty, the user must remove all characters, enter a number (field is now valid), then remove the number before the user may continue the survey.
  - The negative symbol is an invalid character, but negative numbers are accepted if and only if the first character entered is a negative, then followed by only numbers.
    - Backspacing a negative integer will cause the behaviour as described [in the comment above.](https://github.com/muccg/rdrf/issues/1371#issuecomment-654072445)
    - The field will no longer accept a negative symbol if the symbol is removed after the field becomes valid while first being invalid.
    - Entering a valid integer will allow the user to enter a negative symbol as the first character when editing field contents.
- This behaviour does not manifest for float (next field; `WEIGHTCLIN`).

**Comment by jithendralal** [comment]
These issues are fixed by the commit https://github.com/muccg/rdrf/commit/8ac920e5f5aec388043f08b9b1f471fab984a69b
