### ISSUE TITLE
Add validation logic for float survey questions

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1372]
The float input boxes accept invalid characters like alphabets

**Comment by jithendralal** [comment]
Components from availity-reactstrap can be used for the float fields :
https://availity.github.io/availity-reactstrap-validation/

**Comment by id2359** [comment]
Related to https://github.com/muccg/rdrf/issues/1414

**Comment by jithendralal** [comment]
The changed code is causing a "-" to be accepted as valid and ended up in the survey's respnse:

![image](https://user-images.githubusercontent.com/1198456/86429335-d1d21d00-bd21-11ea-87ab-dcc1f985d2d5.png)

![image](https://user-images.githubusercontent.com/1198456/86429372-eb736480-bd21-11ea-9deb-76747188a18d.png)

**Comment by jithendralal** [comment]
The validation of the float field 
- disables the Next button, if invalid data is entered
- enables Next for blank field
