### ISSUE TITLE
IntegerWidget / Datatypes needs to be changed in react code

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1380]
IntegerWidget is specifying the sliderparameters and is not used by integer fields that do use the slider,

IntegerWidget  becomes SliderWidget   ( instead widget_name use tag = "slider"

Better to call it SliderWidget and add a NoWidget case :

type Widget = SliderWidget | NoWidget

Would be good to have some subfield we can "spread" into the Input component:

e.g.

<Input {...spec.params}

Integer fields may have max and min ( they may not)
type is number for integer
type is date for dates
type text for float with pattern
Float has pattern
Not all fields use the Sliderwidget

**Comment by jithendralal** [comment]
![image](https://user-images.githubusercontent.com/1198456/85381101-3a760880-b570-11ea-8433-1a61f691b14d.png)

**Comment by gmaloneccg** [comment]
Failed due to failing #1371.
