### ISSUE TITLE
Skipped the radio select question at the end of the BaselinePROMS survey 

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1391]
![image](https://user-images.githubusercontent.com/1198456/85668065-daf33680-b6f0-11ea-90dd-1dab9c8fe30c.png)

The range type question  (widget RadioSelect) appearing at the end of the survey, if skipped is saved as Null.
This does not happen with other RadioSelect questions.
(Note: the absence of consent in the BreastCancer BaselinePROMS causes the question to be the last one)

**TODO:** The site system has the consent. This needs to be added to the PROMS system.

**Comment by id2359** [comment]
definition issue - consent should be there as last question : probably not on staging proms site - need to sync

**Comment by id2359** [comment]
Invalid as we need consent as last question
