### ISSUE TITLE
CIC Breast: PROMS: Your Health Today

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1397]
The Your Health Today slider does not appear as a slider, but as a "number" field. Arbitrarily large values can be entered in the survey. Pulled data on the Baseline PROMS page show validation errors.

Pulled data, Your Health Today;

![cicbc_yht_pulled](https://user-images.githubusercontent.com/50615516/85832366-77fcb080-b77f-11ea-80d5-c9734edfc8af.png)

**Comment by jithendralal** [comment]
Possible issue: The exporter and importer does not include the new field "widget_config" of SurveyQuestion model.

**Comment by jithendralal** [comment]
**For testing:**
YOUR HEALTH TODAY should be rendered as a slider and not as an input box.
