### ISSUE TITLE
CIC Breast: "Enter a list of values" validation error

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1398]
On the patient's Pathology page, logged in as clinical staff. When a validation error occurs for a different CDE on the page, the CDE "Indicate histological type of the tumour" shows a validation error stating "Enter a list of values". This validation error does not occur if the other fields are valid.

![cicbc_clindat_dualerror](https://user-images.githubusercontent.com/50615516/85833405-30772400-b781-11ea-87c0-c297420a8669.png)

**Comment by id2359** [comment]
- [ ] subclass multiplechoicefield
- [ ] alter clean method
- [ ] add feature or scenario aloe test
- [ ]  add step to detect number of field level validation messages
