### ISSUE TITLE
CIC Breast: Followup PROMS: Re-operation date errors

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1399]
In the Followup PROMS 2-year survey.

The date of re-operation CDE;

- can accept 6 digits for year
- pulls as year-month-day, rather than day-month-year

![cicbc_followup2y_date](https://user-images.githubusercontent.com/50615516/85840381-eb0c2400-b78b-11ea-991b-64a41da48071.png)

**Comment by jithendralal** [comment]
18-6-2020 is pulled correctly as 18-6-2020
18-6-222222 is pulled wrongly
