### ISSUE TITLE
CIC Breast: Followup PROMS: First question not asked in all surveys

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1402]
In all of the CIC Breast Followup PROMS surveys, the first question, `BREASTQ_SURG` "What was the most extensive surgery you had for breast cancer", is not asked.

**Comment by id2359** [comment]
Asked Angela 02/07/2020 3:48pm

**Comment by id2359** [comment]
On years 1 and 2 ( follow up) the question is asked ( position 71 )
The questions depending on this question are subsequent to it in the surveys.

The other surveys don't ask it ( and there are no questions depending on it )
