### ISSUE TITLE
Definition to be changed - in CDE EQ_Health_Rate on CIC BC -Staging

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1404]
Definition to be changed in CDE EQ_Health_Rate on CIC BC Staging:
https://rdrf.ccgapps.com.au/cicbreast/admin/rdrf/commondataelement/EQ_Health_Rate/change/

The instruction text of the CDE lacks punctuation necessary for proper formatting in the slider:
We would like to know how good or bad your health is TODAY. This scale is numbered from 0 to 100. 100 means the best health you can imagine 0 means the worst health you can imagine Please tap on the scale to indicate how your health is TODAY

This has to be corrected as:
We would like to know how good or bad your health is TODAY. This scale is numbered from 0 to 100. 100 means the best health you can imagine. 0 means the worst health you can imagine. Please tap on the scale to indicate how your health is TODAY.

**Comment by gmaloneccg** [comment]
The slider currently appears as so;

![cicbc_followup_healthslider_partial](https://user-images.githubusercontent.com/50615516/85994109-d7102e80-b9e6-11ea-9e82-8f9135c66559.png)

**Comment by jithendralal** [comment]
The punctuation corrected on CIC BC Staging site system.
Bumped up registry version from 1.0.6 to 1.0.7

**TO DO**
Copy the definition to CIC BC Staging PROMS system.
