### ISSUE TITLE
Create same consent sections in Breast cancer as for CRC 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1407]

**Comment by id2359** [comment]
get rid of existing consent section/questions ( adult/child)

**Comment by jithendralal** [comment]
The consent section for BC Staging was made same as for CRC Staging.

The registry version was bumped from 1.0.6 to 1.0.7 in #1404 along with this ticket.

**Comment by gmaloneccg** [comment]
Consent pulled correctly, but opened #1409 as instruction text is missing.
