### ISSUE TITLE
CIC Breast: PROMS: Consent instruction text not present

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1409]
In the CIC BC Baseline PROMS survey. The instruction text for the Consent (final) question does not appear.

BC;

![cicbc_baselineproms_consent_trim](https://user-images.githubusercontent.com/50615516/86200835-515ac300-bb4d-11ea-943f-54bbeb2a4f49.png)

CRC;

![ciccrc_baselineproms_consent_trim](https://user-images.githubusercontent.com/50615516/86200844-561f7700-bb4d-11ea-85e5-abd22d488379.png)

**Comment by jithendralal** [comment]
The definition updated: Consent Instructions copied from CRC to BC.

The bumped up version on BC is 1.0.9 now.

**TODO : sync definition on Proms system**
