### ISSUE TITLE
CIC Breast: Odd character in CDE TARGETTX

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1411]
On the patient's Treatment page, for the cde `TARGETTX`. The option for "Her-2 targeting therapy" contains an odd character. The dash does not appear to be a regular Unicode or ASCII character.

Exact string as appears in the HTML;

```

 Her‐2 targeting therapy
```

**Comment by id2359** [comment]
dupe of https://github.com/muccg/rdrf/issues/1412
