### ISSUE TITLE
unicode characers in codes

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1412]
for cic breast on staging 
CDEPermittedValues with pk  ( .value) fields:

( on cic breast site system staging):

pk   permissible value
18  [Disease of the nervous system (For example, Parkinson’s disease or multiple sclerosis)]
90  [Post-­menopausal (natural/surgical)]
91  [Pre-­menopausal]
156 [Her‐2 targeting therapy]

Could just use the ascii characters

**Comment by jithendralal** [comment]
The invalid characters removed.
Bumped up the version from 1.0.7 to 1.0.8

**TO DO**
The definition to be coped to PROMS system on CIC BC Staging

**Comment by id2359** [comment]
labels edited on site system.
export yaml from site system

**Comment by jithendralal** [comment]
https://rdrf.ccgapps.com.au/cicbreast/admin/rdrf/cdepermittedvaluegroup/MENOPAUSE/change/
'-' in value 0
Pre-­menopausal

**Comment by gmaloneccg** [comment]
Manifests in a Python shell (in Emacs) as such, where value is the text copied from the PV value, and description is the text copied from the PV description;

![cicbc_invalidchar_inpy](https://user-images.githubusercontent.com/50615516/86699881-20bcd280-c000-11ea-9581-26315d93bbc7.png)

Find (Ctrl + F) in Chrome will find both strings, but Python returns `False` for `value == description`.

**Comment by jithendralal** [comment]
https://rdrf.ccgapps.com.au/cicbreast/admin/rdrf/cdepermittedvaluegroup/MENOPAUSE/change/
replaced the unicode character with a '-'

Bumped up registry version from 1.0.8 to 1.0.9

**Comment by gmaloneccg** [comment]
The HTML for this label appears as such (2020-07-08, 10:50am, v1.0.9);

![cicbc_premeno_html](https://user-images.githubusercontent.com/50615516/86869151-95a61000-c0c5-11ea-814a-4604fd318cd1.png)

There is a second character, `&shy;`, after the first dash.

**Comment by gmaloneccg** [comment]
The priority for this is likely quite low. This is only a problem if there is an Aloe test that is searching for this label, which there currently is not. Furthermore, this text only appears on the PROMS, which cannot be tested by Aloe tests, and the PROMS clinical forms should not necessarily be tested by Aloe tests.

**Comment by id2359** [comment]
close after  synching to proms site one more time.
