### ISSUE TITLE
CIC Breast: PROMS: HEIGHTCLIN validation behaviour

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1413]
In the CIC BC Baseline PROMS survey, on Android One, Firefox browser.

Validation for the field `HEIGHTCLIN` does not appear to the user unless returning to the question after continuing.

The question for CDE `HEIGHTCLIN` provides a numeric keypad, which accepts decimal points. Validation for this field does not accept decimal points, but validation only appears if returning to the question after continuing, whereupon the input box is outlined in red and helper text appears suggesting nearby appropriate values.

**Comment by gmaloneccg** [comment]
After pulling the PROMS data, the data received include a decimal point, and show a validation error for this field. This means that erroneous data can be entered, with or without a visible validation warning, and saved.

**Comment by id2359** [comment]
fixed by https://github.com/muccg/rdrf/issues/1371
