### ISSUE TITLE
CIC Breast: PROMS: WEIGHTCLIN visible behaviour

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1414]
In the CIC BC Baseline PROMS survey, Android One, Firefox browser.

The field `WEIGHTCLIN` does not appear to accept any entered data, as the data do not contribute to progression in the survey and are wiped if the user returns to the question after continuing. However, the data entered in this field appears to be pulled correctly.

The input for this field is also a regular virtual keyboard, rather than a numeric keypad.

**Comment by jithendralal** [comment]
Notes:
- the weight question is rendered as a text input
- the validation is done in onchange event handler

**Comment by id2359** [comment]
Sounds like re-initialisation on going back is clobbering the value.
if the field has already been filled in once, going back should re-display the value that was already entered.

Maybe the "default value" is overriding - so we need to check the existing data first and ensure we don't ignore it.
