### ISSUE TITLE
Management command to set up proms site

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1422]
django-admin setup_proms --yaml-file <yaml_file>

should:
make it transactional ( roll back on error)

a)  clear existing models for:
[CommonDataElement, CDEPermittedValueGroup, CDEPermittedValue, Survey, SurveyQuestion, Precondition, RegistryForm, Section]
e.g. CommonDataElement.objects.alll().delete()

b) ensure registry metadata is correct  ( preserve metadata by default 
c) add (non-default ) option to override metadata ( with metadata in yaml )

**Comment by jithendralal** [comment]
The importer preserves metadata by default for existing registry.
- the management command has option -o Y to override this

**Comment by id2359** [comment]
Rolled back when tried on staging: Some logging of whatever exception was thrown would allow us to debug further ( rethrow the exception after logging.)

**Comment by jithendralal** [comment]
TO DO : add more logging

**Comment by id2359** [comment]
Test plan ( on Breast Cancer initially)

- [ ] choose some question in the Breast site system that are in the survey; make a note of them and them check closely the survey questions corresponding to them are identical ( options ) 
- [ ] do regression test on surveys
