### ISSUE TITLE
CIC BC: PROMS: Text box initialised by prior text box entry

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1425]
In the CIC BC Baseline PROMS survey. Entering correct data for `HEIGHTCLIN` then going to the next question, `WEIGHTCLIN`, shows `WEIGHTCLIN` initialised with the value entered into `HEIGHTCLIN`.

- Survey progress does not increase if the data in `WEIGHTCLIN` remains unmodified.
- Continuing through the survey without modifying `WEIGHTCLIN` pulls it as empty, regardless of what appears in the field.
- Progress increases if the data in `WEIGHTCLIN` is modified in any way, such as by entering more data or by backspacing.
  - Continuing and submitting shows data pulled as was present when the question was left, but only if modifying the initialised data.

**Comment by jithendralal** [comment]
This fix addresses the issues reported by George in the ticket #1371
