### ISSUE TITLE
CIC BC: Baseline PROMS: Display error for multiple-type CDE

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1426]
In the CIC BC Baseline PROMS survey, there is a question with text "Have you been told by a doctor that you have any of the following?", which is of type multiple. On mobile (Google Chrome, Android One), selecting any number of entries does not change the display from "0 selected". Selected entries appear to be pulled correctly.

**Comment by gmaloneccg** [comment]
Post commit 8ac920e, the data entered into the field persists. That is, navigating to the previous question then forwards (without modifying the entries in the field) does not clear the answers, though the CDE still says "0 selected". The answers appear to be pulled correctly.

On desktop, this manifests somewhat differently. The list of options for the field shows none of the options highlighted upon returning to the field. Ignoring this and continuing to the end of the survey appears to pull the answers correctly.

**Comment by gmaloneccg** [comment]
In the Baseline PROMS survey; Google Chrome, Android One. Selecting any number of options in the list (>0) does not update the number shown, unless moving off the question (backwards or forwards) and then returning,  whereupon it will display correctly. However, if all entries are removed from the list (so that there are none selected), the display will show "0 selected" prior to moving away and then back.

**Comment by jithendralal** [comment]
**TODO**
The "select multiple" is rendered on Chrome for Android differently.
It is rendered as a simple drop-down. 
If a single option is selected, it will be shown in the text box.
If multiple options are selected, the text box shows 'n selected'.

Enable USB Debugging on mobile and connect via USB
to use the DevTools on desktop to debug Chrome on mobile.

**Comment by jithendralal** [comment]
The multiselect was being rendered as a <Select multiple.
This has been changed to a set of Checkboxes.
