### ISSUE TITLE
Add react test framework

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1430]
Try https://www.pluralsight.com/guides/how-to-test-react-components-in-typescript

**Comment by id2359** [comment]
There's also this https://create-react-app.dev/docs/running-tests/

Try to fit within create react app's constraints.

**Comment by jithendralal** [comment]
current implementation of react component:
- the **templates/proms/base.html** has **window.proms_config** which is getting populated by the django template tags
- initialState object is set by looking at the **window.proms_config** within proms_page/reducers/index.ts

**Comment by jithendralal** [comment]
As noted above, this requires major restructuring of the current react components.
