### ISSUE TITLE
CIC BC: "Enter a list of values" error on Treatment page

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1436]
In CIC BC, on the patient's Main/Treatment clinical form. The CDE with label "Have you had one of the following re-operations since your surgery for breast cancer?" is a radio CDE, but shows "Enter a list of values" when attempting to save.

This CDE is asked as a question in the followup PROMS surveys, in which it is multiple.

**Comment by id2359** [comment]
Fixed by a definition change ( https://github.com/muccg/rdrf/issues/1448 )
