### ISSUE TITLE
CIC CRC BCCA Export

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1441]
A csv report for ingestion by the BCCA cancer audit registry

- [x] report definition file
- [x] modification to custom action

**Comment by jithendralal** [comment]
Data dictionary received from Angela:
[BCCADatasetDictionary21062018.xlsx](https://github.com/muccg/rdrf/files/4936564/BCCADatasetDictionary21062018.xlsx)

Differences between Data Dictionary and CDE:
[differences_csv.txt](https://github.com/muccg/rdrf/files/4936565/differences_csv.txt)

The report spec for BCCA Report:
[updated_mapping_bcca_json.txt](https://github.com/muccg/rdrf/files/4936566/updated_mapping_bcca_json.txt)

**Comment by jithendralal** [comment]
Data dictionary received from Angela:
BCCADatasetDictionary21062018.xlsx
Differences between Data Dictionary and CDE:
differences_csv.txt

The report spec for BCCA Report: (to be used in Data field of Custom Action for BCCA Report)
updated_mapping_bcca_json.txt
Runtime spec:
{ "async": true }

**Comment by jithendralal** [comment]
The date format expected by the target system is dd/mm/yyyy, whereas the current report uses dd-mm-yyyy

**Comment by jithendralal** [comment]
[bcca_report_spec.txt](https://github.com/muccg/rdrf/files/4970499/bcca_report_spec.txt)

**Comment by id2359** [comment]
Emailed Angela about using validation of some fields (  at the cde level):

Backend code            Formatting permitted
nhi_number		AAANNNN
medicare_number		NNNN/NNNNN/N/N
dva_number		AAXXNNNN[A]
patient_postcode	XXXX

**Comment by id2359** [comment]
Reopened as the change to the format function in utils affected the rest of RDRF.

Need to add a new bcca specific format function in the module.

**Comment by jithendralal** [comment]
Merged on 28 Jul

**Comment by gmaloneccg** [comment]
There are empty rows in the CSV, which may occur where the patient has not filled out any data in the BCCA form.

**Comment by gmaloneccg** [comment]
Opened #1491.
