### ISSUE TITLE
Identified report 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1442]

**Comment by id2359** [comment]
for all registries

**Comment by jithendralal** [comment]
Data for Identified Report - CIC BC
[identified_report.json.txt](https://github.com/muccg/rdrf/files/4958006/identified_report.json.txt)

runtime spec
`{"async": true}`

**Comment by gmaloneccg** [comment]
- Name appears in the Menu as "IdentifiedReport" (no space).
- Result saves as "Completion Report.csv".
- Not all clinical form data are present in the report.
  - Columns present are identical to the Completion Report.
- Attempting to download a second time provides the file "error.txt", with the contents "This file has already been downloaded.".

**Comment by gmaloneccg** [comment]
Differences between identified report JSON and the CSV returned on staging;
- There are 487 columns listed in the identified report JSON, as found in the admin page. There are 32 columns in the CSV.
- 507 columns differ between the JSON and the CSV, suggesting that there are 12 labels in the intersection;
  - 6 in the JSON are present in the returned CSV, and 6 in the CSV are present in the JSON. These are identical, as they were counted twice;

    > `['DOB', 'Family Name', 'Given Names', 'Is there evidence of local, regional or distant recurrence', 'Patient ID', 'Sex']`

    All other CDEs differ.

**Comment by gmaloneccg** [comment]
In all CIC registries, data for the followup survey (or, in the case of CIC BC, followup for years 3-10) are blank in all identified reports -- the columns are present, but no data are present.

**Comment by gmaloneccg** [comment]
The column format/order for the CIC BC identified report (with all fields) is;
Demographics --> Followup PROMS Year 1 --> Followup PROMS Year 2 --> Followup PROMS Years 3-10 --> Followup PROMS 6-month --> Clinical forms --> Baseline PROMS

**Comment by gmaloneccg** [comment]
Opened #1492.
