### ISSUE TITLE
CIC BC: Followup PROMS: Unable to click "Unknown" for multiple CDEs

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1445]
In the CIC BC Followup PROMS surveys, tested for 6-month and 1-year surveys, on Chrome for desktop and mobile.

For the questions "Have you had one of the following re-operations since your surgery for breast cancer?" and "In the past year have you received systemic (ie drug) treatment for breast cancer?", the final option in the list is "Unknown", with the value 999. This option cannot be clicked, as it instantly unchecks itself after clicking it.

**Comment by jithendralal** [comment]
This was fixed in #1426
