### ISSUE TITLE
The SURGERYPATIENT CDE AllowMultiple - the widget RadioSelect to be removed

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1448]
The RadioSelect to be removed from sites system definition and synced on PROMS as well.

**Comment by jithendralal** [comment]
The SURGERYPATIENT CDE modified on CIC BC Staging site system - removed RadioSelect widget (CDE being Allow Multiple)

**TODO - the new definition to be synced to PROMS system for CIC BC Staging**

**Comment by jithendralal** [comment]
TO TEST:
The SURGERYPATIENT CDE is used in the pre-operation question in the 6-Months survey.
Multiple options to be selected in the survey and after submitting the survey, once the responses are pulled on site system, 
the form should correctly show the options selected in the survey.

**Comment by id2359** [comment]
Breast Cancer registry 1.0.10 ( ditto proms yaml)
md5
8339fdab55fe8a962ab13f559b6c84de  cicbreastclinical.yaml
49978b1fc244c41154abb494453c1745  cicbreastproms.yaml

rdrd next_release branch git hash a4e5ed3795ca146f6845234ef113f2f06561bcdd

**Comment by id2359** [comment]
( Usually the configuration error noted manifests as an error like: "Enter a list of values" on the cde after pulling the proms, because the value pulled down is a scalar ( e.g. "3" ) but the expected value for the datatype is a list.
