### ISSUE TITLE
CIC BC: Followup PROMS: Missing question

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1449]
In the CIC BC Followup PROMS 6 months survey. Possibly present in other followup surveys.

The question "Have you had one of the following re-operations since your surgery for breast cancer?" is a precondition question. The question afterwards asks the date of re-operation. This question is not asked, regardless of the answers to the precondition question.

This may be due to the precondition, which appears to always evaluate to false.

**Comment by id2359** [comment]
precondition evaluation going wrong here:  the precondition cde is allow_multiple , the value to check is a comma sep list.

The relations we support for preconditions are:

pre = value
pre in valuelist
pre contains value

but not 
**pre intersects valuelist**

We'll need to support last type to fix this

**Comment by jithendralal** [comment]
precondition cde allow multiple | precondition value | operator
| csv | or
y | csv | intersection
| v | =
y | v | contains
