### ISSUE TITLE
CIC CRC: Doubled Menu options

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1455]
On any of the clinical forms for any patient. Logged in as clinical.

The menu "Menu" contains doubled entries for the Deidentified Report, BCCA Report, and Completion Report.

![ciccrc_menudouble](https://user-images.githubusercontent.com/50615516/88127500-4f6fa700-cbc3-11ea-87da-1a8833be839e.png)

**Comment by jithendralal** [comment]
This fixes issue reported in #1472
