### ISSUE TITLE
CIC CRC: De-identified report: null id values

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1456]
In the CIC CRC de-identified report, all patients in the registry appear to have a unique, non-null ID, but there are 8 `"id": null` entries in approx. 50,000 lines of JSON.

**Comment by id2359** [comment]
Patient object manager operates over active patients ( not soft deleted) -

**Comment by gmaloneccg** [comment]
6.1.25 1.27 -- vim does not find the pattern `"id": null`;
![idnull_notfound](https://user-images.githubusercontent.com/50615516/89480945-2d128780-d786-11ea-9485-55bcf4c4d1c4.png)
