### ISSUE TITLE
CIC BC: Identified Report: Doubled menu option

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1462]
In CIC BC, logged in as clinical, on any patient clinical data page.

Two options for the Identified Report are present in the Menu.

![cicbc_identifiedreport_menudbl](https://user-images.githubusercontent.com/50615516/88358263-c3de4d80-cd5d-11ea-8804-2e0313d510aa.png)

**Comment by jithendralal** [comment]
This issue was fixed in #1455
