### ISSUE TITLE
CIC CRC named data csv report

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1481]
Develop csv file with named data" for CRC

**Comment by id2359** [comment]
First idea was to use csv generator but this does not include follow ups. Problem. I have emailed Angela

**Comment by id2359** [comment]
Done by adding an include all identified report on staging.

**Comment by gmaloneccg** [comment]
The IdentifiedReport appears to be missing the followup PROMS data -- a section of columns in the CSV is empty, corresponding to followup PROMS survey questions. The section begins with the first questions from the followup PROMS survey.

**Comment by gmaloneccg** [comment]
Opened #1492.
