### ISSUE TITLE
BCCA format rules for backend codes

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1486]
Backend code            Formatting permitted
nhi_number		AAANNNN
medicare_number		NNNN/NNNNN/N/N
dva_number		AAXXNNNN[A]
patient_postcode	XXXX

( These should be handleable by regular expressions  in the registry definition ( property on the cde model)

**Comment by jithendralal** [comment]
medicare_number NNNN/NNNNN/N/N - BCCA/BCCAPatientTab/BCCAmedicare_number - ^\d\d\d\d/\d\d\d\d\d/\d/\d$
Instructions: Enter the medicare number in the format NNNN/NNNNN/N/N eg. 1234/12345/1/1
dva_number AAXXNNNN[A] - BCCA/BCCAPatientTab/BCCAdva_number - 
patient_postcode XXXX - BCCA/BCCAPatientTab/BCCApatient_postcode

**Comment by gmaloneccg** [comment]
Medicare number field regex could be; `^\d{4}/\d{4}(/\d){2}$` (or with forward slash escaped, if necessary)
- Ruby finds that both patterns are equivalent;
![irb_regex_test](https://user-images.githubusercontent.com/50615516/89484534-40295580-d78e-11ea-85d6-0ff86dcc2125.png)

**Comment by gmaloneccg** [comment]
Opened #1489 and #1490.
