### ISSUE TITLE
CIC CRC: BCCA: Validation for Medicare number field

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1489]
In the CIC CRC BCCA form. The field for Medicare number (`BCCAmedicare_number`) does not have a validation pattern. The field features a max. length of 20, but no pattern.

The pattern could be `^\d{4}/\d{5}(/\d){2}$` given the current spec. This further suggests that the max. length could be limited to 14.

**Comment by jithendralal** [comment]
Added validation patter to BCCAmedicare_number
`^\d{4}/\d{5}(/\d){2}$`

eg. 1234/12345/1/1

The registry version was bumped up in #1494 with this to 1.28
