### ISSUE TITLE
CIC CRC: BCCA: Validation for postcode field

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1490]
In the CIC CRC BCCA form. The field for postcode (`BCCApatient_postcode`) is currently an integer, and does not feature any validation. The helper text states to enter 9999 is the postcode is unknown.

The validation pattern, if the field is string, could be `^\d{4}$`. If integer, the max. value could be given as 9999.

**Comment by jithendralal** [comment]
Added validation patter to BCCApatient_postcode CDE
`^\d{4}$`

The registry version was bumped up in #1494 with this to 1.28

**Comment by gmaloneccg** [comment]
As at 6.1.26 1.28, `BCCApatient_postcode` is an integer field, with a max. length of 4 (string only), no max. value, and no regex pattern. Long integers can be entered on the BCCA clinical form with no validation error.

**Comment by id2359** [comment]
Max length is not evaluated for integers as it is only applicable to string datatypes ( this is a deficiency in the admin interface currently.)

To close this ticket - add integer validation to prevent numbers > 9999 being entered and add min value of 0
