### ISSUE TITLE
CIC CRC: BCCA: Validation for DVA number field

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1494]
In the CIC CRC BCCA clinical forms. The validation for DVA number should be adjusted, according to an email from Lesley.

The pattern could be; `^[a-zA-Z]{2}[0-9]{6}[a-zA-Z]?$`

**Comment by jithendralal** [comment]
3 letters, 5 digits, 1 optional letter as per the DVA documentation:
`^[a-zA-Z]{3}\d{5}[a-zA-Z]?$`
