### ISSUE TITLE
CIC CRC: Change Password menu option missing

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1500]
In CIC CRC 6.1.25 1.27, logged in as clinical staff or admin. The menu option for Change Password is missing.

![ciccrc_clincal_changepass_missing](https://user-images.githubusercontent.com/50615516/89503189-b8574180-d7b5-11ea-8c02-774d417b4e6e.png)

**Comment by jithendralal** [comment]
This is dependent on the env var "enable_pwd_change"

**Comment by id2359** [comment]
Env var needs to be set on tests and in prod and staging to match crc ( which uses LDAP ):   Password management is via SJOG ldap admins not under user control.

**Comment by id2359** [comment]
Need to check CRC, BC and LC in prod

**Comment by id2359** [comment]
( by design)
