### ISSUE TITLE
OVMOST: Patient Doctor multi-panel section blocks saving Demographics

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1507]
In OVMOST, when adding a new patient or editing a patient's demographics data. Logged in as clinical staff.

On the patient's Demographics page, the multiple-panel section "Patient Doctor" has a required select CDE "Doctor". The list has no entries. This causes a validation error on saving, as there is nothing entered into the required field, so the page cannot be saved. This can be avoided by not adding a panel to this section, removing all panels in the section, or marking the panel for deletion.

**Comment by id2359** [comment]
Hid same demographic sections as CIC CRC
