### ISSUE TITLE
OVMOST: YOUR HEALTH TODAY

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1509]
In the OVMOST Baseline survey, Android One, Google Chrome browser.

The YOUR HEALTH TODAY slider does not appear as a slider, but as a text box. The slider also shows doubled instruction text, with no dot points.

![ovmost_yht_red](https://user-images.githubusercontent.com/50615516/90086929-19799a80-dd0b-11ea-8bc7-83215711d643.png)

**Comment by id2359** [comment]
Added widget config to survey question

{"widget_name": "slider", "max_label": "The best health you can imagine", "min_label": "The worst health you can imagine", "box_label": "YOUR HEALTH TODAY"}
