### ISSUE TITLE
CIC CRC: Add Follow Up Proms option

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1521]
In CIC Clinical v6.1.27 (RDRF v1.28), on the patients listing, logged in as clinical staff.

There is an option on the patients listing to add a followup PROMS survey without making a PROMS request. On each patient entry, in the drop-down menu marked "Follow up PROMS", there is an option marked "Add Follow Up Proms", which opens an empty followup survey page. The survey is saved and date-stamped in the correct form group when the page is saved.

![cicclinical_addpromsoption](https://user-images.githubusercontent.com/50615516/90719355-aa201f80-e2a3-11ea-887a-c1704ce4bf9d.png)

**Comment by APMCCG** [comment]
Issue no longer presents as of CIC CRC 1.31 & RDRF 6.3.17.
