### ISSUE TITLE
django-two-factor auth vuln

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1525]
Security policy
Security advisories
0
Dependabot alerts
3
django-two-factor-auth
 Open	GitHub opened this alert on 11 Jul
 Dependabot cannot update to the required version
View details about this error or learn more about Dependabot security updates.

1 django-two-factor-auth vulnerability found in rdrf/setup.py on 11 Jul
Remediation
Upgrade django-two-factor-auth to version 1.12.0 or later. For example:

install_requires=[
    'django-two-factor-auth>=1.12.0'
],
or…
extra_requires=[
    'django-two-factor-auth>=1.12.0'
],

**Comment by jithendralal** [comment]
- [x] unit tests pass
- [x] aloe tests pass
- [x] human testing 

Parent: #1529
