### ISSUE TITLE
Django security issue : Check upgrade possible 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1526]
Dependabot cannot update to the required version
View details about this error or learn more about Dependabot security updates.

5 django vulnerabilities found in rdrf/setup.py on 18 Feb
Remediation
Upgrade django to version 2.2.13 or later. For example:

install_requires=[
    'django>=2.2.13'
],
or…
extra_requires=[
    'django>=2.2.13'
],

**Comment by id2359** [comment]
Current 2.1.15

**Comment by jithendralal** [comment]
AssertionError: Database queries to 'clinical' are not allowed in this test. Add 'clinical' to rdrf.testing.unit.tests.UpdateCalculatedFieldsTestCase.databases to ensure proper test isolation and silence this failure.

**Comment by jithendralal** [comment]
Parent #1529
