### ISSUE TITLE
CIC CRC: Custom Action timeout page

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#1527]
In CIC CRC, logged in as clinical staff, using remote Chromium (Selenium, Ruby).

The following sequence of events occurred;

1. The BCCA Report was requested. Redirected to waiting page.
2. Laptop locked for lunch break.
3. Upon returning, the task was complete.
4. Clicked download link.
5. Credentials input popup appeared, but clicked Cancel.
6. Redirected to Django admin page;
![cicbc_apiroot](https://user-images.githubusercontent.com/50615516/91387083-f3341e80-e823-11ea-964c-38b4d75b1e1d.png)

**Comment by gmaloneccg** [comment]
Also tested without locking the laptop, i.e. with a "regular" timeout. The behaviour is identical if the credentials popup is cancelled when prompted.

**Comment by jithendralal** [comment]
`
REST_FRAMEWORK = {
    **'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),**
    'DEFAULT_AUTHENTICATION_CLASSES': (
       #  'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
`

**Comment by id2359** [comment]
Will be fixed by
