### ISSUE TITLE
CIC BC: Patient List module text issue

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1552]
CIC BC v1.0.14 (RDRF v6.1.28), logged in as clinical staff.

When selecting the "Follow up PROMS - Years 3 - 10" drop-down, the text for adding a survey is strangely spaced and possibly erroneous (see below).

![CIC_BC_PROMS_text_issue](https://user-images.githubusercontent.com/70674198/92094234-c9bc5980-ee06-11ea-96b0-d4abc0f5ccf5.png)

**Comment by id2359** [comment]
Add followup shouldn't be appearing in patient listing modules if add button on sidebar hidden
