### ISSUE TITLE
CIC CRC: Other characters in integer fields

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1564]
In CIC CRC v1.29 (RDRF v6.2.0), logged in as clinical staff.
The following characters other than numerals can be entered into integer fields: '+', '-', 'e'. If an attempt to save the data is made with any of these symbols in the field, the field clears and the save is successful, but no data is retained for the particular CDE.

**Comment by id2359** [comment]
1e1 doesn't validate on integer fields ( OK)
+ ok saved ok

**Comment by id2359** [comment]
+10 worked  ( 10 is displayed)

1e1 didn't validate
