### ISSUE TITLE
CIC CRC: Medicare number inconsistencies

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1565]
In CIC CRC v1.29 (RDRF v6.2.0), logged in as clinical staff.
When entering Medicare numbers, the last digit in the number is currently allowed to be zero, which is not possible for real Medicare numbers (the lowest digit is 1).

Affected CDEs:
 - Form: Patient Information, Section: Patient Identifiers, CDE: `Medicare`
 - Form: BCCA, Section: Patient Tab, CDE: `BCCAmedicare_number`

**Comment by id2359** [comment]
```
^\d{4}/\d{5}/\[1-9](/\[1-9])?$ 
```

Instructions don't match pattern currently on staging ??

Medicare validity depends on more than just a regular expression though ( check digit)

**Comment by jithendralal** [comment]
The Australian Medicare Number is made of:
identifier (8 digits) + checksum (1 digit) + issue no (1 non-zero digit) + IRN (1 non-zero digit)

**Comment by id2359** [comment]
Closing stale issue
