### ISSUE TITLE
CIC CRC: Deidentified Report - additional Baseline PROMS data

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1566]
In CIC CRC v1.29 (RDRF v6.2.0).
When comparing data in the Deidentified Report CSV to data in the system for Baseline PROMS, there is data recorded in the CSV that is not present in CIC CRC. For one patient (ID: staging-crc-40e14156-cbbb-11ea-ae4f-0242ac110010), multiple Baseline PROMS entries are recorded that contain:
 - more data than a regular Baseline PROMS, such as multiple questions from the Follow-up PROMS, e.g. stoma- & radiotherapy-related questions at columns XX to YE, YY, ABG to ABL, AEN, etc.; gender-identifying questions at columns ABM, ACW, AHP, AON, etc.
A specific example is `BaselineProms_3_EORTCQLQC29_2_1_EORTCQLQC29_Q49_NS` at column ABG: the section `EORTCQLQC39_2` and its element `EORTCQLQC29_Q49_NS` are not part of the `BaselineProms` form, but are part of the `FollowUpProms` form.
 - more question data than there are baseline questions, e.g. 50+ answers recorded from columns ZE to ABO, AFG to AHT, ALY to AOU, etc., when there are only 42 total questions in a Baseline PROMS).

Data in question can be found from columns WD to BEA in the Deidentified Report CSV created on 17/9/2020.

**Comment by id2359** [comment]
Processing of json needs definition to only expose columns in definition  - already fixed in latest cicap script
