### ISSUE TITLE
CIC CRC: Deidentified Report - unknown CDEs present

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1572]
In CIC CRC v1.29 (RDRF v6.2.0).
Some columns present in the Deidentified Report CSV do not align with CDEs/sections in the CIC CRC system or its associated YAML file. For example, the CDEs & sections recorded in columns BXF-BYU of the CSV for the `BaselineProms/1` form are only associated with Follow-up PROMS in the CIC CRC system and the YAML file, not with Baseline PROMS.
Additionally, the CDE `EORTCQLQC29_Q58` is present in the CSV in columns ACK, AHZ, ALG, ASH, AWR, BMD, BVS, BVU, BWZ, BYN, and BYW, but the CDE does not exist in the YAML file. Given that there is data in these columns for patients `staging-crc-40e14156-cbbb-11ea-ae4f-0242ac110010`, `staging-crc-41201fd4-cbbb-11ea-ae4f-0242ac110010`, `staging-crc-41342d94-cbbb-11ea-ae4f-0242ac110010`, and `staging-crc-41567e26-cbbb-11ea-ae4f-0242ac110010`, the CDE could be deprecated from a previous version of CIC CRC.

**Comment by jithendralal** [comment]
It was verified that a CDE with code EORTCQLQC29_Q58 is NOT being used in the BaseLinePROMS survey:
https://rdrf.ccgapps.com.au/cicclinical/admin/rdrf/survey/27/change/

**Comment by id2359** [comment]
Better to use the yaml to filter fields ( so only fields in the definition get mapped to columns in csv)

**Comment by jithendralal** [comment]
[staging-crc_20200917122654.txt](https://github.com/muccg/rdrf/files/5308590/staging-crc_20200917122654.txt)

The csv generated by the modified script is attached here. 
Please use it for testing.

**Comment by APMCCG** [comment]
The following CDEs have no data present for any patient, and are not part of the regular Baseline PROMS form:
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q31
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q32
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q33
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q34
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q35
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q36
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q37
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q38
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q39
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q40
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q41
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q42
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q43
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q44
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q45
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q46
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q47
BaselineProms/1/EORTCQLQC29/1/EORTCQLQC29_Q48
BaselineProms/1/EORTCQLQC29_1/1/EORTCQLQC29_Q49
BaselineProms/1/EORTCQLQC29_1/1/EORTCQLQC29_Q50
BaselineProms/1/EORTCQLQC29_1/1/EORTCQLQC29_Q51
BaselineProms/1/EORTCQLQC29_1/1/EORTCQLQC29_Q52
BaselineProms/1/EORTCQLQC29_1/1/EORTCQLQC29_Q53
BaselineProms/1/EORTCQLQC29_1/1/EORTCQLQC29_Q54
BaselineProms/1/EORTCQLQC29_1/1/EORTCQLQC29_Q55
BaselineProms/1/EORTCQLQC29_2/1/EORTCQLQC29_Q49_NS
BaselineProms/1/EORTCQLQC29_2/1/EORTCQLQC29_Q50_NS
BaselineProms/1/EORTCQLQC29_2/1/EORTCQLQC29_Q51_NS
BaselineProms/1/EORTCQLQC29_2/1/EORTCQLQC29_Q52_NS
BaselineProms/1/EORTCQLQC29_2/1/EORTCQLQC29_Q53_NS
BaselineProms/1/EORTCQLQC29_2/1/EORTCQLQC29_Q54_NS
BaselineProms/1/EORTCQLQC29_3/1/EORTCQLQC29_Q56
BaselineProms/1/EORTCQLQC29_3/1/EORTCQLQC29_Q57
BaselineProms/1/EORTCQLQC29_4/1/EORTCQLQC29_Q59
BaselineProms/1/MSKCC/1/MSKCC_Q01
BaselineProms/1/MSKCC/1/MSKCC_Q02
BaselineProms/1/MSKCC/1/MSKCC_Q03
BaselineProms/1/MSKCC/1/MSKCC_Q04
BaselineProms/1/PromsGender/1/PromsGender

**Comment by jithendralal** [comment]
These CDEs which are not being used in BaselineProms are filtered out, with reference to the current definition yaml.
