### ISSUE TITLE
CIC CRC: BCCA Report timeout issues

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1574]
In CIC CRC v1.29 (RDRF v6.2.0), logged in as clinical staff.
Follow-up to issue #1527. When testing the fix for this issue, the following occurred:
 - After allowing the system to time out and then clicking the download link for the BCCA report, the login page was displayed instead of a pop-up requesting credentials
 - Upon entering credentials and logging in, the BCCA report was successfully downloaded, but the page was not redirected away from the login page
 - If credentials were entered again and login re-attempted after the download, a 403 error occurred
 - If login was not re-attempted after the download, but an attempt was made to navigate to another page of the system, the login page would be displayed again. Logging into this page then redirected to the target page

**Comment by id2359** [comment]
We can redirect after successful download back to the patient listing ( completing the task) - this should move the user away from the login page in this case.
