### ISSUE TITLE
CIC CRC: Deidentified Report - unidentifiable patients

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1579]
CIC CRC v1.29 (RDRF v6.2.0)
In the most recent CIC CRC Deidentified Report CSV, there are patients present whose CIC IDs do not match those of any other patient in CRC, and as such do not appear when searched.
The patient IDs are:
 - staging-crc-40ec3282-cbbb-11ea-ae4f-0242ac110010
 - staging-crc-40ee051c-cbbb-11ea-ae4f-0242ac110010
 - staging-crc-411da5ba-cbbb-11ea-ae4f-0242ac110010
 - staging-crc-a6334d00-f88a-11ea-b02f-0242ac110009

**Comment by id2359** [comment]
cleaned data on staging
