### ISSUE TITLE
CIC CRC: Deidentified Report - missing patients

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1580]
CIC CRC v1.29 (RDRF v6.2.0)
In the most recent CIC CRC Deidentified Report CSV, there are some patients from CIC CRC whose IDs are not present despite being included in previous reports. The IDs for these patients are:
 - staging-crc-ea2ee796-fc98-11ea-a356-0242ac11000c
 - staging-crc-eb2c1bb6-cbc2-11ea-a915-0242ac110010
 - staging-crc-41502e2c-cbbb-11ea-ae4f-0242ac110010
 - staging-crc-315d2536-cd84-11ea-b8a6-0242ac110010
 - staging-crc-ef2efb18-d09d-11ea-8d6d-0242ac11000b
 - staging-crc-5fd6fff8-e298-11ea-a3b8-0242ac11000e

**Comment by id2359** [comment]
Archived patients ?
