### ISSUE TITLE
CIC BC: PROMS - duplicate data pulled

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1592]
In CIC BC v1.0.14 (RDRF v6.2.1).

For patient `staging-bc-6e433b24-d6e0-11ea-afe4-0242ac110016`, after completing a Follow-up PROMS - Years 3-10, the Proms page was refreshed and the page for the survey selected before the pull was completed and incomplete data was displayed. Upon returning to the Proms page without saving, a duplicate set of data was pulled 60 seconds after the first and saved as a separate survey - both surveys contained all data from the completed PROMS.
Only one PROMS request was created for this type of survey. The issue could not be replicated in other patients.

**Comment by id2359** [comment]
Probably a timing issue  - lots of completed surveys on the proms site are for the older named surveys so they never get deleted or processed ( but are downloaded ) - as we log this , it must have blown out the time to longer than normal

**Comment by id2359** [comment]
Possible solution: Add a "in process" state when to SurveyRequest so that we don't try to process the same record at the same time in two overlapping crons -- if the state is set to received at the end of processing , the survey assignment will get deleted
