### ISSUE TITLE
CIC BC: reports excluding patients

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1593]
In CIC BC v1.0.14 (RDRF v6.2.1), logged in as clinical staff.

In the CSV files generated by the Identified Report, Completion Report, and Identified Everything custom actions, there are only rows for those patients who have recorded more data than the compulsory demographics information (presently 20 of 24 patients). The patients currently excluded from the reports are as follows:
`staging-bc-6e4e4d70-d6e0-11ea-afe4-0242ac110016`
`staging-bc-c622848e-e66d-11ea-8112-0242ac110008`
`staging-bc-92be0d74-d219-11ea-a87d-0242ac110015`
`staging-bc-d6f27b52-e839-11ea-8e0f-0242ac110008`

**Comment by id2359** [comment]
Even if no dynamic data, this should pull dmeographic columns properly
