### ISSUE TITLE
Check dependency updates

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1594]
install pur
copy setup.py  to some local file outside the codebase call it requirements.txt
copy to a backup file

download/install kdiff3

run pur on requirements.txt ( in place updates the file()
run kdiff3 to check the updates
document in ticket

**Comment by APMCCG** [comment]
32 dependencies require updating.

13 major version changes:
 - celery: 4.4.7 -> 5.0.0
 - Django: 2.2.13 -> 3.1.2
 - django-anymail: 7.2.1 -> 8.1
 - django-ajax-selects: 1.9.1 -> 2.0.0
 - django-extensions: 2.2.5 -> 3.0.9
 - geoip2: 2.9.0 -> 4.1.0
 - openpyxl: 2.6.4 -> 3.0.5
 - pycountry: 19.8.18 -> 20.7.3
 - setuptools-scm: 3.3.3 -> 4.1.2
 - django-otp: 0.7.4 -> 1.0.1
 - django-phonenumber-field: 2.4.0 -> 5.0.0
 - Pillow: 6.2.2 -> 8.0.0
 - kombu: 4.6.8 -> 5.0.2

12 minor version changes:
 - django-registration-redux: 2.6 -> 2.8
 - djangorestframework: 3.9.4 -> 3.12.1
 - django-storages: 1.8 -> 1.10.1
 - pyyaml: 5.2 -> 5.3.1
 - six: 1.13.0 -> 1.15.0
 - SQLAlchemy: 1.2.5 -> 1.3.20
 - phonenumberslite: 8.11.1 -> 8.12.11
 - ua-parser: 0.8.0 -> 0.10.0
 - django-user-agents: 0.3.2 -> 0.4.0
 - django-simple-history: 2.8.0 -> 2.12.0
 - Markdown: 3.1.1 -> 3.3.1
 - django-redis: 4.11.0 -> 4.12.1

7 patch changes:
 - psycopg2: 2.8.4 -> 2.8.6
 - pyodbc: 4.0.27 -> 4.0.30
 - pyparsing: 2.4.5 -> 2.4.7
 - uwsgi: 2.0.18 -> 2.0.19.1
 - django-two-factor-auth: 1.12.0 -> 1.12.1
 - django-reversion: 3.0.5 -> 3.0.8
 - django-session-security: 2.6.5 -> 2.6.6

**Comment by APMCCG** [comment]
Upgrades not performed as part of this issue will be addressed in issues #1605 and #1606.
