### ISSUE TITLE
Check security audit branch in trrf 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1633]

**Comment by id2359** [comment]
https://github.com/eresearchqut/trrf/compare/6d2b7e4b5df1b142493690602211b923b9344d8b...9701f76cf7c510fb395b02c8c6460f010ce02ce2

**Comment by id2359** [comment]
Create python script to check views

**Comment by APMCCG** [comment]
Initial check of security updates: [trrf_security_updates.txt](https://github.com/muccg/rdrf/files/5963081/trrf_security_updates.txt)
