### ISSUE TITLE
Add login required mixin or use decorators on additonal views

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1638]
For each of these we need to decide what action to take:

Actions being

W - whitelist
F -  Fix ( add LoginRequiredMixin class)
D - delete code as it is not used anymore
I - Ignore ( this is ok as it is)

when action done check the box

when all actions are done we can close the ticket

Non-secure views found:
- File: /home/amalone/src/rdrf/rdrf/rdrf/routing/login_router.py
- [x] ['RouterView']

I

- File: /home/amalone/src/rdrf/rdrf/rdrf/views/registry_list_view.py
- [x] ['RegistryListView']

D

- File: /home/amalone/src/rdrf/rdrf/rdrf/views/proms_views.py
- [x] ['PromsCompletedPageView']
- [x] ['PromsView']
- [x] ['PromsLandingPageView']
- File: /home/amalone/src/rdrf/rdrf/rdrf/views/registry_view.py
- [x] ['RegistryView']
I
 - File: /home/amalone/src/rdrf/rdrf/rdrf/views/landing_view.py
- [x] ['LandingView']
I
- File: /home/amalone/src/rdrf/rdrf/rdrf/views/copyright_view.py
- [x] ['CopyrightView']
F ( nb this was 500ing if user wasn't logged in ( empty response)

- File: /home/amalone/src/rdrf/rdrf/rdrf/views/lookup_views.py
- [x] ['UsernameLookup']

I  ok because used by registration view via ajax 

- [x] ['RecaptchaValidator']

I  ok because meant to be used in registration before users created

- File: /home/amalone/src/rdrf/rdrf/rdrf/views/clinician_view.py
- [x] ['ClinicianActivationView']

I ok because used as a registration process

- File: /home/amalone/src/rdrf/rdrf/rdrf/views/patients_listing.py
- [x] ['PatientsListingView']

redirects away when not logged in but why not add decorator??????

- File: /home/amalone/src/rdrf/rdrf/rdrf/services/rest/views/proms_api.py
- [x] ['SurveyEndpoint']
- [ ] 
- File: /home/amalone/src/rdrf/rdrf/explorer/views.py

- [x] ['SqlQueryView']

**Comment by APMCCG** [comment]
Whitelist implemented with pull request #1652.
