### ISSUE TITLE
Email template change test 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1650]
Added

<br>
<b><font color='red'>Google Chrome or Firefox (recent versions) web browsers <i>need</i> to be used,</font> as other web browsers are not supported.</b>
<br>

to proms email

Works on

- [x] CRC
- [x] Lung
- [x] Breast

**Comment by APMCCG** [comment]
Re-opening as tests of actual PROMS workflows not completed in Safari (iPad).

- [x] PC (Ubuntu Linux, Chrome)
- [x] Mobile (Android, Chrome & Firefox)
- [ ] Tablet (iOS, Safari)
