### ISSUE TITLE
OVMOST Definition change

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1651]
Test the new Instruction text on several questions:

MOSTFollow_up_Q1,MOSTFollow_up_Q2,MOSTFollow_up_Q3,MOSTFollow_up_Q4,MOSTFollow_up_Q5,MOSTFollow_up_Q6,MOSTFollow_up_Q7,MOSTFollow_up_Q8,

MOSTFollow_up_Q9,MOSTFollow_up_Q10,MOSTFollow_up_Q11,MOSTFollow_up_Q12,MOSTFollow_up_Q13,MOSTFollow_up_Q14,MOSTFollow_up_Q15,MOSTFollow_up_Q16,

MOSTFollow_up_Q17, MOSTFollow_up_Q18,MOSTFollow_up_Q19,MOSTFollow_up_Q20, MOSTFollow_up_Q22,MOSTFollow_up_Q23,MOSTFollow_up_Q24,MOSTFollow_up_Q25, MOSTFollow_up_Q26ar, ,MOSTFollow_up_Q26br, MOSTFollow_up_Q26cr

The new text is in the instructions - 

It should look like: 

No problem = 0. Slight = 1,2,3. Somewhat = 4,5,6. Considerably = 7,8,9. Worst possible = 10.

**Comment by APMCCG** [comment]
Text updated successfully for all questions except MOSTFollow_up_Q20. Functionality of PROMS not affected. Success across all approved browsers and platforms.
