### ISSUE TITLE
FH: non-patient relative Family Linkage issues

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1654]
In FH 0.1.69 (RDRF 6.3.2).
When attempting the following process, an unexpected validation error occurs with the message "FAIL: ‘NoneType’ object has no attribute ‘id’":
 - Create index patient with 2 relatives, one patient, one non-patient
 - On the Family Linkage page, click and drag the relative patient from the "Relatives" section to the "Index Patient" section
 - Save the page

**Comment by id2359** [comment]
FL = Family Linkage screen
R = Relative with no associated patient record 
RP = Relative with an associated patient record
IP = Index patient

indexify(x) = drags x to the index area in FL

Family = (Index , [ rels ])


Where Family = ( X, [ RP, R ] ) and indexify(RP) is attemped error occurs

but indexify(R) works and R has a new associated patient created
