### ISSUE TITLE
Create UAT Guide for CIC CRC HSS Rollout

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1656]
Angela has requested we have some testing guides sent to the UAT ( user acceptance testing) clinicians for Colorectal Cancer.

We can use the use case testing documents as a basis.

Ideally ,

a) Copy your existing testing templates to a new set of documents on Gdrive so I can send through.
b) Make it clear ( consistent naming of GUI etc ) and touch up the presentation so it looks ok - aim for understandability by non-software developers.

**Comment by APMCCG** [comment]
The document can be found at the following link:
https://docs.google.com/document/d/1h9E5hPak6TMpN_uLg0s6Hnb6criEQ0xbaoQMEtg2UTA/edit?usp=sharing
