### ISSUE TITLE
Check new python base image for rdrf

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1669]
Currently our docker files for RDRF inherit from python:3.8-slim-buster

via our muccg/docker-python-base images

Would be good to create an experimental branch of RDRF using  a later base image

**Comment by id2359** [comment]
In your experimental branch:
Try changing Dockerfile-base in ~/src/rdrf

FROM muccg/python-base:3.8-debian-10  --> FROM muccg/python-base:3.9-debian-10


Do a sanity build and regression test locally.
Do a push origin branchname to exercise our build tests on that python version.

**Comment by APMCCG** [comment]
Unable to update Python version - change is breaking as newer versions of Selenium (> 3.3.1) are incompatible with newest version of Aloe (0.2.0).
