### ISSUE TITLE
Deactivate CIC explorer urls

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1672]
these shouldn't be exposed in CIC as Views  ( via url patterns)

( Do we have a specific flag in settings for a Site system.)

 - explorer/urls.py
   - explorer/query/<query_id> - accessible through explorer if registry has explorer access
   - explorer/query/download/<query_id>/<action> - accessible for downloading and viewing through explorer
   - explorer/query/delete/<query_id> - accessible through explorer
   - explorer/new - accessible through explorer
   - explorer/sql - inaccessible (expected - SQLQueryView not user-facing view)

**Comment by APMCCG** [comment]
Explorer views are already blacklisted for CIC users in rdrf/rdrf/urls.py.
