### ISSUE TITLE
Check api views and admin page links for CIC

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1705]
In RDRF 6.3.5.
Some of the API views are not necessary to functionality of RDRF for CIC, and the URLs should be de-registered.

**Comment by APMCCG** [comment]
URLs registered for non-CIC:
 - api/v1/registries
 - api/v1/registries/<registry_code>
 - api/v1/registries/<registry_code>/patients
 - api/v1/registries/<registry_code>/patients/<patient_id>
 - api/v1/registries/<registry_code>/clinicians
 - api/v1/registries/<registry_code>/indices
 - api/v1/workinggroups
 - api/v1/countries
 - api/v1/countries/<country_code>/states
 - api/v1/calculatedcdes
 - api/v1/tasks/<task_id>
 - api/v1/taskdownloads/<task_id>
 - api/v1/users
 - api/v1/doctors
 - api/v1/nextofkinrelationship

URLs registered for CIC:
 - api/v1/registries
 - api/v1/registries/<registry_code>
 - api/v1/registries/<registry_code>/patients
 - api/v1/registries/<registry_code>/patients/<patient_id>
 - api/v1/registries/<registry_code>/indices
 - api/v1/workinggroups
 - api/v1/countries
 - api/v1/countries/<country_code>/states
 - api/v1/calculatedcdes
 - api/v1/tasks/<task_id>
 - api/v1/taskdownloads/<task_id>

URLs that could be potentially removed from CIC based on initial testing:
 - api/v1/registries
 - api/v1/registries/<registry_code>
 - api/v1/registries/<registry_code>/patients (only the specific patient url is used)
 - api/v1/registries/<registry_code>/indices
 - api/v1/workinggroups

**Comment by id2359** [comment]
Check the final quicklinks menu ordered dict locally
