### ISSUE TITLE
React test framework check

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1718]
Can we:

1. Add a module to test our react components
2. Invoke it (somehow ) in the build system

Put relevant info/links below. ( I don;t expect this to be fixed immediately just assemble what we need to do )

**Comment by APMCCG** [comment]
Testing libraries
Jest documentation: https://jestjs.io/docs/getting-started
React Testing Library documentation: https://testing-library.com/docs/react-testing-library/intro

Create React App testing documentation: https://create-react-app.dev/docs/running-tests/
 - Jest comes as default testing library
 - Can install RTL with `npm install --save-dev @testing-library/react` (plus Jest DOM if needed - `@testing-library/jest-dom`)

**Comment by APMCCG** [comment]
[React testing setup notes.txt](https://github.com/muccg/rdrf/files/6160978/React.testing.setup.notes.txt)

**Comment by APMCCG** [comment]
Code that needs to be added for testing: [React testing - code to add.txt](https://github.com/muccg/rdrf/files/6168570/React.testing.-.code.to.add.txt)

**Comment by APMCCG** [comment]
Initial React testing is in place and working in build system. Any extensions to testing will be in later tickets.
