### ISSUE TITLE
RDRF: Custom Action Execution admin page error

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1719]
In RDRF 6.3.7.
Following the steps below in any registry causes an AttributeError to occur with the message "type object 'NoneType' has no attribute '_meta'":
 - Login as admin
 - Go to Custom Action Executions admin page (admin/rdrf/customactionexecution)
 - Click the "Add" button at the top-right of the page (admin/rdrf/customactionexecution/add)

**Comment by id2359** [comment]
Better to make add button invisible in GUI
