### ISSUE TITLE
is-svg 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1727]
is-svg
 Open	GitHub opened this alert 2 days ago
 Dependabot cannot update is-svg to a non-vulnerable version
The latest possible version that can be installed is 3.0.0 because of the following conflicting dependency:

react-scripts@3.4.0 requires is-svg@^3.0.0 via a transitive dependency on postcss-svgo@4.0.2
The earliest fixed version is 4.2.2.

View logs or learn more about troubleshooting Dependabot errors.

1 is-svg vulnerability found in …/frontend/yarn.lock 2 days ago
Remediation
Upgrade is-svg to version 4.2.2 or later. For example:

is-svg@^4.2.2:
  version "4.2.2"
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by id2359** [comment]
https://create-react-app.dev/docs/updating-to-new-releases/

**Comment by APMCCG** [comment]
Currently unable to upgrade: latest version of react-scripts does not yet address the security issues (https://github.com/facebook/create-react-app/issues/10698).

**Comment by APMCCG** [comment]
After upgrading `react-scripts` to latest version (#1738), `postcss-svgo` dependency has been updated from 4.0.2 to 4.0.3 and security issue has been addressed. Refer to https://github.com/cssnano/cssnano/ for more information.
