### ISSUE TITLE
RDRF: React frontend - unexpected action payload

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1744]
The `submitAnswers` action, used in the reducer to send survey data to RDRF, is currently used as the "onClick" event handler for the "Submit Answers" button on the last page of the PROMS surveys in the frontend. This causes the emitted action to have an empty event object attached to it as a payload - this payload is not being used by the reducer, and has caused issues in React testing.

**Comment by id2359** [comment]
Make payload null like the other actions that don't use a payload.
