### ISSUE TITLE
Investigate timeout code

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1759]
User requested we lengthen the timeout code ( feature which logs the user out after a period of inactivity.)

- [x] Find out where timeout code is
- [x] Answer whether its configurable
- [ ] If not , suggest a possible solutions

**Comment by APMCCG** [comment]
The session timeout for RDRF is controlled by the `SESSION_SECURITY_EXPIRE_AFTER` environment variable, which can be configured in the docker-compose files. This variable, if defined, is used to set the timeout within `settings.py`. If the variable is undefined, the timeout defaults to 600 seconds.
Code (line 744 in `settings.py`):
`SESSION_SECURITY_EXPIRE_AFTER = env.get("session_security_expire_after", 600)`

**Comment by id2359** [comment]
can we switch this feature off?
