### ISSUE TITLE
promsgender error on HSS update proms

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1771]
for cic crc uat

registry.log.2021-04-22:[ERROR:2021-04-22 13:25:29,820:proms_api.py:372:_update_proms_fields] could not locate cde PromsGender: cannot unpack non-iterable NoneType object | Traceback (most recent call last):
registry.log.2021-04-22:TypeError: cannot unpack non-iterable NoneType object

**Comment by id2359** [comment]
PromsGender cde doesn't exist on hss uat crc
( PromsGenderSection didn't exist either)

PromsSex CDEPermittedValueGroup did exist


On staging the section and cde exist but the section is not a member of a form


This must have been created manually on staging to workaround the importer or exporter skipping these.

**Comment by id2359** [comment]
I manually added the cde on hss uat crc - will need to fix this on the others also and get the value exported properly

**Comment by id2359** [comment]
This is just getting skipped from looking at the code

**Comment by APMCCG** [comment]
The `PromsSystemManager` class is used to download the PROMS data, and attempts to match the CDEs in the submitted survey with those in the FollowUpProms form using internal method `_locate_cde`. This method takes the target form & CDE models, attempts to find the relevant form and section on the site system the CDE is located in, and returns both to the calling function `_update_proms_fields`:

(proms_api.py, line 414)
```
...
for form_model in form_models:
    for section_model in form_model.section_models:
        if not section_model.allow_multiple:
            for cde_model in section_model.cde_models:
                if cde_model.code == target_cde_model.code:
                    return form_model, section_model
```

However, the PromsGender CDE and PromsGenderSection section are not part of the FollowUpProms form on the site system, so `_locate_cde` does not reach the `return` statement, and `_update_proms_fields` instead attempts to assign a value of `None` to the form and section variables. This throws the error that's being logged:

(proms_api.py, line 365)
```
...
    else:
        form_model, section_model = self._locate_cde(cde_model, context_model, target_form_model)
except BaseException as e:
    import traceback
    trace_back = traceback.format_exc()
    message = str(e) + " | " + str(trace_back)
    logger.error(f"could not locate cde {cde_code}: {message}")
    # should fail for now skip

    continue
...
```

**Comment by APMCCG** [comment]
The fact that the PromsGender CDE can't be located is not actually an error, as the CDE is not saved to avoid redundant patient sex data, but the way it is logged makes it look like one.
