### ISSUE TITLE
Update Bootstrap

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1774]
Branch with updated bootstrap and jquery doesn't work ( as expected)

Implement the changes needed to make RDRF use latest bootstrap.

**Comment by jithendralal** [comment]
- bootstrap css class names have changed in this new version 5.0.0 - this hinders the display of navbar menus
-

**Comment by jithendralal** [comment]
Modified files today:

        modified:   rdrf/rdrf/static/css/rdrf.css
        modified:   rdrf/rdrf/templates/rdrf_cdes/base-1-col.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/clinician.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/custom_consent_form.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/form.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/form_group_button_component.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/form_readonly.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/generic_patient.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/patient_edit.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/patients_listing.html
        modified:   rdrf/rdrf/templates/rdrf_cdes/rdrfcontext_launcher.html

**Comment by jithendralal** [comment]
The latest commit to this branch 
https://github.com/muccg/rdrf/commit/df8f7437c6796eb5070a733686d88912d7520140

**Comment by APMCCG** [comment]
Upgrading Bootstrap to v5.0.0 is causing the majority of Aloe tests to fail - the step 'go to the registry "(.*)"' in `steps.py` fails after clicking the registry list dropdown (`utils.click(world.browser.find_element_by_link_text('Registries on this site'))`), as the link elements within the dropdown do not appear, but __only in the tests and not in the local build__. This appears to be an issue in `bootstrap.min.js` for Bootstrap v5, as the event handler for clicking the dropdown is not functioning in the test container. Have attempted to fix the issue using information from the following links:
- https://stackoverflow.com/questions/18345714/bootstrap-dropdown-menu-not-working-not-dropping-down-when-clicked
- https://stackoverflow.com/questions/9529574/bootstrap-dropdown-menu-not-working
- https://stackoverflow.com/questions/66997690/site-navigation-bootstrap-toggle-not-working
- https://stackoverflow.com/questions/12458522/bootstrap-dropdown-not-working
- https://stackoverflow.com/questions/17651078/bootstrap-dropdowntoggle-method-doesnt-work

**Comment by APMCCG** [comment]
Bootstrap-related breaking issues:
 - [ ] Missing icons - some glyphicons still remain, some Font Awesome icons are not displaying
 - [ ] Broken modals - the CDE history and admin consents modals do not display (being handled by ticket #1814)
 - [ ] Missing validation highlighting - fields in patient forms are not highlighted when they do not pass validation

Style issues:
 - The following file contains a list of the currently-identified style issues: [bootstrap_5_style_issues.txt](https://github.com/muccg/rdrf/files/6667060/bootstrap_5_style_issues.txt)

Outdated libraries:
 - [ ] jQuery UI (jquery-ui-1.11.4.min.js)
     - Current version: 1.11.4
     - Updated version: 1.12.1
 - [ ] jQuery datatables (jquery.datatables.min.js & jquery.datatables.min.css)
     - Current version: 1.10.12
     - Updated version: 1.10.24

**Comment by APMCCG** [comment]
Remaining class changes:
- [ ] `close` (for button elements)
    - Affected templates:
        - archive_modal.html
        - consent_list.html
        - form_field_history.html
        - import_registry.html
    - Replace with: `btn-close`
- [ ] `thumnail`
    - Affected templates:
        - change_form.html
    - Replace with: `card`
- [ ] `well`
    - Affected templates:
        - form_readonly.html
        - reports.html
        - landing.html
        - form_print.html
        - form.html
        - report_table_view.html
        - change_list_results.html
    - Replace with: `card`
- [ ] `alert-dismissable`
    - Affected templates:
        - import_registry.html
    - Replace with: `alert-dismissible`
- [ ] `divider` (for dropdown elements)
    - Affected templates:
        - base-2-cols.html
        - base-1-col.html
        - portfolio.html
        - rdrf_cdes/base.html
        - rdrf_cdes/index.html
    - Replace with: `dropdown-divider`
- [ ] `alert-alert`
    - Affected templates:
        - family_linkage.html
        - questionnaire_handling.html
    - Replace with: N/A
- [ ] `panel-info` (replaced with `card-info` in templates, which is not a viable class)
    - Affected templates:
        - rdrf_cdes/base.html
        - clinician.html
        - permission_matrix.html
        - questionnaire_handling.html
        - two_factor/_base.html
    - Replace with: no official replacement, but a combination of `alert-info` and `border-info` works

**Comment by APMCCG** [comment]
Style issues with Bootstrap 5 upgrade:
- Landing page
    - [ ] Navbar not transparent
    - [ ] Hidden navbar-toggle made visible
    - [ ] Significant increase in footer text size
    - [ ] Very little spacing between divided sections
    - [ ] Links in dropdown wrapping incorrectly (`dropdown-item` is misspelled as `dropdwn-item`)
- Login page
    - [ ] Labels no longer bolded
    - [ ] Very little spacing between field sides and card border
- Login assistance sent page
    - [ ] Slight vertical alignment issues for text in `alert-warning` alert
- Login assistance password reset page (from email link)
    - [ ] Labels no longer bolded
    - [ ] Differing field and button alignment
- Password reset page (from User Menu option)
    - [ ] Labels no longer bolded
    - [ ] Differing field and button alignment
- Two-factor auth start page
    - [ ] Minor vertical text spacing issues
    - [ ] Change in how `btn-link` displays (may have to fix with styles)
- Two-factor auth setup page
    - [ ] Very little spacing between "Token" field sides and card border
    - [ ] Minor vertical text spacing issues
    - [ ] Change in how `btn-link` displays (may have to fix with styles)
- Two-factor auth login page
    - [ ] Very little spacing between "Token" field sides and card border
- Two-factor auth disable page
    - [ ] Checkbox label no longer bolded
- Patients List
    - [ ] Dropdown buttons in "Modules" column displaying differently
    - [ ] Table row borders not as light
- Add patient page
    - [ ] "Save" and "Cancel" buttons aligned incorrectly
    - [ ] All field labels aligned left instead of right
    - [ ] Labels no longer bolded
    - [ ] Dropdowns missing arrow icons
    - [ ] "Add" buttons on multiform CDEs have dark font instead of light
    - [ ] Section width significantly reduced
- Demographics page
    - [ ] All field labels aligned left instead of right
    - [ ] Labels no longer bolded
    - [ ] Dropdowns missing arrow icons
    - [ ] "Add" buttons on multiform CDEs have dark font instead of light
    - [ ] Patient ID in top banner vertically misaligned with other elements
    - [ ] Text wrapping on long labels causing vertical spacing issues
    - [ ] Vertical spacing issues in text for file CDE with file uploaded
    - [ ] Section width significantly reduced
    - [ ] "Saved successfully" alert does not match width of sections
- Consents page
    - [ ] All field labels aligned left instead of right
    - [ ] Labels no longer bolded
    - [ ] "Add" buttons on multiform CDEs have dark font instead of light
    - [ ] Vertical spacing issues in text for file CDE with file uploaded
    - [ ] Patient ID in top banner vertically misaligned with other elements
    - [ ] Section width significantly reduced
    - [ ] "Saved successfully" alert does not match width of sections
- Dynamic form pages
    - [ ] All field labels aligned left instead of right
    - [ ] Labels no longer bolded
    - [ ] "Add" buttons on multiform CDEs have dark font instead of light
    - [ ] "Print" buttons have dark font instead of light
    - [ ] Vertical spacing issues in text for file CDE with file uploaded
    - [ ] Patient ID in top banner vertically misaligned with other elements
    - [ ] Section width significantly reduced
    - [ ] "Saved successfully" alert does not match width of sections
    - [ ] Header text (e.g. "Please click the green 'Save' button before progressing to the next form") not bordered and font size significantly larger
    - [ ] History modal width significantly reduced
    - [ ] History modal table column spacing significantly reduced
    - [ ] "Chart" button in history modal not greyed out when element cannot be plotted
    - [ ] No cursor change when hovering over greyed out "Chart" button in history modal
- PROMS page
    - [ ] Card header fill does not reach card borders
    - [ ] "Existing Surveys" table width reduced significantly
    - [ ] Inline style colouring of text content in table removed
    - [ ] Patient ID in top banner vertically misaligned with other elements
    - [ ] Labels no longer bolded in "New Survey Request" modal
    - [ ] Dropdowns missing arrow icons in "New Survey Request" modal
- Family Linkage page
    - [ ] Section width significantly reduced
- Explorer page
    - [ ] "No" option in report delete dropdown not styled as a link
- Explorer edit/add report pages
    - [ ] Labels no longer bolded
- Custom action pages
    - [ ] Date field labels no longer bolded on Completion Report page
- Admin pages
    - [ ] No padding between tables and containing card borders
    - [ ] Consent list modal width significantly reduced
    - [ ] Text misaligned and displaying incorrectly in "\<p class='card'\>" elements at top of pages
    - [ ] Page content aligned further left
    - [ ] Very little spacing between heading elements on "change" pages 
    - [ ] "Resend" buttons on Email Notification History page have dark font instead of light
- Navbar
    - [ ] Dropdowns overlapping with navbar
    - [ ] Dropdowns aligned differently
