### ISSUE TITLE
FH: Unsaved changes dialog on unchanged Clinical Data page

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1778]
The following issue has presented in the rdrf-1775-patient-timeout-fix branch (see PR #1777):
- Branch is adding `django-session-security` functionality to patient forms
- After navigating to Clinical Data page for patient, a dialog with the following text displays when attempting to reload or navigate to another page - "Leave site? Changes that you made may not be saved"
- Dialog displays even if no changes have been made
- Issue possibly caused by `django-session-security` detecting loading of calculated CDEs as changes to page

**Comment by id2359** [comment]
Given this is a non-merged branch it's low priority - I suspect this side-effect is the reason we didn't apply that code to the clinical pages
