### ISSUE TITLE
FH: Incomplete data prefill when linking patient to index

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1789]
In RDRF 6.3.20.
Following on from issue #1228, the same problem occurs when linking a patient to an index.
Steps to reproduce:
1. Create two separate patients.
2. On the family linkage page for one patient, add the other with the "Add looked up patient to family" button and save.
3. Go to the Patient Relative section of the Demographics page for the new index - the entry for the other patient does not have Sex, Location, or Living status filled.

**Comment by id2359** [comment]
unit tests would be good
