### ISSUE TITLE
FH/RDRF: Login assistance - Incorrect message after password reset email sent

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1792]
In RDRF 6.3.20.
When a user enters his/her email to the login assistance page (https://rdrf.ccgapps.com.au/ophg/login_assistance) and clicks the "Submit" button, the password reset email successfully sends and the user is redirected to https://rdrf.ccgapps.com.au/ophg/login_assistance_email_sent. However, this page displays the message "This URL does not exist, or you are not logged in." This message still displays if the page is accessed while logged in, but the password reset workflow itself is not affected.

**Comment by id2359** [comment]
One problem is that this page is likely generic ,

**Comment by id2359** [comment]
View:  RegistryView


url:

 re_path(r"^(?P<registry_code>\w+)/?$",
            registry_view.RegistryView.as_view(), name='registry'),
