### ISSUE TITLE
Use django-csp across the board

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1801]
- [x] Update middleware to use csp
- [x] Update all inline scripts to use nonces
- [x] Fix inline styles

The following html files have inline scripts

filepath  number of inlines

- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/base.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/base-2-cols.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/permission_matrix.html 2
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/form_readonly.html 2
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/form.html 2
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/base-1-col.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/application_error.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/family_linkage.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/completed_questionnaire_thankyou.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/questionnaire_handling.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/rdrf_cdes/information.html 1
- [x] ome/lee/src/rdrf/rdrf/rdrf/templates/proms/base.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/admin/change_list.html 1
- [x] /home/lee/src/rdrf/rdrf/rdrf/templates/admin/change_form.html 1

**Comment by id2359** [comment]
Also styles in divs etc

**Comment by id2359** [comment]
After making this apply for non-proms sites, we're getting a build fail.

**Comment by APMCCG** [comment]
Some of the styles cannot be applied nor some scripts executed with the current CSP.
Issues:
- Inline event handlers can't have a nonce applied
    - Solutions:
        - Move event handlers to an inline script with a nonce
        - Move event handlers to a JS file
- Inline style attributes on elements can't have a nonce applied
    - Solutions:
        - Replace styles with classes
        - Move styles to an inline style block with a nonce
        - Move styles to a CSS file
- Any references to external resources is blocked (e.g. jquery.validate.min.js being loaded from ajax.aspnetcdn.com, any icons being loaded by Bootstrap)
    - Solutions:
        - Adjust CSP to allow specific external links
        - Replace all external resources with local resources (see https://getbootstrap.com/docs/5.0/customize/overview/#csps-and-embedded-svgs for Bootstrap CSP info)

**Comment by APMCCG** [comment]
External links referred to:
- https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js (by rdrf/templates/rdrf_cdes/base.html)
- http://www.w3.org/2000/svg (by Bootstrap CSS, vendors.css, and vendors-bundle.js)
- https://fonts.googleapis.com (by theme.css & expanded-theme.css, various different font links)
- https://cdn.jsdelivr.net/npm/promise-polyfill@8.1.3/dist/polyfill.min.js (by calculated_field_plugin.js)
- https://cdn.jsdelivr.net/npm/whatwg-fetch@3.4.0/dist/fetch.umd.min.js (by calculated_field_plugin.js)

**Comment by APMCCG** [comment]
Remaining CSP issues:
- RDRF code
    - CountryWidget class adds inline event handler to country fields
    - Nonces are not being applied to inlines in rdrfcontext_launcher.html
    - Calculated field scripts are generated in Python without a nonce
    - Some registry definitions contain inline style attributes
- jQuery
    - "Add" buttons on multiform CDEs are not functioning
        - Script/style?: Style
        - RDRF code: `$("<hr>").attr("style", "border: solid 1px gray").appendTo(new_form);` (in add_form)
    - Consent modal styles not applying
        - Script/style?: Style
        - RDRF code: `var first_save = $("<td>").attr("class", "col-md-2").attr("style", "text-align:center;").text(value.first_save);` (in get_consent_details)
    - Admin change list search bar styles not applying
        - Script/style?: Style
        - RDRF code: `$("#toolbar").attr("style", "text-align:right");` (anonymous function in change_list.html)
    - Family linkage search dropdown image blocked due to using a URL to apply it
        - Script/style?: Script
        - RDRF code: `lookupIndex` function (in family_linkage.html)
    - CDE history modal styles not applying
        - Script/style?: Style
        - RDRF code: `rdrf_click_form_field_history` function (in form.js)
- Other external resources
    - Session security overlay is not hidden - inline style attribute is blocked
    - Session security script setting up warning & automatic logout is blocked
    - Bootstrap SVGs (select field arrow, modal close button, etc.) are blocked due to using a URL to apply the image
    - Underscore.js tries to evaluate strings as JS code (Family Linkage, Explorer)
