### ISSUE TITLE
The registry dropdown is not clickable in the aloe tests with bootstrap 5 changes

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1812]
The registry dropdown is not clickable in the tests

Relates to https://github.com/muccg/rdrf/issues/1774

( use same branch rdrf-1774 for this ticket )

The aloe tests don't start.

I have tried updating selenium and the chrome container in this branch - probably best to revert to earlier version to not muddy the waters.
Then  try to replicate the failure to click the registry dropdown in a local test build.

The issue _might_ relate to differences between the test container volume  and dev container ( which does allow click ) : reason being collect static copies js files into /data/static which is mapped to different local directories )

**Comment by APMCCG** [comment]
Registry dropdown is now clickable, but tests are still failing.
