### ISSUE TITLE
Harden applicability_condition evaluation

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1819]

**Comment by jithendralal** [comment]
MTM has
`
    patient.age >= 18 and patient.patient_type not in ['deceased','carrier']
    patient.has_guardian and patient.patient_type not in ['deceased','carrier']
    patient.age >= 16 and patient.age < 18 and patient.patient_type
    patient.patient_type == 'deceased'
    patient.patient_type == 'carrier'
    patient.age >= 11 and patient.age < 16 and patient.patient_type
    patient.age < 11 and patient.patient_type not in ['deceased','carrier']
`
