### ISSUE TITLE
jQuery 3.6.0: Report datatable "Column Visibility" button error

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1837]
This ticket relates to #1774.
With jQuery 3.6.0 installed, when viewing a report on the site ("reportdatatable" page) an error occurs after clicking on the "Column Visibility" button. The dropdown opens as expected, but it cannot be closed, the rest of the page does not function, and any interaction causes the following error:
```
Uncaught TypeError: d(...).parents(...).andSelf is not a function
    at HTMLBodyElement.<anonymous> (datatables.min.js:214)
    at HTMLBodyElement.dispatch (jquery-3.6.0.min.js:2)
    at HTMLBodyElement.v.handle (jquery-3.6.0.min.js:2)
```

**Comment by jithendralal** [comment]
This issue was not seen in my testing.

Tested this using: 
- rdrf-1774 branch
- FH definition
- SYSTEM_ROLE left to be NORMAL
- removed the containers and volumes and did a fresh build
