### ISSUE TITLE
Bootstrap 5: Style differences and minor styling issues

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1839]
Remaining style differences and issues after Bootstrap 5 upgrade #1774 (some may not need changing):
- Landing page
    - [x] ~~Significant increase in footer text size~~ Spacing and alignment of footer links done instead, font size does not require changing
    - [x] Very little spacing between divided sections
- Login page
    - [x] Labels no longer bolded
    - [x] Very little spacing between field sides and card border
- Login assistance password reset page (from email link)
    - [x] Labels no longer bolded
- Password reset page (from User Menu option)
    - [x] Labels no longer bolded
- Two-factor auth start page
    - [x] Minor vertical text spacing issues
    - [x] Change in how `btn-link` displays (may have to fix with styles)
- Two-factor auth setup page
    - [x] Very little spacing between "Token" field sides and card border
    - [x] Minor vertical text spacing issues
    - [x] Change in how `btn-link` displays (may have to fix with styles)
- Two-factor auth login page
    - [x] Very little spacing between "Token" field sides and card border
- Two-factor auth disable page
    - [x] Checkbox label no longer bolded
- Patients List
    - [x] Dropdown buttons in "Modules" column displaying differently
    - [x] ~~Table row borders not as light~~ Styling applied by jQuery Datatables plugin
- Add patient page
    - [x] Labels no longer bolded
    - [x] ~~"Add" buttons on multiform CDEs have dark font instead of light~~ Style change not required, text is readable
- Demographics page
    - [x] Labels no longer bolded
    - [x] ~~"Add" buttons on multiform CDEs have dark font instead of light~~ Style change not required, text is readable
    - [x] ~~Text wrapping on long labels causing minor vertical spacing issues~~ Issue no longer presenting
    - [x] ~~Minor vertical spacing issues in text for file CDE with file uploaded~~ Text is generated by Django - unable to style without CSS for label elements
- Consents page
    - [x] Labels no longer bolded
    - [x] ~~"Add" buttons on multiform CDEs have dark font instead of light~~ Style change not required, text is readable
    - [x] ~~Minor vertical spacing issues in text for file CDE with file uploaded~~ Text is generated by Django - unable to style without CSS for label elements
- Dynamic form pages
    - [x] Labels no longer bolded
    - [x] ~~"Add" buttons on multiform CDEs have dark font instead of light~~ Style change not required, text is readable
    - [x] ~~"Print" buttons have dark font instead of light~~ Style change not required, text is readable
    - [x] ~~Minor vertical spacing issues in text for file CDE with file uploaded~~ Text is generated by Django - unable to style without CSS for label elements
- PROMS page
    - [x] ~~Labels no longer bolded in "New Survey Request" modal~~ Text is generated by Django - unable to style without CSS for label elements
- Explorer page
    - [x] "No" option in report delete dropdown not styled as a link
- Explorer edit/add report pages
    - [x] Labels no longer bolded
- Report data tables
    - [x] ~~Height of table area increased~~ Height of table is variable depending on column titles
- Custom action pages
    - [x] ~~Date field labels no longer bolded on Completion Report page~~ Text is generated by Django - unable to style without CSS for label elements
- Admin pages
    - [x] No padding between tables and containing card borders
    - [x] Consent list modal width significantly reduced
    - [x] Text misaligned and displaying incorrectly in "\<p class='card'\>" elements at top of pages
    - [x] ~~Page content aligned further left~~ Issue no longer presenting
    - [x] Very little spacing between heading elements on "change" pages 
    - [x] ~~"Resend" buttons on Email Notification History page have dark font instead of light~~ Style change not required, text is readable
- Navbar
    - [x] ~~Dropdowns overlapping with navbar~~ Very minor visual difference that would require large style changes to correct

**Comment by id2359** [comment]
Only do if payoff effort/benefit worth is -ie will take a day

**Comment by APMCCG** [comment]
Style issues without simple fixes:
- Demographics page
    - [ ] Minor vertical spacing issues in text for file CDE with file uploaded
- Consents page
    - [ ] Minor vertical spacing issues in text for file CDE with file uploaded
- Dynamic form pages
    - [ ] Minor vertical spacing issues in text for file CDE with file uploaded
- PROMS page
    - [ ] Labels no longer bolded in "New Survey Request" modal
- Custom action pages
    - [ ] Date field labels no longer bolded on Completion Report page
