### ISSUE TITLE
ov changes before go live

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1849]
- [x] Baseline PROMS email: definition change - Email Templates
- [x] Follow-up PROMS email: definition change - Email Templates
- [x] PROMS preamble: definition change - Registry metadata
- [x] Consent question text: codebase change - renderConsent in frontend/src/pages/proms_page/components/question.tsx

**Comment by id2359** [comment]
[210705 Ovarian PROMS blurb.docx](https://github.com/muccg/rdrf/files/6773934/210705.Ovarian.PROMS.blurb.docx)

**Comment by id2359** [comment]
consent text: default to current hardcoded one
We could put a different message in the registry metadata to specialise it 

I'd rather not have to do a release of all registries just for  this last item

**Comment by jithendralal** [comment]
Though the build failed on travis (tests failing), with CSP disabled, locally the build finished without error.

**Comment by jithendralal** [comment]
Note: 
Custom text to be added with the key "survey_consent_information" in registry metadata.
