### ISSUE TITLE
CSP: Session security scripts and styles blocked

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1856]
This ticket relates to #1801.
The session security plugin generates inline script and style blocks without nonces, which causes the CSP to block them. A solution to this is to add the hashes of the scripts/styles to the CSP header.

**Comment by APMCCG** [comment]
Fixed in branch rdrf-1801-django_csp, commit e16603c902d9ffd95815c6923da454abc29043d2 - hashes for script & style blocks added to CSP header.

**Comment by id2359** [comment]
Need to determine the actual affect on system behaviour:

Does this stop an end  user getting a timeout popup message? Only in admin interface?
Does session timeout no longer work?

**Comment by jithendralal** [comment]
Tested locally, with ENABLE_CSP=1 in env.
Did not see the issue happening locally 
(The console does not show any csp blocked messages. In the original issue, the console was showing the blocked message.)
