### ISSUE TITLE
theme.css has reference to previous version of bootstrap css

### ISSUE THREAD

**Issue by jithendralal** [muccg/rdrf#1863]
issue found is /static/css/compiled/theme.css has this reference:
`@import url(../../bootstrap-3.3.6/css/bootstrap.min.css);`

And these external references 
`
@import url(https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300italic,300,400italic,500,500italic,700,700italic,900,900italic);
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic);
@import url(https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic);
@import url(https://fonts.googleapis.com/css?family=Merriweather:400,300italic,300,400italic,700,700italic);
`

On the page http://localhost:8000/ console shows 404 error:
`GET http://localhost:8000/static/bootstrap-3.3.6/css/bootstrap.min.css net::ERR_ABORTED 404 (Not Found)`

theme.css is being used in these templates only:
T1  rdrf/emplates/rdrf_cdes/index.html 
T2  rdrf/emplates/rdrf_cdes/portfolio.html - for http://localhost:8000/reglist

**Comment by id2359** [comment]
For T1 update fonts to not use problematic ones.

For T2 : better to remove view and template entirely. ( problem solved)
