### ISSUE TITLE
make csp configurable

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1869]

**Comment by jithendralal** [comment]
- CSP is enabled by default
- CSP can be disabled through environment

**Comment by jithendralal** [comment]
set the env var to disable csp
- ENABLE_CSP=0

**Comment by jithendralal** [comment]
csp is disabled by default
set the env var to enable csp

    ENABLE_CSP=1

**Comment by jithendralal** [comment]
Since csp_nonce is being used in inline scripts and styles, 
after building, the csp has to be enabled for those pages to work.
