### ISSUE TITLE
check memcache usage

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1879]
Would be good to optimise queries which are just definition models.

E.g.

Getting the cdes in a survey - this is not going to change much 

ditto getting the forms in a registry or the sections in a form or the cdes in a section etc.

Jith:

- [x] check memcache locally - what is getting populated?

**Comment by jithendralal** [comment]
Something like this can be done:

from django.core.cache import cache
cache.set('registry', Registry.objects.get(code='ICHOMCRC'))
cache.get('registry')
