### ISSUE TITLE
RDRF: Session security script blocked by CSP on site systems

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1883]
In RDRF 6.5.0, from the 16/7/21 regression test of CIC CRC on staging.
The script generated by the session security plugin to control warnings and automatic logouts is being blocked by the current CSP, as the hash used in the "script-src" directive only works for local builds. The "ping" URL in the script depends on the current site URL, which changes the hash depending on the site.

**Comment by APMCCG** [comment]
Hash to be added to "script-src" to allow script on CIC CRC: 'sha256-Ut7O38MTFhdBSL9zq+wGU9ELSKxY14TMB8ts4gZ0XAs='

**Comment by id2359** [comment]
https://rdrf.ccgapps.com.au/ov/static/session_security/script.js
generated script:


            var sessionSecurity = new yourlabs.SessionSecurity({
                pingUrl: '/ov/session_security/ping/',
                warnAfter: 480,
                expireAfter: 600,
                confirmFormDiscard: "You have unsaved changes in a form of this page."
            });

**Comment by id2359** [comment]
```
    
    <script type="text/javascript" src="/ov/static/session_security/script.js"></script>

    
    
        <script type="text/javascript">
            var sessionSecurity = new yourlabs.SessionSecurity({
                pingUrl: '/ov/session_security/ping/',
                warnAfter: 480,
                expireAfter: 600,
                confirmFormDiscard: "You have unsaved changes in a form of this page."
            });
        </script>
        

```
