### ISSUE TITLE
RDRF: Demographics page validation SVGs blocked by CSP

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1884]
In RDRF 6.5.0, from the 16/7/21 regression test of CIC CRC on staging. Follow-up to #1857.
When saving a patient's Demographics page with invalid data, the current validation highlighting for invalid fields attempts to add an SVG to the field as well as the border colour. These SVGs are currently not stored locally and are thus blocked by the "image-src" CSP directive. This does not affect the functionality of the page and does not prevent the relevant border colours from being applied.

**Comment by id2359** [comment]
Use local icon not svg to workaround
