### ISSUE TITLE
RDRF: Password reset link uses incorrect domain

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1885]
In RDRF 6.5.0, from the 16/7/21 regression test of CIC CRC on staging.
After submitting a user's email as part of the logged-out password reset workflow, the reset link in the email that is sent to the user uses the "example.com" domain instead of the site domain - this means the user cannot complete the workflow by clicking on the link. However, the token in the link is still valid on the site system, and can be copied and used to complete the workflow.

**Comment by id2359** [comment]
config of site object
