### ISSUE TITLE
RDRF: JavaScript TypeError on Custom Actions admin page

### ISSUE THREAD

**Issue by APMCCG** [muccg/rdrf#1886]
In RDRF 6.5.0, from the 16/7/21 regression test of CIC CRC on staging.
When accessing any of the Custom Actions admin pages (list of actions, adding action, editing action), the following error appears in the browser console:
```
Uncaught TypeError: j is not a function
    at custom_action.js:23
```

`j` is defined on line 2 of custom_action.js as follows:
```
j = django.jQuery;
```

**Comment by jithendralal** [comment]
Found this issue in local testing as well.
