### ISSUE TITLE
CIC CRC Failed test - PROMS options

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1888]
Complete the survey and check that all data have been correctly pulled on the Baseline PROMS page
Expected result: All data aligns with survey answers
Actual result: All answers with options “Not at all”, “A little”, “Quite a bit”, and “Very much” (misspelled as “Very mich”) are off by one, and any questions answered with “Not at all” are not recorded and have validation errors
Pass/fail: Fail

**Comment by jithendralal** [comment]
Tested with Version 6.5.0 1.31

**Comment by id2359** [comment]
now fixed after sync of new definition for crc
