### ISSUE TITLE
cic crc followup proms regression

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1889]
via Alfie
Complete survey and check pulled data as with step 15, but check for the survey appearing under the Follow up PROMS section on the sidebar
Expected result: All data aligns with survey answers
Actual result: All answers with options “Not at all”, “A little”, “Quite a bit”, and “Very much” (misspelled as “Very mich”) are off by one, and any questions answered with “Not at all” are not recorded and have validation errors
Pass/fail: Fail

**Comment by jithendralal** [comment]
Tested with Version 6.5.0 1.31

Questions answered with “Not at all” are recorded correctly.
https://rdrf.ccgapps.com.au/cicclinical/ICHOMCRC/forms/8/110/215

**Comment by id2359** [comment]
Definition has now been synced and is appearing in PROMS survey.

Data in staging site system before change is still there ( ie wrong)

Spelling error noted above not fixed ( new ticket)
