### ISSUE TITLE
Patient has data saved in proms and clinical forms but all red crosses in forms drop down in patient listing

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1895]
Patient has data saved in proms and clinical forms but all red crosses in forms drop down in patient listing.

One patient, reported in SJOG Colorectal cancer. Patient has data.

I have tested on site with a new test patient and can't replicate.
Other patients ok by look of it.

- [x] Try to replicate on staging
- [x] Check codebase and determine what condition is being checked for a green tick.

**Comment by APMCCG** [comment]
Unable to replicate on staging, green ticks showing in PROMS & clinical forms with saved data.
The condition being checked for the tick is "is_current", a method property of the FormsButton class. This check is performed in the "forms_button.html" template.
"is_current" checks form currency using FormProgress class methods.
