### ISSUE TITLE
Send data into Redis when UMRN query made

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1922]
We need to be able to identify which registry/application container sent the query for data to HIH endpoint.

Because we have 4 distinct registry containers , we need to use an external system to store that metadata. We already use a single Redis container for the backend of Celery and it is ideal as a "Blackboard System", so let's use that to store the data.

Lets use a Redis Set to store umrns per registry container

e.g.

key = crc:umrns 

value : a Redis set   e.g.    {"123", "300", ...  }    ( all UMRNs so far known in crc )
( see https://redis.io/topics/data-types-intro )

use SADD  ( should be exposed in django redis wrapper)

**Comment by jithendralal** [comment]
https://redis.io/topics/persistence

added a volume mapping for redis container ./data/redis:/data
the aof file is saved in it by redis: ./data/redis/appendonly.aof

**Comment by id2359** [comment]
Closing because sadd operation done in view.

Redis persistence options need to be added in HSS uat and prod as an ops change
