### ISSUE TITLE
HL7 field mappings 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1928]
- [x] Find response message to the query ( has MSH.9 == qry_a19 )
- [x] for demographic fields - find corresponding message paths ( segment / field number) 
- [x] note any transforms we need 

Mappings defined for demographics update from adr 19:
```
{
    "Demographics/family_name": {"path": "PID.F5.R1.C1"},
    "Demographics/given_names": {"path": "PID.F5.R1.C2"},
    "Demographics/umrn": {"path": "PID.F2"},
    "Demographics/date_of_birth": {"path": "PID.F7", "transform": "date"},
    "Demographics/date_of_death": {"path": "PID.F29", "transform": "date"},
    "Demographics/place_of_birth": {"path": "PID.F23"},
    "Demographics/country_of_birth": {"path": "PID.F11.R1.C6"},
    "Demographics/ethnic_origin": {"path": "PID.F22.R1.C2"},
    "Demographics/sex": {"path": "PID.F8"},
    "Demographics/home_phone": {"path": "PID.F13"},
    "Demographics/work_phone": {"path": "PID.F14"}
```

demographic fields we have :
http://localhost:8000/admin/rdrf/demographicfields/

**Comment by id2359** [comment]
https://hl7-definition.caristix.com/v2/HL7v2.6/TriggerEvents/QRY_A19

**Comment by jithendralal** [comment]
|Demographics Field|ADR_A19 path|
|--|--|
|Given names| |

**Comment by jithendralal** [comment]
With the modified structure:

{"QRY_A19": {
    "Demographics/family_name": {"path": "PID.F5.R1.C1"},
    "Demographics/given_names": {"path": "PID.F5.R1.C2"},
    "Demographics/umrn": {"path": "PID.F2"},
    "Demographics/date_of_birth": {"path": "PID.F7", "transform": "date"},
    "Demographics/date_of_death": {"path": "PID.F29", "transform": "date"},
    "Demographics/place_of_birth": {"path": "PID.F23"},
    "Demographics/country_of_birth": {"path": "PID.F11.R1.C6"},
    "Demographics/ethnic_origin": {"path": "PID.F22.R1.C2"},
    "Demographics/sex": {"path": "PID.F8"},
    "Demographics/home_phone": {"path": "PID.F13"},
    "Demographics/work_phone": {"path": "PID.F14"}
}
