### ISSUE TITLE
Integration Framework Field Updater - create update dictionary

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1929]
Need code to take the data update dictionary from the parser and update the patient data accordingly.

1. Use HL7Mapping model to grab json mapping info.
2. Use defined HL7 message "paths" to extract the field data from the message.
3. Transform based on defined transform functions.

result will be a dictionary of field paths to values

**Comment by jithendralal** [comment]
{ "Demographics/family_name": {"path": "PID.5.1.1", "transform": "identity"}, "Demographics/given_names": {"path": "PID.5.2", "transform": "identity"}, "Demographics/umrn": {"path": "PID.2.1", "transform": "identity"}, "Demographics/date_of_birth": {"path": "PID.7", "transform": "date"}, "Demographics/date_of_death": {"path": "PID.29", "transform": "date"}, "Demographics/place_of_birth": {"path": "PID.23", "transform": "identity"}, "Demographics/country_of_birth": {"path": "PID.11.6", "transform": "identity"}, "Demographics/ethnic_origin": {"path": "PID.22.2", "transform": "identity"}, "Demographics/sex": {"path": "PID.8", "transform": "identity"}, "Demographics/home_phone": {"path": "PID.13.12", "transform": "identity"}, "Demographics/work_phone": {"path": "PID.14.12", "transform": "identity"} }
