### ISSUE TITLE
confirm date fields work in surveys 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1937]
If not we'll have to update the React code

**Comment by jithendralal** [comment]
A date type CDE was added to a section and then added as a survey question.
The date widget was rendered like shown below:

**Comment by jithendralal** [comment]
on CIC CRC Staging:
added the cde, section
used the section in baseline proms form
added the survey qquestion to the baseline proms survey 
bumped up version 1.32 to 1.33
