### ISSUE TITLE
How to make demographic labels more dynamic?

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1955]
This is going to be a problem if we unhide the patient umrn field which is labelled currently as Hospital/Clinic ID for some reason.

**Comment by jithendralal** [comment]
Testing:
The umrn in DemographicFields is set to **Readonly** and **not Hidden** to make the custom label visible for clinical users.

**Comment by jithendralal** [comment]
**Testing:**

The **umrn** field in **DemographicFields** is set to **Readonly** and **not Hidden** to make the custom label visible for **clinical** users.

**Comment by jithendralal** [comment]
**Testing:**

The **umrn** field in **DemographicFields** is set to **Readonly** and **not Hidden** to make the custom label visible for **clinical** users.
