### ISSUE TITLE
Treating clinician is hardcoded in definition

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#1986]

**Comment by id2359** [comment]
Just investigate available options

**Comment by jithendralal** [comment]
Add a datasource in rdrf.forms.widgets.datasources.py
```
class Clinicians(DataSource):
    def values(self):
        registry_model = self.context["registry_model"]
        clinicians_group = Group.objects.get(name="Clinical Staff")
        clinicians = []
        for custom_user in CustomUser.objects.filter(registry__in=[registry_model],
                                                     groups__in=[clinicians_group]):
            clinicians.append((custom_user.get_full_name(), custom_user.get_full_name()))
        return clinicians
```

**Comment by id2359** [comment]
The existing registry defs have the old style field:
lee@xublr:~/src/rdrd/defs$ find . -type f   | xargs grep -i datasource
./hss/uat/hss-uat-ls-proms.yaml:  widget_name: DataSourceSelect:PatientCentres
./hss/uat/hss-uat-bc-site.yaml:  widget_name: DataSourceSelect:PatientCentres
./hss/uat/hss-uat-lc-site.yaml:  widget_name: DataSourceSelect:PatientCentres
./hss/uat/hss-uat-bc-proms.yaml:  widget_name: DataSourceSelect:PatientCentres
./hss/prod/bc-site.yaml:  widget_name: DataSourceSelect:PatientCentres
./prod/mtm.yaml:  widget_name: DataSourceSelect:PatientCentres
./prod/ovmost-site.yaml:  widget_name: DataSourceSelect:PatientCentres
./prod/rarelipid.yaml:  widget_name: DataSourceSelect:PatientCentres
./staging/lc-proms.yaml:  widget_name: DataSourceSelect:PatientCentres
./staging/mtm.yaml:  widget_name: DataSourceSelect:PatientCentres
./staging/bc-site.yaml:  widget_name: DataSourceSelect:PatientCentres
./staging/ovmost-site.yaml:  widget_name: DataSourceSelect:PatientCentres
./staging/lc-site.yaml:  widget_name: DataSourceSelect:PatientCentres
./staging/bc-proms.yaml:  widget_name: DataSourceSelect:PatientCentres
./sjog/prod/lc-midland-site.yaml:  widget_name: DataSourceSelect:PatientCentres
./sjog/prod/lc-midland-proms.yaml:  widget_name: DataSourceSelect:PatientCentres
./sjog/prod/bc-subiaco-site.yaml:  widget_name: DataSourceSelect:PatientCentres

**Comment by id2359** [comment]
just reopening until we resolve problem above

**Comment by jithendralal** [comment]
Changes made for the earlier version of widgets work: **DataSourceSelect:PatientCentres**

**Comment by jithendralal** [comment]
This was tested 
by adding a CDE with widget DataSourceSelect:PatientCentres
and another CDE with widget DataSourceSelect and widget_config {"tag":"diabetic"}
