### ISSUE TITLE
Entered File CDEs on invalid sections where a required field is missing are re-initialising 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#244]
To replicate:
Make a section with:
A a file cde
B a required field of any type

If a file is uploaded for A  but no data is entered for B
the form is invalid and the content is re-displayed to the user BUT
the file upload is not re-initialised so that when the form is submitted with the missing data entered the file is not actually uploaded.

**Comment by rvl** [comment]
This is a general problem with file fields and validation in Django forms.
