### ISSUE TITLE
Yaml import/export- Form order is not retained

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#251]

**Comment by rvl** [comment]
Thanks, Kathryn. Which RDRF version was the YAML exported from?

**Comment by rvl** [comment]
Also, what exactly is in the wrong order? Are the forms in the wrong order, sections in the wrong order, or CDEs in the wrong order? Which registry?

**Comment by aahunter** [comment]
@knapier feedback required

**Comment by knapier** [comment]
Apologies, just saw the comments @aahunter @rvl 

Form order is set on 'Registry Form' under 'position'. This is not saved when exporting or importing (I'm not sure at what stage). When ever I import a new yaml, for any registry, I have to manually reset the order position. This gets very tedious for registries such as Angelman which has >10 forms.

Section and CDE order is fine.
