### ISSUE TITLE
Styling of 'delete' button 

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#287]
Using chrome, delete button appears cut off

<img width="1222" alt="screen shot 2016-10-24 at 10 06 17 am" src="https://cloud.githubusercontent.com/assets/17611855/19631848/4f4b4854-99d3-11e6-9792-6c34ef5800a2.png">

**Comment by rvl** [comment]
Does this look like an ok fix?

![admin-buttons](https://cloud.githubusercontent.com/assets/1019641/19677633/21d352c6-9a92-11e6-9b26-0bd202b2fe97.png)

**Comment by knapier** [comment]
Looks good to me @rvl !
