### ISSUE TITLE
'dict' object has no attribute 'gridfs_dict'

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#290]
Editing demographics form on FH staging /ophg:

AttributeError at /fh/patient/523/edit
'dict' object has no attribute 'gridfs_dict'
Request Method: POST
Request URL:    https://rdrf.ccgapps.com.au/ophg/fh/patient/523/edit
Django Version: 1.10.2
Exception Type: AttributeError
Exception Value:  
'dict' object has no attribute 'gridfs_dict'
Exception Location: /app/rdrf/rdrf/registry_specific_fields.py in save_registry_specific_data_in_mongo, line 44
Python Executable:  /env/bin/uwsgi
Python Version: 3.5.2
Python Path:  
['.',
 '/app',
 '/app/rdrf',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/env/lib/python3.5/site-packages']
Server time:    Tue, 25 Oct 2016 09:35:42 +0800
Traceback Switch to copy-and-paste view

/env/lib/python3.5/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _legacy_get_response
            response = self._get_response(request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, _callback_args, *_callback_kwargs) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/views/generic/base.py in view
            return self.dispatch(request, _args, *_kwargs) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/views/generic/base.py in dispatch
        return handler(request, _args, *_kwargs) ...
▶ Local vars
/app/rdrf/rdrf/patient_view.py in post
            registry_specific_fields_handler.save_registry_specific_data_in_mongo(request) ...
▶ Local vars
/app/rdrf/rdrf/registry_specific_fields.py in save_registry_specific_data_in_mongo
                                form_value = file_wrapper.gridfs_dict ...
▶ Local vars

**Comment by knapier** [comment]
Mixed Content: The page at 'https://rdrf.ccgapps.com.au/ophg/fh/patient/523/edit' was loaded over a secure connection, but contains a form which targets an insecure endpoint 'http://dpaste.com/'. This endpoint should be made available over a secure connection.

**Comment by id2359** [comment]
The "existing_data" looks like:

existing_data	
{'fh': {'FHFounderEffectOrigin': 'FHFEODutchAfrikaaners',
        'FHNum1stDegRelatives': '1',
        'FHNum2ndDegRelatives': '2',
        'FHNum3rdDegRelatives': '3',
        'FHPedigreeUpload': {'django_file_id': 36,
                             'file_name': 'dummyfile.txt'},
        'context_id': None}}

The file upload is a dictionary but the code is expecting an object - a FileWrapper

gridfs_dict   is no longer used though?

**Comment by id2359** [comment]
Fixed run time error by using the dict directly

The download link is not appearing despite the file cde  being saved with the correct structure to Mongo
