### ISSUE TITLE
File upload does not refresh page with link to file

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#291]
Upload file- save page- link to file does not appear. Need to refresh page in order to see the link.

**Comment by id2359** [comment]
This is in the clinical forms

Affer save of a clinical form the link doesn't appear

If one lands on the page again ( using GET) the link is shown

**Comment by id2359** [comment]
The view post method wraps the file upload but this doesn't (yet) have an associated django file id
Investigating how to return that
