### ISSUE TITLE
NoReverseMatch at /admin/useraudit/loginattempt/

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#298]
User locked out due to 3 incorrect log in attempts. Admin user trying to access 'User log in attempts log'

NoReverseMatch at /admin/useraudit/loginattempt/
Reverse for 'reactivate_user' with arguments '(25,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method: GET
Request URL:    https://rdrf.ccgapps.com.au/mtm/admin/useraudit/loginattempt/
Django Version: 1.10.2
Exception Type: NoReverseMatch
Exception Value:  
Reverse for 'reactivate_user' with arguments '(25,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location: /env/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 392
Python Executable:  /env/bin/uwsgi
Python Version: 3.5.2
Python Path:  
['.',
 '/app',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/env/lib/python3.5/site-packages',
 '/env/src/django-rdrf/rdrf',
 '/app/mtm']
Server time:    Fri, 28 Oct 2016 14:25:54 +0800
Error during template rendering

In template /env/src/django-rdrf/rdrf/rdrf/templates/admin/change_list.html, error at line 99
Reverse for 'reactivate_user' with arguments '(25,)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
89        {% endblock %}
90        {% block date_hierarchy %}{% date_hierarchy cl %}{% endblock %}
91  
92        <form id="changelist-form" action="" method="post"{% if cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %}>{% csrf_token %}
93        {% if cl.formset %}
94          <div>{{ cl.formset.management_form }}</div>
95        {% endif %}
96  
97        {% block result_list %}
98            {% if action_form and actions_on_top and cl.full_result_count %}{% admin_actions %}{% endif %}
99            {% result_list cl %}
100           {% if action_form and actions_on_bottom and cl.full_result_count %}{% admin_actions %}{% endif %}
101       {% endblock %}
102  
103       {% block pagination %}{% pagination cl %}{% endblock %}
104       </form>
105     </div>
106   </div>
107 
108     <script>
109         $(document).ready(function($) {
Traceback Switch to copy-and-paste view

/env/lib/python3.5/site-packages/django/db/models/options.py in get_field
            return self.fields_map[field_name] ...
▶ Local vars
During handling of the above exception ('activate'), another exception occurred:
/env/lib/python3.5/site-packages/django/contrib/admin/utils.py in lookup_field
        f = _get_non_gfk_field(opts, name) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/contrib/admin/utils.py in _get_non_gfk_field
    field = opts.get_field(name) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/db/models/options.py in get_field
            raise FieldDoesNotExist('%s has no field named %r' % (self.object_name, field_name)) ...
▶ Local vars
During handling of the above exception (LoginAttempt has no field named 'activate'), another exception occurred:
/env/lib/python3.5/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _legacy_get_response
            response = self._get_response(request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
                response = response.render() ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/response.py in render
            self.content = self.rendered_content ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/response.py in rendered_content
        content = template.render(context, self._request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/backends/django.py in render
            return self.template.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render
                    return self._render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render_annotated
            return self.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/loader_tags.py in render
        return compiled_parent._render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in _render
        return self.nodelist.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render_annotated
            return self.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/loader_tags.py in render
                result = block.nodelist.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render_annotated
            return self.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/loader_tags.py in render
                result = block.nodelist.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render
                bit = node.render_annotated(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/base.py in render_annotated
            return self.render(context) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/template/library.py in render
        _dict = self.func(_resolved_args, *_resolved_kwargs) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/contrib/admin/templatetags/admin_list.py in result_list
            'results': list(results(cl))} ...
▶ Local vars
/env/lib/python3.5/site-packages/django/contrib/admin/templatetags/admin_list.py in results
            yield ResultList(None, items_for_result(cl, res, None)) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/contrib/admin/templatetags/admin_list.py in __init__
        super(ResultList, self).**init**(_items) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/contrib/admin/templatetags/admin_list.py in items_for_result
            f, attr, value = lookup_field(field_name, result, cl.model_admin) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/contrib/admin/utils.py in lookup_field
            value = attr(obj) ...
▶ Local vars
/env/lib/python3.5/site-packages/useraudit/admin.py in activate
            activation_url = reverse("reactivate_user", args=[user.id,]) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/urls/base.py in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, *_kwargs))) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/urls/resolvers.py in _reverse_with_prefix
            (lookup_view_s, args, kwargs, len(patterns), patterns) ...
▶ Local vars

**Comment by id2359** [comment]
the "possibilties" list of  urls list has zero length I noticed - why I don't know yet
