### ISSUE TITLE
The users should be warned that their password will expire soon

### ISSUE THREAD

**Issue by sztamas** [muccg/rdrf#369]
Currently, there is no warning for the user that their password will expire, so if they are not proactive about changing their password regularly one day they won't be able to log in.

The details is to be determined, can be email and/or warning on the web page.

**Comment by sztamas** [comment]
For now I've just added a warning message to the web page.
I think that's good enough and doesn't need the complications of email templates having to be configured etc.

Let me know if the email notification is a must as well.

**Comment by knapier** [comment]
Email notification would be good, and has been requested by FH. I'll ticket up.
