### ISSUE TITLE
'working group staff' users can not view clinical forms

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#397]
Permissions have been set, but a 'working group staff' user can not view clinical forms (can view demographics/consent forms). Affects both 1.7 and 2.0 versions.

**Comment by id2359** [comment]
Looks like this was explicitly done in the code to address: RDR-778 Working Group Staff have no access to forms from breadcrumbs

**Comment by id2359** [comment]
The ticket referred to seems to say: working group staff should _not_ be allowed to view clinical forms 
so can we get confirmation about what ophg  rules are in this case as we've been taked with undoing work we've previously actioned to do the exact opposite

**Comment by id2359** [comment]
closed behaviour was correct
