### ISSUE TITLE
Internationalisation / translation functionality

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#399]
Some progress was made previously: https://github.com/muccg/fkrp/issues/4

**Comment by id2359** [comment]
re-extracted messages into po file ( still incomplete)
cat'ed my fkrp.po as a test
compiledmessages in django:

CommandError: Execution of msgfmt failed: /app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:951: duplicate message definition...
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:436: ...this is the location of the first definition
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:954: duplicate message definition...
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:929: ...this is the location of the first definition
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:972: duplicate message definition...
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:938: ...this is the location of the first definition
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:978: keyword "label" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:978:171: syntax error
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:997: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:996: missing 'msgstr' section
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:997:3: syntax error
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:997: keyword "you" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:998: keyword "If" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:999: keyword "If" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1000: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1234: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1233: missing 'msgstr' section
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1234:9: syntax error
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1234: keyword "with" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1235: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1462: duplicate message definition...
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:715: ...this is the location of the first definition
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1576: keyword "no" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:1576:66: syntax error

**Comment by id2359** [comment]
modified script to skip thosemsgids  in supplied po file:
still errors:

CommandError: Execution of msgfmt failed: /app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:34: keyword "label" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:34:171: syntax error
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:53: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:52: missing 'msgstr' section
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:53:3: syntax error
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:53: keyword "you" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:54: keyword "If" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:55: keyword "If" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:56: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:290: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:289: missing 'msgstr' section
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:290:9: syntax error
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:290: keyword "with" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:291: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:629: keyword "no" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:629:66: syntax error
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:666: end-of-line within string
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:667: keyword "If" unknown
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:665: missing 'msgstr' section
/app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:667:3: syntax error

**Comment by id2359** [comment]
first issue is embedded quotes in messages which are in effect turned into keywords/unquoted

CommandError: Execution of msgfmt failed: /app/rdrf/rdrf/locale/ar/LC_MESSAGES/django.po:34: keyword "label" unknown
34 msgid "LGMD2I is generally classed as the adult form and MDC1C as the early childhood form of FKRP-related muscular dystrophy. For the purposes o     f the registry the "label" is not as important as knowing that your condition is caused by a genetic change in the FKRP gene (see next question f     or more details)."

**Comment by id2359** [comment]
Another issue is multiline messages

**Comment by id2359** [comment]
Following messages are being extracted with "bad" format strings that cause a compilation error:

msgid "Patient with id %s not found!"
msgid "Adjudication Definition %s not found"
msgid "Unknown adjudication state '%s' - contact admin"
msgid "Could not find user for %s: %s"
msgid "Could not find user for %s"
msgid "There is no working group called %s"
msgid "Adjudication Error: %s"
msgid "Cannot submit adjudication - adjudication request with id %s not found"
msgid "Could not find requesting user for this adjudication '%s'"
msgid "No one has responded to the adjudication request yet!- stats are %s"
msgid "Adjudication Definition with id %s not found"
msgid "Unknown adjudication state: %s"
msgid "Your adjudication decision has been sent to %s"
msgid "Your adjudication decision was not communicated: %s"
msgid "Exon validation error: %s"
msgid "Protein validation error: %s"
msgid "Sequence validation error: %s"
msgid "Unknown ValidationType %s"

**Comment by id2359** [comment]
Also to do:


Patient listing columns
Quicklinks
The Add new patient screen patient fields

**Comment by id2359** [comment]
I've updated the format strings for the above.

For the ones mentioning adjudications:
We should (probably) delete any msg blocks mentioning adjudications in the po file as they are not used by any existing registries anyway, so getting translators to provide translations is a waste of their time:

e.g.

105 #: rdrf/rdrf/form_view.py:1553
 106 #, python-format
 107 msgid ""
 108 "Could not create adjudication request object for %(target_user)s: %(ex)s"
 109 msgstr "FOOBAR %(target_user)s foobar fooobar %(ex)s baz"

**Comment by id2359** [comment]
All user facing pages done for base RDRF -

**Comment by id2359** [comment]
Embedded HTML in the translations ain't workin' - looking at it

**Comment by id2359** [comment]
Some tests were broken, fixed them
