### ISSUE TITLE
Affecting 2.0.1 : delete_file_wrapper() missing 1 required positional argument: 'file_ref'

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#416]
to recreate:

Upload a file to file cd in clinical form
Save Form
Known bug- file link does not appear upon Form save https://github.com/muccg/rdrf/issues/291
Press 'refresh in browser'
TypeError occurs

Note, if you navigate to another Form after Form save, then navigate back to initial Form, file link is present. Error only seems to appear when refreshing browser after initial Form save.

TypeError at /fh/forms/46/558/236
delete_file_wrapper() missing 1 required positional argument: 'file_ref'
Request Method:	POST
Request URL:	https://rdrf.ccgapps.com.au/ophg/fh/forms/46/558/236
Django Version:	1.10.5
Exception Type:	TypeError
Exception Value:	
delete_file_wrapper() missing 1 required positional argument: 'file_ref'
Exception Location:	/app/rdrf/rdrf/dynamic_data.py in handle_file_upload, line 593
Python Executable:	/env/bin/uwsgi
Python Version:	3.5.2
Python Path:	
['.',
 '/app',
 '/app/rdrf',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/env/lib/python3.5/site-packages']
Server time:	Fri, 24 Feb 2017 15:03:52 +0800
Traceback Switch to copy-and-paste view

/env/lib/python3.5/site-packages/django/core/handlers/exception.py in inner
            response = get_response(request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _legacy_get_response
            response = self._get_response(request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/views/generic/base.py in view
            return self.dispatch(request, *args, **kwargs) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/views/generic/base.py in dispatch
        return handler(request, *args, **kwargs) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/utils/decorators.py in _wrapper
            return bound_func(*args, **kwargs) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/contrib/auth/decorators.py in _wrapped_view
                return view_func(request, *args, **kwargs) ...
▶ Local vars
/env/lib/python3.5/site-packages/django/utils/decorators.py in bound_func
                return func.__get__(self, type(self))(*args2, **kwargs2) ...
▶ Local vars
/app/rdrf/rdrf/form_view.py in post
                section_info.save_to_mongo() ...
▶ Local vars
/app/rdrf/rdrf/form_view.py in save_to_mongo
                                                   index_map=self.index_map) ...
▶ Local vars
/app/rdrf/rdrf/dynamic_data.py in save_dynamic_data
        self._update_files_in_gridfs(record.data, registry, form_data, index_map) ...
▶ Local vars
/app/rdrf/rdrf/dynamic_data.py in _update_files_in_gridfs
                                                              existing_record, index_map) ...
▶ Local vars
/app/rdrf/rdrf/dynamic_data.py in update_multisection_file_cdes
                    new_val = DynamicDataWrapper.handle_file_upload(registry_code, key, value, existing_value) ...
▶ Local vars
/app/rdrf/rdrf/dynamic_data.py in handle_file_upload
            filestorage.delete_file_wrapper(to_delete) ...
▶ Local vars

**Comment by knapier** [comment]
If #291 can be addressed, this issue shouldn't need to be fixed.

**Comment by id2359** [comment]
Fixed in #421
