### ISSUE TITLE
Demographic fields- when a date field is configured to be 'hidden', instruction text still appears.

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#417]
For example, the 'date of migration' field (between date of birth and country of birth) is configured to be hidden for working group curator users. Instruction text of 'yyyy-mm-dd' still appears.

<img width="1006" alt="screen shot 2017-02-27 at 4 14 54 pm" src="https://cloud.githubusercontent.com/assets/17611855/23353917/cab618cc-fd09-11e6-915f-5e01f6e9f6e4.png">

**Comment by id2359** [comment]
Fixed in the hiddenfieldsintructions branch
