### ISSUE TITLE
2.0.1 Custom user inactive status message typo 

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#420]
“Too many failed login attemtps”

Should be "Too many failed login attempts”

**Comment by id2359** [comment]
Error is in the migrations within django useraudit - see https://github.com/muccg/django-useraudit/issues/22

we'll need to bump our version of django useraudit when fixed to close this ticket

**Comment by id2359** [comment]
I've updated base RDRF to use 1.5.3 as 1.5.2 contained a mistake
