### ISSUE TITLE
Consent page- upload consent file: deletion of multisection deletes uploaded file but does not delete section

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#425]
Saving of the page after deleting the mutiection says 'pateint saved successfully', but red error message appears below 'deleted' multisection (that has the uploaded file deleted but multisection remains).

* Select a valid choice. That choice is not one of the available choices.

Affects 2.0.1-2.0.3

**Comment by id2359** [comment]
Replicated on FH
Add 1 file save f1
Add another file and save f2
links for both files are visible only after navigating from the page and back again ( to trigger the get view)
mark f1 for deletion 
the "section" is deleted but the mark for deletion checkbox shows and is checked

**Comment by knapier** [comment]
Note, was introduced in v2 (testing on v1.7.14 works as expected).

**Comment by id2359** [comment]
We caused this by removing  a redirect to the get view ( which was preventing a success message from being displayed to the user ) - the originating  POST view does not build the response properly 

Looking into using SuccessMessageMixin

**Comment by id2359** [comment]
Fix just needed to put back redirect and add call  messages api


Fixed #426 also
