### ISSUE TITLE
Find a (better) way of translating embedded html in yaml data

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#441]
Find a way of translating embedded html in yaml cde data that doesn't require breaking up the html into textual fragments.

**Comment by id2359** [comment]
Internationalisation branch allows for translations of embedded html by breaking the textual strings out and then recombining them - but this has the side effect of creating msgids which are small fragments so translators will find it difficult to suppky coherent translations.

**Comment by id2359** [comment]
Need to try:
a custom loader

e.g in template


{% include 'some path specifier for a cde informaton text" }

**Comment by id2359** [comment]
Added a template loader and modded settings naively: get this error: 

ERRORS:
runserver_1   | ?: (templates.E001) You have 'APP_DIRS': True in your TEMPLATES but also specify 'loaders' in OPTIONS. Either remove APP_DIRS or remove the 'loaders' option.

**Comment by aahunter** [comment]
@id2359 set APP_DIRS to False. Then set loaders to:

'django.template.loaders.filesystem.Loader'
'django.template.loaders.app_directories.Loader'

... plus your own custom loader
