### ISSUE TITLE
Email notification improvements

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#447]
Currently resend functionality resends to all recipients which is too coarse-grained and the admin gui doesn't give enough info to clearly indicate who will receive the resend.

**Comment by knapier** [comment]
Currently it's not clear to which users emails are being sent to: For example, at registration, 2 emails are triggered, one to the curator, and one to the user who has registered. These are both denoted by 'new patient', but it is not clear which email is sent to which user- hence 'resend email' is not useful.

![screen shot 2017-08-16 at 3 13 04 pm](https://user-images.githubusercontent.com/17611855/29351487-7cd89ece-8295-11e7-8e7d-7a9801a909ea.png)
![screen shot 2017-08-16 at 3 13 13 pm](https://user-images.githubusercontent.com/17611855/29351488-7cde902c-8295-11e7-8aff-d35addbdbd0f.png)
