### ISSUE TITLE
update fix_modjgo_dates for divergent history records

### ISSUE THREAD

**Issue by aahunter** [muccg/rdrf#459]
Related internal ops issue https://github.com/muccg/ops/issues/1224

**Comment by id2359** [comment]
The script ran successfully but it didn't actually update any timestamps.

Looking at the records, I can see that they are correctly structured, but I  can see form timestamps like this:
"%s_timestamp": "2016-07-18T12:40:42.766000",
which looks like failure of string interpolation

**Comment by id2359** [comment]
I've checked the staging sites and all history objects have correct  form timestamp keys

**Comment by id2359** [comment]
There's an error in the clinical form expression which explains the malformed key

**Comment by id2359** [comment]
This is not actually preventing history being populated

**Comment by id2359** [comment]
Closing as invalid but we should implement #466
