### ISSUE TITLE
Improve consistency in ordering of context form groups

### ISSUE THREAD

**Issue by aahunter** [muccg/rdrf#460]
reported by KN:

Context form group ordering is set by 'name' which is set by the CDE FollowUp/FHFollowUp/DateOfAssessment .

The order displays correctly in the 'module' listing within a patient's record, but the order is not maintained in the patient listing, or when forms are navigated through by clicking the 'next' arrow (looks like ordering is defaulting to date of form creation instead of by name).

**Comment by schangccg** [comment]
Created a PR to address this issue.

**Comment by id2359** [comment]
This has been fixed in sam's pr

**Comment by knapier** [comment]
The order is now maintained when forms are navigated through by clicking the 'next' arrow.

However, the order is not maintained in the patient listing when clicking 'Follow Ups'

**Comment by id2359** [comment]
Refactored to allow consistent ordering in the nav wizard and the patients listing
