### ISSUE TITLE
export : Section matching query does not exist.

### ISSUE THREAD

**Issue by aahunter** [muccg/rdrf#462]
Error in export of FH Registry: Section matching query does not exist.

Attempting to export yaml from live FH registry, and come across this error:

"Error in export of FH Registry: Section matching query does not exist."

https://fhregistry-international.com/

A new form with 2 new CDEs and 1 new section was added to the live registry, hence the update to the registry version and yaml export.

**Comment by id2359** [comment]
from the log:
Lee Render [2:55 PM] 
"[ERROR:2017-06-29 14:47:59,368:exporter.py:386:_get_cdes_for_sections] No Section with code: FHPaid
" in fh live  Is FHPaid the correct code
