### ISSUE TITLE
notifications: email notifications of account lockout

### ISSUE THREAD

**Issue by aahunter** [muccg/rdrf#463]
Multiple reports of account lockout notifications not being sent/received.

**Comment by id2359** [comment]
The base code explicitly prevents it? ( I'm not sure why)

in settings.py:
```python
    registry_code = getattr(settings, "FALLBACK_REGISTRY_CODE", None)

    if registry_code:
        process_notification(
            registry_code, EventType.ACCOUNT_LOCKED, template_data)
    else:
        logger.debug(
            "No settings.FALLBACK_REGISTRY_CODE- no notifications sent")
```

**Comment by id2359** [comment]
FALLBACK_REGISTRY_CODE is being set in mtm, angelman, fkrp settings but not in base rdf.

We'll need to refactor the code to get it to work on base RDRF deployments.

**Comment by id2359** [comment]
I've altered the handler to not rely on settings like this, but instead look at the user object directly to get at the registry(s)

**Comment by id2359** [comment]
signal handler connects signal on site start OK
handler called OK
but seeing [ERROR:2017-06-30 10:50:28,557:email_notification.py:66:send] Email has failed to send
runserver_1   | Traceback (most recent call last):
runserver_1   |   File "/app/rdrf/rdrf/email_notification.py", line 56, in send
runserver_1   |     send_mail(email_subject, email_body, self.email_notification.email_from, [recipient], html_message=email_body)
runserver_1   |   File "/env/lib/python3.6/site-packages/django/core/mail/__init__.py", line 62, in send_mail
runserver_1   |     return mail.send()
runserver_1   |   File "/env/lib/python3.6/site-packages/django/core/mail/message.py", line 342, in send
runserver_1   |     return self.get_connection(fail_silently).send_messages([self])
runserver_1   |   File "/env/lib/python3.6/site-packages/anymail/backends/base.py", line 86, in send_messages
runserver_1   |     sent = self._send(message)
runserver_1   |   File "/env/lib/python3.6/site-packages/anymail/backends/base_requests.py", line 56, in _send
runserver_1   |     return super(AnymailRequestsBackend, self)._send(message)
runserver_1   |   File "/env/lib/python3.6/site-packages/anymail/backends/base.py", line 116, in _send
runserver_1   |     response = self.post_to_esp(payload, message)
runserver_1   |   File "/env/lib/python3.6/site-packages/anymail/backends/base_requests.py", line 77, in post_to_esp
runserver_1   |     self.raise_for_status(response, payload, message)
runserver_1   |   File "/env/lib/python3.6/site-packages/anymail/backends/base_requests.py", line 88, in raise_for_status
runserver_1   |     raise AnymailRequestsAPIError(email_message=message, payload=payload, response=response)
runserver_1   | anymail.exceptions.AnymailRequestsAPIError: Sending a message to lrender@ccg.murdoch.edu.au from no-reply@mg.ccgapps.com.au
runserver_1   | ESP API response 401: Forbidden

**Comment by id2359** [comment]
Tried with same api key that I know works with mtm  and still get error so I suspect in base rdrf env value not propagated ..

**Comment by id2359** [comment]
mailgun api and server name env vars weren't added to .env file
