### ISSUE TITLE
Invalid email address username message not translated because coming from Jquery

### ISSUE THREAD

**Issue by schangccg** [muccg/rdrf#469]
When registering for Angelman or FKRP, if the user does not enter an email address, the string "Please enter a valid email address." appears under the text input field.

This string is not in the .html template or .js code or yaml file but is found in the files:
jquery.validate.min.js and
jquery.validate-1.13.1.min.js

Opening a ticket as discussed with Lee.

**Comment by id2359** [comment]
Issue is we can't provide translations because the string is not exposed in our app
