### ISSUE TITLE
Allow full family linkage behaviour for any registry with the feature string

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#488]
Currently this is restricted to FH even though the behaviour is meant to be triggered by having the feature 'family_linkage' in the registry metadata.

See rdrf-ccg #857 

This behaviour is required for Rare Lipid registry

**Comment by id2359** [comment]
Original motivating question https://github.com/muccg/rdrf-ccg/issues/857

**Comment by id2359** [comment]
Jettisoned the system cde idea as too complicated. Am now using a signal handler and some metadata in the registry model to update family linkage behaviour.

**Comment by id2359** [comment]
The metadata for a registry with family linkage now has to include additional information like this:

`{"features": ["contexts","family_linkage"],
 "family_linkage_form_name": "ClinicalData",
"family_linkage_section_code": "fhDateSection",
"family_linkage_cde_code": "CDEIndexOrRelative",
"family_linkage_index_value": "fh_is_index",
"family_linkage_relative_value": "fh_is_relative"
}`

**Comment by id2359** [comment]
NB. The same config will need to be added to the FH registry metadata  - FH will have to be regression tested as part of the testing for this ticket.

**Comment by id2359** [comment]
NB In the registry metadata:
{"features": ["contexts","family_linkage"], "family_linkage_form_name": "ClinicalData", "family_linkage_section_code": "fhDateSection", "family_linkage_cde_code": "CDEIndexOrRelative", "family_linkage_index_value": "fh_is_index", "family_linkage_relative_value": "fh_is_relative" }


The index value and relative value are coming whatever the definition of the registry defines them to be  (the current rare lipid uses the fh value codes which is ok ) Ideally we'd want re-usable cdes that are not tied to one particular registry

**Comment by knapier** [comment]
@id2359 - Thanks- do I need to update FH's registry metadata too, or it's not necessary as it was designed for FH in the first place?

**Comment by id2359** [comment]
No , it has to be added to FH also
