### ISSUE TITLE
Navigation through forms is not respecting patient_types form applicability

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#491]
When logged in as a parent or patient user, the navigation arrows on the form view are not respecting the list of applicable forms for that user. For example:

CarrierAdditionalInformation has position 5
DeceasedAdditionalInformation has position 6

Form applicability is set:
"patient_types": {
"deceased":  {"forms" : [ "DeceasedAdditionalInformation"], "name": "Deceased Patient"},
"carrier": {"forms": ["CarrierAdditionalInformation"], "name": "Female Carrier"}

When a parent or patient user reaches the end of their applicable forms (position 4), the arrows attempt to reach the next form in position 5. This triggers an error.

Patient user: 'Looks like you don't have access to this page ...' 
Parent user: 'You don't have permissions to view patient data'

The navigation should follow the module listing.

**Comment by id2359** [comment]
Fixed in 3.0.0 in another ticket
