### ISSUE TITLE
Notify users that their password is about to expire in X days

### ISSUE THREAD

**Issue by sztamas** [muccg/rdrf#504]
There are hooks for this in muccg/django-useraudit but they aren't set up in rdrf projects.
It will be an improvement to notify users before they password will expiry so they can change it instead of just being locked out.

Notification should be at least email, maybe the UI can have a warning as well after login.

Original issue: muccg/rdrf-ccg#940

**Comment by sztamas** [comment]
Added both on screen warning and email notification.

**Comment by knapier** [comment]
@sztamas I am configuring password expiry emails for the live registries post 2.3.1 release-  how many days to password expiry is the trigger for the email to be sent?

**Comment by sztamas** [comment]
It is `30` days by default in base RDRF.

I think it would be better if you didn't hardcode that into the email.
I made a variable called `days_left` that you can use in the template. It will be set to the days you have left until your password will expire.

```
Your password will expire in {{ days_left }} days.
```
