### ISSUE TITLE
Set up password validators for all the registries

### ISSUE THREAD

**Issue by sztamas** [muccg/rdrf#514]
The registries that have different rules than base RDRF will have to have their own password validator configurations in their own settings file.

@knapier do you know the requirements for all the registries?

For MTM, based on the registration form, it is at least 6 character long and has to have at least 1 number.
Is that right?

How about the others?

**Comment by knapier** [comment]
Hi @sztamas 

Initially, we had no password rules.

MTM/FRKP requested at least 6 characters long and 1 number, which was implemented on the registration page for MTM/FKRP/Angelman.

FH requested stronger password rules. FH does not use registration, so a different rule was implemented in base RDRF.

If MTM/FKRP/Angelman users change their password via 'password reset', they need to follow the stronger password rules.

**Comment by knapier** [comment]
For consistency, we could apply the base RDRF password rules across all registries. We would need to update registration page text though for MTM/FKRP/Angelman.

**Comment by sztamas** [comment]
I've just set up the following rules in base RDRF:
  * at least 8 character long
  * can't be a common password (common password list supplied by Django)
  * must have at least 1 uppercase letter
  * must have at least 1 lowercase letter
  * must have at least 1 number
  * must have at least 1 special character

Let me know if this is sensible or you need something to be changed.
We will have to go through all the registries and make sure that their registration page is in line with these rules.

The "password reset" and new "change password" functionality uses these rules already.
