### ISSUE TITLE
V.2.3.0 testing questions and notes

### ISSUE THREAD

**Issue by knapier** [muccg/rdrf#519]
1.  Are account lock out emails now redundant? (They are not sending from rdrf  when triggered. User is notified from 'trouble signing in?').

2. FH curator workflow: Jing sets up new curator account, and sends link to 'change my password' so users can set their own password. She will now have to send a link to: 'https://rdrf.ccgapps.com.au/ophg/login_assistance/

3. Password expiry email notifications can be set- what about account expiry?

**Comment by sztamas** [comment]
1. Do you mean we should remove it? I think there is still value in sending out those emails when an account is locked.

2. OK. That might be a problem. That login assistance functionality currently works just for patients and parents not "system users". The password reset url is still there (`REGISTRY_URL/password_reset`), but I removed the menu item from the banner to it. Do they send out the link to the page that requires the users to put in their email address or the email with password reset link directly?

3. That isn't supported yet in `django-useraudit` so if you need it, it has to be a new feature request.

**Comment by knapier** [comment]
Hi @sztamas 
1. No, I agree and think the emails should still send- but they are not. I'll raise a bug ticket.

2. Jing sends send an email with the link that requires them to put in their email address, they then change their password. As long as the url is still available, this should be fine, I'll just need to communicate this to Jing.

3. Ok. Let's chat to determine if this is required :)

**Comment by id2359** [comment]
Url is still available and works from my local testing.

**Comment by knapier** [comment]
I'm having trouble accessing the url from staging, but it could be due to multiple registries defined on staging?

When trying: 
https://rdrf.ccgapps.com.au/ophg/password_reset

'Oops, wrong registry code...'

When trying: https://rdrf.ccgapps.com.au/ophg/fh/password_reset

Request Method: | GET
-- | --
https://rdrf.ccgapps.com.au/ophg/fh/password_reset


Request Method: | GET
-- | --
https://rdrf.ccgapps.com.au/ophg/fh/password_reset
