### ISSUE TITLE
Logo  for PROMS system

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#657]

**Comment by aminur80** [comment]
To allow logo at PROMS (Survey start page):
- add environment variable PROMS_LOGO with relative path to the logo image

**Comment by aminur80** [comment]
Actual Values:
      - PROJECT_LOGO=/images/cic_logo.png
      - PROJECT_LOGO_LINK=https://www.ciccancer.com
      - PROJECT_TITLE=
      - PROMS_LOGO=/images/proms_logo.png
