### ISSUE TITLE
Logo for Clinical System

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#658]

**Comment by aminur80** [comment]
The new changes will require the following as part of environment variable - 
PROJECT_TITLE 
PROJECT_LOGO 
PROJECT_LOGO_LINK

Example: 
 - PROJECT_LOGO=<path_to the logo image> 
                      sample:  /images/dummy_logo.png
 - PROJECT_LOGO_LINK=<https link to external url> 
                      sample: https://www.google.com
 - PROJECT_TITLE=<project_title>

All these can be left empty as well

**Comment by aminur80** [comment]
Actual Values:
- PROJECT_LOGO=/images/cic_logo.png
- PROJECT_LOGO_LINK=https://www.ciccancer.com
- PROJECT_TITLE=
- PROMS_LOGO=/images/proms_logo.png
