### ISSUE TITLE
Wrong value in precondition at smap survey

### ISSUE THREAD

**Issue by aminur80** [muccg/rdrf#660]
Precondition is not working properly for some questions in smap survey due to the reason that the condition itself contains invalid value from original question.
Existing value in precondition - 
48: Do you have a stoma bag (colostomy/ileostomy) (please select the correct answer)>>2
Expected value in precondition - 48: Do you have a stoma bag (colostomy/ileostomy) (please select the correct answer)>>0

**Comment by id2359** [comment]
Error was in the precondition configuration  where the position value of 2 was used in place of the code value representing True ( which, oddly, is 0.)
