### ISSUE TITLE
Make survey questions non mandatory

### ISSUE THREAD

**Issue by aminur80** [muccg/rdrf#678]
Currently the Questions in the survey need to be answered, otherwise user cannot proceed to the next one. The user should be allowed not to answer a question and proceed to the next one.

NB. This was the original behaviour and users have flipped back so it should be matter of removing the checks we added.

**Comment by id2359** [comment]
Aminur suggested this link: This might be a useful reading - https://www.surveymonkey.com/curiosity/make-survey-questions-required/
