### ISSUE TITLE
Bug: Patients from other registry is visible to genetic user even when the right registry is not selected in Patient listing

### ISSUE THREAD

**Issue by aminur80** [muccg/rdrf#734]
**Description:**
Application gives error in the browser when clicking on a Patient from ICHOM registry as genetic user while selecting FH Registry in the Patient Listing.

**Steps to reproduce:**
1) Login as Admin in the system
2) Go to Admin Page and choose Users
2) select user **genetic** 
3) Multi select the following working group - 
- fh Royal Perth Hospital
- fh Wesley Medical Center
- ICHOMCRC RPH
4) Multi select the following registry - 
- FH Registry(fh)
- ICHOM Cholorectal Cancer
5) **Save** the record
6) Login as genetic user using **genetic**/**genetic**
7) Go to Patient Listing and select the registry from FH Registry dropdown
8) Patient from ICHOM Registry is visible
9) Click the patient from ICHOM Registry
10) See the **error** in the browser
``
builtins.AttributeError
AttributeError: 'NoneType' object has no attribute 'working_groups'
``

**Expected Result:**
Patient from ICHOM registry should not be visible.

**Comment by id2359** [comment]
Please create another ticket don't put two issues in one ticket if they are not related
