### ISSUE TITLE
"ISO compliance"

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#742]
I found a remark in linked documents below saying compliance involved not exposing unused use cases.

So one gesture to compliance is:

Hide irrelevant links/admin models based when site is used as a PROMS site - base RDRF still exposes far too many pieces of irrelevant functionality 

we need to minimise risk that any PROMS functionality is disrupted due to any of the irrelevant pages being landed on / accessed.

This ticket is pretty open-ended: I suggest we limit the use cases on the PROMS site. 

Produce a "plan" first with your idea of how to implement it, and then we can evaluate it.

**Comment by id2359** [comment]
CAR links to
http://gcio.wa.gov.au/
which points to
 https://www.wa.gov.au/agency/office-of-digital-government
which lists a number of potentially relevant policies

https://www.wa.gov.au/government/publications/digital-security-controls-checklist

**Comment by aminur80** [comment]
Plan:
- Add a new environment variable named - **proms_site** which has value [0, 1]
 1 - Proms site is Active
 0 - Proms site is Inactive
- Retrieve that environment in settings.py
 `PROMS_SITE = env.get('proms_site', False)`
- inside the admin.py register only those that are relevant to Proms Site by checking settings.PROMS_SITE

**Comment by aminur80** [comment]
Updated Plan:
- add a new environment variable named **SYSTEM_ROLE** which may contain string value such as CIC_PROMS or CIC_CLINICAL
- Retrieve that environment in settings.py
- inside admin.py create a enumerated class with values  CIC_CLINICAL, CIC_PROMS and register only  those that are relevant to SYSTEM_ROLE

**Comment by aminur80** [comment]
Value allowed as **SYSTEM_ROLE**:
CIC_PROMS
CIC_DEV
CIC_CLINICAL
NORMAL

NORMAL is defaulted if SYSTEM_ROLE does not exists
