### ISSUE TITLE
Copyright Text for CIC clinical system

### ISSUE THREAD

**Issue by aminur80** [muccg/rdrf#754]
- [x] Add copyright text/link for CIC Clinical system
- [x] Copyright page should have banner and be styled ( minimally to not stand out too much)

**Comment by aminur80** [comment]
Hi @id2359 
The idea of having copyright text or link to be available at clinical system can be achieved through use of CurrentSiteManager from django.contrib.sites.managers
1) Define a copyright model
class Copyright(models.Model)
     link = models.CharField(max_length=200)
     copyright_text = models.TextField(blank=True, null=True)
     site = models.ForeignKey(Site, on_delete=models.CASCADE)
     on_site = CurrentSiteManager()
2) Enabling the sites framework
- Add 'django.contrib.sites' to your INSTALLED_APPS setting.
- Define a SITE_ID settings:
  SITE_ID = 1
- Run migrate. 

3) Copyright.on_site.all() will return only copyright objects associated with current site, according to the SITE_ID settings

This way for clinical system, the copyright text or link is fetched using the site_id

** We can use this model also for PROMS system in a similar way

Any feedback is welcome

**Comment by id2359** [comment]
[2019-1-23 Copyright text for PROMs (1).docx](https://github.com/muccg/rdrf/files/2843405/2019-1-23.Copyright.text.for.PROMs.1.docx)

**Comment by id2359** [comment]
I think one way to put in copyright text(s) for the clinical system is to iterate through the copyright text on the survey questions  and store any registry level copy right info into metadata.
