### ISSUE TITLE
Error issuing prod up locally

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#796]
./develop.sh up prod

Creating rdrf_uwsgiprod_1       ... error

_

> ERROR: for rdrf_uwsgiprod_1  Cannot start service uwsgiprod: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/app/docker-entrypoint.sh\\": stat /app/docker-entrypoint.sh: no such file or directory"'
> 
> ERROR: for uwsgiprod  Cannot start service uwsgiprod: b'oci runtime error: container_linux.go:247: starting container process caused "exec: \\"/app/docker-entrypoint.sh\\": stat /app/docker-entrypoint.sh: no such file or directory"'
> ERROR: Encountered errors while bringing up the project.
> UdevQt: unhandled device action "move"

_

**Comment by id2359** [comment]
This is happening on next_release

**Comment by id2359** [comment]
my bad - problem behind keyboard

**Comment by mouneyrac** [comment]
I am having problem behind keyboard too :)
