### ISSUE TITLE
UserChangeForm class is overiding the base Django class instead of extending it.

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#848]
This is causing the code to lose all code update on the base UserChangeForm class in Django.

PS: the current OldUserChangeForm should be called something like DjangoUserChangeForm (if we were keeping the overriding process instead of extending).

**Comment by mouneyrac** [comment]
This is related to #846

**Comment by id2359** [comment]
Fixed in RDRF 5.0.6
