### ISSUE TITLE
PROMS password breach mitigation 2: prevent deletion of surveyassignment models

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#855]
This can still be done in the backend ( at time pull proms api request handled ) - just not exposed as an action in the admin GUI

**Comment by mouneyrac** [comment]
A solution is to keep the current administration which allows editing/deleting. In production, the admin user has to be disabled from the backend (django-admin). So no user can log in the system but in case of trouble or if we want to update the proms later, we still can temporarily enable the admin user, do the required change, and disable it again.

This is the safest solution and the best one if the admin user usage is expected to be rare on the Proms system.

**Comment by mouneyrac** [comment]
Closing - the disable admin user feature is mentioned in the Google drive CIC folder under maintenance
