### ISSUE TITLE
New consent text at end of survey

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#861]
See the attached word document containing the revised consent text

**Comment by id2359** [comment]
[CRC follow up PROMS changes.docx](https://github.com/muccg/rdrf/files/3361000/CRC.follow.up.PROMS.changes.docx)

**Comment by mouneyrac** [comment]
Assigning to Lee as we need to update the PROMSconsent CDE in the admin interface.

**Comment by id2359** [comment]
We've updated the consent cde for this bit:
Consent
_Thank you for completing this survey. We realise that the information you have provided is personal and sensitive and so your confidentiality will be protected at all times. Only your doctor will have access to your individual information. Any use of your information for research purposes will only be in a non- identifiable, combined format._


Do we have the other bit below?



By ticking this box you: 
    • Give consent for the information you provide to be used for the CIC Cancer project; and 
    • Will receive a reminder when the next survey is due.

**Comment by mouneyrac** [comment]
Checkbox text updated (+ fixed a bug in the clean() function)
