### ISSUE TITLE
Duplicate instruction text in PROMS survey

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#863]
On Windows 10 Phone, Microsoft Edge built-in browser, survey accessed via QR code.
Instruction text for question EQ_Health_Rate "YOUR HEALTH TODAY" is duplicated, which causes the progress arrows, progress bar, and part of the health slider to be obscured. This makes it impossible to complete the survey beyond this question, and cannot navigate within the survey.

**Comment by id2359** [comment]
The instruction text on the EQ_Health_Rate cde is:

We would like to know how good or bad your health is TODAY.
This scale is numbered from 0 to 100.
100 means the best health you can imagine
0 means the worst health you can imagine
Please tap on the scale to indicate how your health is TODAY.



I have removed it on the proms

**Comment by id2359** [comment]
This means that the two yaml files diverge in more than just the registry metadata -
