### ISSUE TITLE
Repeat question in FollowUp PROMS survey

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#865]
FollowUp PROMS survey asks EORTCQLQC29_Q56 "To what extent were you interested in sex?" prior to asking CDEPatientSex "What is your gender?". EORTCQLQC29_Q56 is listed as a question for men only in the FollowUp PROMS populated page. 

If CDEPatientSex answered male, the next question asked is EORTCQLQC29_Q57 "Did you have difficulty getting or maintaining an erection?", which is correct, resulting in both "men-only" questions answered.

If CDEPatientSex answered female, the next question asked is EORTCQLQC29_Q58 "To what extent were you interested in sex?", the first of the questions listed as for women only, then asks EORTCQLQC29_Q59 "Did you have pain or discomfort during intercourse?", which is correct. This results in one of the "men-only" questions being answered, and both "women-only" questions answered, but the first women-only question (EORTCQLQC29_Q58) is a repetition of EORTCQLQC29_Q56.

![CIC_CRC_followup_female_rptq](https://user-images.githubusercontent.com/50615516/60702333-4cab0100-9f31-11e9-869d-1644787e21df.png)

**Comment by id2359** [comment]
The defintion has been changed on site system - we need to copy to proms

**Comment by id2359** [comment]
I've updated staging
