### ISSUE TITLE
Change to FH dutch lipid score calculation [done - awaiting #841 integration]

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#867]
Jing has requested a change to the calculation.

Spec:
See attached pdf

**Comment by id2359** [comment]
[SUWA Printi19071116150.pdf](https://github.com/muccg/rdrf/files/3390884/SUWA.Printi19071116150.pdf)

**Comment by id2359** [comment]
![unnamed](https://user-images.githubusercontent.com/1163895/61196366-d1033e00-a700-11e9-8ab6-4d0318702fa3.png)

**Comment by id2359** [comment]
From Jing: As discussed, I have attached the paper, please see the footnote in Table 1.
It says that “per group” should have “only one score, the highest applicable”….. eg, “the highest score for family history is 2”…..

**Comment by mouneyrac** [comment]
done - awaiting for #841 to be integrated so we can merge this fix.
