### ISSUE TITLE
Validation error updating calculation for FH dutch lipid network score ( phenotypic)

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#883]
Couldn't execute /env/lib/python3.6/site-packages/rdrf/scripts/check-calculation.js: [Errno 2] No such file or directory: '/env/lib/python3.6/site-packages/rdrf/scripts/check-calculation.js': '/env/lib/python3.6/site-packages/rdrf/scripts/check-calculation.js'

**Comment by id2359** [comment]
We will need to update via the backend

**Comment by id2359** [comment]
This occurs in the admin interface but not when a cde is saved via the backend ( django-admin shell_plus)

**Comment by mouneyrac** [comment]
what are the steps to reproduce?
