### ISSUE TITLE
[POEM] calculated field: score error 

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#900]
Web service returns "Unscored" - when all  data filled in

--------------------------------------------------------------------------------------------------------------------------
Testing instructions 
--------------------------------------------------------------------------------------------------------------------------
**Test case reference**
[TO BE EDITED by anyone who knows the related test case - example: TC-RDRF-1]

**Environment:** 
staging poems

**Steps:**
1- Go to poems proms page
2- Check that the final score respect all different values of the specification

**Expected Result:**
all values should match the specs

**QA result:**
[TO BE EDITED BY QA TESTER] Passed/Failed  / Comment about failure / QA tester name / Date

**Comment by id2359** [comment]
changing field in the front end trigger web service call but the value  is wrong?

**Comment by gmaloneccg** [comment]
Results for POEM PROMS survey test, 16th August;
[20190816 POEM PROMS survey.ods](https://drive.google.com/open?id=1WtLajhV2Q5fI7uPBeKGZMYqf8NTl2h-V)

**Comment by mouneyrac** [comment]
Score appears as “UNSCORED”, suggesting “counts” not correctly assigned.

**Comment by mouneyrac** [comment]
I got it working but I have suspicious of the original code:

```
var DAYS0 = "NoDays";
var  DAYS1TO2 = "1to2Days";
var  DAYS3TO4 = "3to4Days";
var  DAYS5TO6 = "5to6Days";
var  EVERYDAY = "EveryDay";

function convert(val) {
    switch (val) {
        case DAYS0:
            return 0;
        case DAYS1TO2:
            return 1;
        case DAYS3TO4:
            return 2;
        case DAYS5TO6:
            return 3;
        case EVERYDAY:
            return 4;
        default:
            return 0;
    }
}

function getQ(cde) {
    try {
       return convert(cde);
    }
    catch (err) {
        return 0;
    }

}

function sum(arr) {
    var total = 0;
    for (var i = 0; i < arr.length; i++) {
        total += arr[i];
    }
    return total;
}

function getCategory(score) {
    if (score <= 2)
        return "Clear or almost clear";
    if (score <= 7)
        return "Mild eczema";
    if (score <= 16)
        return "Moderate eczema";
    if (score <= 24) {
        return "Severe eczema"
    }
    if (score <= 28) {
        return "Very severe eczema";
    }
    return "";
}

// Can't use eval ..
var q1 = context.poemQ1;
var q2 = context.poemQ2;
var q3 = context.poemQ3;
var q4 = context.poemQ4;
var q5 = context.poemQ5;
var q6 = context.poemQ6;
var q7 = context.poemQ7;


var answers = [getQ(q1), getQ(q2), getQ(q3), getQ(q4), getQ(q5), getQ(q6), getQ(q7)];
var counts = {};

for (var i = 0; i < answers.length; i++) {
    var answer = answers[i];
    counts[answer] = counts[answer] ? counts[answer] + 1 : 1;
}

var s = 0;
var cat = "";


if (counts[0] == 1) {
    s = sum(answers);
    cat = getCategory(s);
    context.result = s.toString() + " ( " + cat + " )";

}
else if (counts[0] >= 2) {
    context.result = "UNSCORED";
}
else {
    s = sum(answers);
    cat = getCategory(s);
    context.result = s.toString() + " ( " + cat + " )";
}
```

Two problems:
1- we can never display "Clear or almost clear"
2- the first "if (counts[0] == 1) {" make no sens as the last else produce the exact same result.

**Comment by mouneyrac** [comment]
After thinking - I am guessing the code was supposed to accept unanswered question up to 1, and still score it?

**Comment by gmaloneccg** [comment]
Passed 60 randomised-input tests. [Test result in Google Drive.](https://drive.google.com/open?id=1OSW-n5C_tohEizmYLOJ2oBOUynFq29at)
