### ISSUE TITLE
POEM PROMS survey title text not shown

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#903]
When opening the POEM PROMS survey, the title page of the survey displays the header "Survey" and the subtitle "None". The rest of the survey appears to be normal.
[Test result in Google Drive.](https://drive.google.com/open?id=1WtLajhV2Q5fI7uPBeKGZMYqf8NTl2h-V)

**Comment by mouneyrac** [comment]
It is true it is pretty empty:

![POEM survey first page](https://user-images.githubusercontent.com/354908/63252856-35d32a80-c2a3-11e9-8194-41d9b1a74d39.png)


What should we write? Maybe the client wants to have a say?

**Comment by mouneyrac** [comment]
I suggest:

Title: 

Poem Score Survey

Subtitle:

This survey helps us to understand how the eczema your child are experiencing impacts her/him. The information you provide will help your child health team to provide care that better meets her/his individual needs. What you tell us will also help to improve care for other children who undergo medical treatments in the future.

PS: assigning to Lee as it needs to be changed in the metadata.
