### ISSUE TITLE
Email Notification Historys: Resend is not url formatted

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#906]
![Resend url is not url formatted](https://user-images.githubusercontent.com/354908/63320011-d5012c00-c34e-11e9-9088-58e85e18e417.png)

**Comment by mouneyrac** [comment]
also remove the last s of Hisorys if possible (probably a django plural stuff)

**Comment by gmaloneccg** [comment]
Successful 20190902 11:24am. Resend option now appears as a button.
