### ISSUE TITLE
504 Gateway Timeout when attempting to view FH Report

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#914]
In explorer page in FH registry, selecting to view "FH Report" results in 504 Gateway Timeout error.

[FH Explorer page.](https://rdrf.ccgapps.com.au/ophg/explorer/)

**Comment by id2359** [comment]
docker logs:
[DEBUG:2019-08-21 15:16:22,197:middleware.py:25:process_request] ['/ophg/account/login', '/ophg/account/two_factor/setup', '/ophg/account/two_factor/qrcode', '/ophg/logout', '/ophg/translations/jsi18n/']
[DEBUG:2019-08-21 15:16:22,264:utils.py:339:wrapper] drop_table time = 0:00:00.034465 secs
[DEBUG:2019-08-21 15:16:22,285:utils.py:339:wrapper] create_cursor time = 0:00:00.020611 secs
[DEBUG:2019-08-21 15:16:22,289:utils.py:339:wrapper] _get_sql_metadata time = 0:00:00.003708 secs
[DEBUG:2019-08-21 15:16:22,323:utils.py:339:wrapper] _get_mongo_metadata time = 0:00:00.033736 secs
[INFO:2019-08-21 15:16:22,326:reporting_table.py:245:report] CLINICAL COLUMN 0 column_45_12_DateOfAssessment
[INFO:2019-08-21 15:16:22,326:reporting_table.py:245:report] CLINICAL COLUMN 1 column_45_12_fhAgeAtAssessment
[INFO:2019-08-21 15:16:22,327:reporting_table.py:245:report] CLINICAL COLUMN 2 column_45_12_CDEIndexOrRelative
[INFO:2019-08-21 15:16:22,327:reporting_table.py:245:report] CLINICAL COLUMN 3 column_45_7_CDEfhDutchLipidClinicNetwork
[INFO:2019-08-21 15:16:22,327:reporting_table.py:245:report] CLINICAL COLUMN 4 column_45_7_CDE00024
[DEBUG:2019-08-21 15:16:22,327:utils.py:339:wrapper] create_columns time = 0:00:00.004308 secs
[DEBUG:2019-08-21 15:16:22,331:utils.py:339:wrapper] drop_table time = 0:00:00.003884 secs
[DEBUG:2019-08-21 15:16:22,364:utils.py:339:wrapper] create_table time = 0:00:00.025641 secs
[DEBUG:2019-08-21 15:16:22,365:utils.py:339:wrapper] generate_results time = 0:00:00.000054 secs
[DEBUG:2019-08-21 15:18:33,571:middleware.py:25:process_request] ['/ophg/account/login', '/ophg/account/two_factor/setup',

**Comment by id2359** [comment]
We've addressed this by speeding up the report.
