### ISSUE TITLE
ProgrammingError when attempting to download FH report

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#915]
In explorer page in FH registry, selecting to download "FH Report" results in ProgrammingError traceback message.

[Error message text: 20190821 FH Report ProgrammingError.docx](https://github.com/muccg/rdrf/files/3524104/20190821.FH.Report.ProgrammingError.docx)

**Comment by mouneyrac** [comment]
From memory, this has been fixed since last August. It is working on staging.
