### ISSUE TITLE
Missing calculated fields for angelman

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#921]
- [x] ANGBMImetric

- [x] ANGBMIimperial

- [x] ANGCurrentPatientAge

**Comment by gmaloneccg** [comment]
Entering date of birth as "09-09-9999" can save successfully, and returns patient current age as -7981 years. Entering date of birth as "09-09-0999" can save successfully, but patient current age field is blank.

**Comment by gmaloneccg** [comment]
Tested a few more values. It appears as though the field will not accept a year with more than four digits, less than four digits, or the first digit as zero.
