### ISSUE TITLE
Angelman registration country listing not in alphabetical order

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#926]
On the parent/patient registration page, drop-down lists for "Parent/Guardian Country" and patient "Country" are not in alphabetical order. 

[Parent/Patient registration page.](https://rdrf.ccgapps.com.au/angelman/ang/register/)

Examples in the parent/guardian country listing include "Chad" between "Turks and Caicos Islands" and "Togo", "Switzerland" between "Cocos (Keeling) Islands" and "Chile".

**Comment by mouneyrac** [comment]
Once a country is picker, the States are also not sorted properly.
