### ISSUE TITLE
generating reports is timing out on staging

### ISSUE THREAD

**Issue by mouneyrac** [muccg/rdrf#936]

**Comment by mouneyrac** [comment]
I decrease the time from half during inserts. Inserts are the main reasons it takes time so it should considerably reduce the time on prod. Let's check if we still have a timeout.

**Comment by gmaloneccg** [comment]
Four failed reports, with the remainder successful. Separate tickets written per failed report, as requested. Test results available in Drive (two, for successes and failures).
