### ISSUE TITLE
Write PDF Patient Report specs

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#946]
We'll need to get specs from Angela Thurs 5 sep

**Comment by mouneyrac** [comment]
Minute from meeting:
1- clinicians need to send a report of the patient data (can be data from any forms, but we know all of them in the database) to a third party entity
2- the clinician may send it by email / by fax / in person
3- so it is likely we need a printable version (clean html page or PDF) and possibly an email/share option (input field with email? available on the generated html page/pdf?)
4- we suggested the report could be generating from a simple html templating system with placeholder for form/section/cde (need little admin interface)
5- technical difficulty: writing human version of the database value
6- no need to keep generated version (up to the user to record the generated reports) neither information about sent actions
7- the generation of the reports would be from a list of reports accessible on each patient sidebar (basically matching the template name)
