### ISSUE TITLE
Timeout for report "FH Report 2"

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#954]
Attempting to view or download the report "FH Report 2" returns 504 Gateway Timeout.

[Test result in Drive.](https://drive.google.com/open?id=1nLWJo86QTrLoB6nPeV7P8lr69MpDZm-T)

**Comment by mouneyrac** [comment]
fixed by reducing the processing time with code improvement #936 and increasing the timeout of the loadbalancer on AWS #952

**Comment by mouneyrac** [comment]
reopening as it is still timing out on FH contrarely to FH Report

**Comment by mouneyrac** [comment]
We should extend the timeout of the load balancer (as the first solution) - assigning to Lee.

**Comment by mouneyrac** [comment]
timeout has been extended on staging.
