### ISSUE TITLE
Timeout for report "FH test"

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#955]
Attempting to view or download the report "FH test" returns 504 Gateway Timeout.

[Test result in Drive.](https://drive.google.com/open?id=1nLWJo86QTrLoB6nPeV7P8lr69MpDZm-T)

**Comment by mouneyrac** [comment]
fixed by reducing the processing time with code improvement #936 and increasing the timeout of the loadbalancer on AWS #952
