### ISSUE TITLE
Allow syslog logging if configured

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#977]
From Midland email:

" What methods are available by which audit and log data can be accessed and analysed. (We are using a Syslog server for logging purposes)"

**Comment by mouneyrac** [comment]
This is how we would do it for calling remote syslog server:
https://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-python-apps/#examples

Basically it is adding Syslog as a handler and to each logger list.

It is working the same for local Syslog (in the address you put /dev/log)

So I think till the runserver docker container can access the server where Syslog server is running, there won't be an issue.

We will add a env var to set the address.

**Comment by mouneyrac** [comment]
Some info how papertrail allow to use SSL to communicate with it: https://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/#download-root-certificates

**Comment by mouneyrac** [comment]
https://riptutorial.com/django/example/4028/logging-to-syslog-service

**Comment by id2359** [comment]
Again let's expose environment settings so this is configured from Rancher at Midland --> environment --> settings.py
