### ISSUE TITLE
CIC CRC PROMS surveys: Question 10 behaviour

### ISSUE THREAD

**Issue by gmaloneccg** [muccg/rdrf#992]
In the CIC CRC PROMS surveys, for question 10 "Did you need to rest?" (EORTCQLQC30_Q10);
1. The question is asked in the BaselinePROMS survey only if question 9 "Have you had pain?" (EORTCQLQC30_Q09) is provided with the highest-level answer (i.e. "Very much").
2. The question is asked in the FollowUpPROMS survey regardless of the answer to question 9.
3. The question phrasing is unclear; is the question asking if the patient needs to rest because of a high level of pain experienced, as per question 9? This appears to be the case, as it is dependent on the answer to question 9 in the BaselinePROMS survey.

**Comment by mouneyrac** [comment]
That's is likely a survey designer issue. Assigning to you Lee so you can see with Angela.

**Comment by id2359** [comment]
I'll follup up with Angela
