### ISSUE TITLE
Implement LDAP group for Midland

### ISSUE THREAD

**Issue by id2359** [muccg/rdrf#993]
App-MI-CIC-ICHOMCRC

is Colorectal cancer

**Comment by id2359** [comment]
Expose config which is checked in settings.py so I can "set" from Rancher

**Comment by mouneyrac** [comment]
Can we confirm App-MI-CIC-ICHOMCRC is a gidnumber in the LDAP user?

**Comment by mouneyrac** [comment]
Confirm there is a field Email in LDAP

**Comment by mouneyrac** [comment]
Ask what are the field name for Firstname and Lastname (ours are first_name and last_name) - we may need to edit the code if they are different

**Comment by mouneyrac** [comment]
These will be settings variable in rancher (we will need to change some of the values):

      - LDAP_ENABLED=1
      - RDRF_AUTH_LDAP_WORKING_GROUP=ICHOMCRC SJOG Midland
      - RDRF_AUTH_LDAP_AUTH_GROUP=Clinical Staff
      - RDRF_AUTH_LDAP_REGISTRY_MODEL=ICHOMCRC
      - RDRF_AUTH_LDAP_USERS_MUST_BE_STAFF=1
      - RDRF_AUTH_LDAP_ALLOW_SUPERUSER=0
      - RDRF_AUTH_LDAP_REQUIRE_2FA=0
      - AUTH_LDAP_REQUIRE_GROUP=cn=App-MI-CIC-ICHOMCRC,ou=groups,dc=example,dc=com
      - RDRF_AUTH_LDAP_FIRST_NAME_ATTR=username
      - RDRF_AUTH_LDAP_LAST_NAME_ATTR=sn
      - RDRF_AUTH_LDAP_MAIL_ATTR=mail
